----
<div style="display: flex; align-items: center;">
    <img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="20%" style="vertical-align: top;">
    <h1 style="margin-left: 20px;">Data Library for Python</h1>
</div>

----

## Content layer - Ownership - Insider
This notebook demonstrates how to retrieve Ownership insider data.

#### Learn more

To learn more about the LSEG Data Library for Python please join the LSEG Developer Community. By [registering](https://developers.refinitiv.com/iam/register) and [logging](https://developers.refinitiv.com/content/devportal/en_us/initCookie.html) into the LSEG Developer Community portal you will have free access to a number of learning materials 
 on the [LSEG Developer Portal](https://developers.lseg.com/en)

#### Getting Help and Support

If you have any questions regarding using the API, please post them on 
the [LSEG Data Q&A Forum](https://community.developers.refinitiv.com/spaces/321/index.html). 
The LSEG Developer Community will be happy to help.

## Set the configuration file location
For a better ease of use, you have the option to set initialization parameters of the LSEG Data Library in the _lseg-data.config.json_ configuration file. This file must be located beside your notebook, in your user folder or in a folder defined by the _LD_LIB_CONFIG_PATH_ environment variable. The _LD_LIB_CONFIG_PATH_ environment variable is the option used by this series of examples. The following code sets this environment variable.

In [1]:
import os
os.environ["LD_LIB_CONFIG_PATH"] = "../../../Configuration"

## Some Imports to start with

In [1]:
import lseg.data as ld
from lseg.data.content import ownership

## Open the data session

The open_session() function creates and open sessions based on the information contained in the lseg-data.config.json configuration file. Please edit this file to set the session type and other parameters required for the session you want to open.

In [3]:
ld.open_session("platform.ldp")

## Retrieve data

### Insider - Shareholders report

In [3]:
response = ownership.insider.shareholders_report.Definition("LSEG.L").get_data()
response.data.df

,Instrument,Investor Perm Id,Insider Full Name,Investor Parent Type,Investor Type,Investor Region,Investment Style,Orientation,Turnover Rating,Turnover Pct,...,SharesHeld Change,SharesHeld Value Change,% SharesOutstanding Change,SharesHeld Change%,Previous SharesHeld,Previous % SharesOutstanding,Previous SharesHeld Value,Previous Holding sDate,Previous Filing Type,Country
0,LSEG.L,34419998407,Calrow (Robert Derek),Strategic Entities,Individual Investor,Europe,,,LOW,0.0,...,151378,18111151.54,200.0,100.0,151377,0.0285,17667951.42,2024-05-01,UK Registers,United Kingdom
1,LSEG.L,34419998419,Magennis (Yvonne),Strategic Entities,Individual Investor,Europe,,,LOW,0.0,...,0,0.0,100.0,0.0,173348,0.0326,20232294.49,2024-05-01,UK Registers,United Kingdom
2,LSEG.L,34420011959,Nolan (Clodagh),Strategic Entities,Individual Investor,Europe,,,LOW,0.0,...,-12000,-1435702.8,93.39,-6.78,177000,0.0333,20658537.3,2024-05-01,UK Registers,United Kingdom
3,LSEG.L,34422796951,O'Connor (Dennis),Strategic Entities,Individual Investor,Europe,,,LOW,0.0,...,0,0.0,100.0,0.0,147000,0.0277,17157090.3,2024-05-01,UK Registers,Ireland
4,LSEG.L,34422798353,Hodgson (Violet Margaret),Strategic Entities,Individual Investor,Europe,,,LOW,0.0,...,0,0.0,100.0,0.0,126470,0.0238,14760933.4,2024-05-01,UK Registers,United Kingdom
5,LSEG.L,34426709931,Bolshaw (Christopher Michael Ferrington),Strategic Entities,Individual Investor,Europe,,,LOW,5.5915,...,-7050,-739726.18,93.81,-6.32,111550,0.021,9496053.84,2022-09-01,UK Registers,United Kingdom
6,LSEG.L,34416771843,Schwimmer (David J.D.),Strategic Entities,Individual Investor,Europe,,,LOW,11.9818,...,18618,2230108.68,122.88,22.87,81396,0.0153,9119804.29,2024-02-28,Regulatory News Service,United Kingdom
7,LSEG.L,34413354653,Warren (David P),Strategic Entities,Individual Investor,North America,,,LOW,32.9665,...,-39998,-4017021.38,65.28,-34.78,114998,0.0216,9978838.29,2022-10-03,UK Registers,United States
8,LSEG.L,34423095321,Johnson (Catherine),Strategic Entities,Individual Investor,Europe,,,,<NA>,...,0,0.0,100.0,0.0,28806,0.0054,2795229.68,2023-03-06,Regulatory News Service,United Kingdom
9,LSEG.L,34415766064,Roos (Murray),Strategic Entities,Individual Investor,Europe,,,,<NA>,...,12435,1304751.07,271.43,162.68,7644,0.0014,741746.01,2023-03-02,Regulatory News Service,United Kingdom
10,LSEG.L,34425643685,Maguire (Daniel John),Strategic Entities,Individual Investor,Europe,,,,<NA>,...,0,0.0,100.0,0.0,15251,0.0029,1479901.68,2023-03-06,Regulatory News Service,United Kingdom
11,LSEG.L,34413368250,Robert (Donald),Strategic Entities,Individual Investor,Europe,,,LOW,9.8182,...,0,0.0,100.0,0.0,10000,0.0019,1180483.96,2023-12-31,Regulatory News Service,United Kingdom
12,LSEG.L,34413683201,Proch (Michel-Alain),Strategic Entities,Individual Investor,Europe,,,,<NA>,...,9314,1087082.23,<NA>,0.0,<NA>,<NA>,<NA>,NaT,,France
13,LSEG.L,34416785544,Shalders (David),Strategic Entities,Individual Investor,Europe,,,,<NA>,...,-1200,-120516.67,85.0,-11.54,10396,0.002,1104909.31,2023-06-01,Regulatory News Service,United Kingdom
14,LSEG.L,34425290830,Bakhshi (Balbir Singh),Strategic Entities,Individual Investor,Europe,,,,<NA>,...,688,66761.02,116.67,22.25,3092,0.0006,263216.48,2022-09-30,Regulatory News Service,United Kingdom
15,LSEG.L,34424788471,McCarthy (Anthony),Strategic Entities,Individual Investor,Europe,,,,<NA>,...,2666,279731.92,<NA>,0.0,<NA>,<NA>,<NA>,NaT,,United Kingdom
16,LSEG.L,34414129169,Hogg (Cressida M),Strategic Entities,Individual Investor,Europe,,,LOW,25.5816,...,533,63844.02,150.0,46.35,1150,0.0002,128848.78,2024-02-28,Regulatory News Service,United Kingdom
17,LSEG.L,34424691447,Blakemore (Dominic),Strategic Entities,Individual Investor,Europe,,,,<NA>,...,0,0.0,100.0,0.0,1611,0.0003,190175.97,2023-12-31,Regulatory News Service,United Kingdom
18,LSEG.L,34414711186,DeRose (Kathleen Traynor),Strategic Entities,Individual Investor,Europe,,,LOW,0.0,...,0,0.0,100.0,0.0,1500,0.0003,177072.59,2023-12-31,Regulatory News Service,United Kingdom
19,LSEG.L,34414356353,Rahmani (Valerie),Strategic Entities,Individual Investor,North America,,,LOW,42.3359,...,0,0.0,100.0,0.0,1429,0.0003,168691.16,2023-12-31,Regulatory News Service,United States
20,LSEG.L,34414187562,Gebreyes (Tsega),Strategic Entities,Individual Investor,Europe,,,LOW,0.0,...,0,0.0,100.0,0.0,1200,0.0002,141658.07,2023-12-31,Regulatory News Service,United Kingdom
21,LSEG.L,34426045540,Guthrie (Scott),Strategic Entities,Individual Investor,Europe,,,LOW,0.0,...,0,0.0,100.0,0.0,623,0.0001,73544.15,2023-12-31,Regulatory News Service,United Kingdom
22,LSEG.L,34423146057,Vaswani (Ashok),Strategic Entities,Individual Investor,Europe,,,LOW,0.0,...,0,0.0,100.0,0.0,581,0.0001,68586.12,2023-12-31,Regulatory News Service,United Kingdom
23,LSEG.L,34421727989,Calrow (Barbara Elizabeth),Strategic Entities,Individual Investor,Europe,,,LOW,0.0,...,-151378,-18111151.54,0.0,-100.0,151378,0.0285,17668068.13,2024-05-01,UK Registers,United Kingdom
24,LSEG.L,34420009263,Strange (John Cope),Strategic Entities,Individual Investor,Europe,,,,<NA>,...,-85000,-8552575.62,0.0,-100.0,85000,0.016,8536597.27,2023-09-01,UK Registers,United Kingdom
25,LSEG.L,34424483478,Trivedi (Durga Charan),Strategic Entities,Individual Investor,Asia / Pacific,,,HIGH,161.2598,...,-210856,-23296764.79,0.0,-100.0,210856,0.0397,25256837.19,2024-03-01,UK Registers,India

### Insider - Transaction report

In [4]:
response = ownership.insider.transaction_report.Definition("LSEG.L").get_data()
response.data.df

,Instrument,Equity owner name,Date,Investor Type,Insider Role Type,isPrimary InsiderRole,Date Became Insider,Contact NoLonger Exists,Contact NoLonger Exists Date,Insider Inactive Date,...,AsReported SharesHeld,AsReported Indirect SharesHeld,Region,AddrLine1,AddrLine2,AddrLine3,State Province,City,Country,PostalCode
0,LSEG.L,Proch (Michel-Alain),2024-05-03,Individual Investor,Chief Financial Officer,Chief Financial Officer,NaT,<NA>,NaT,NaT,...,9314,<NA>,Europe,,,,,,,
1,LSEG.L,Schwimmer (David J.D.),2024-03-26,Individual Investor,Chief Executive Officer,Chief Executive Officer,NaT,<NA>,NaT,NaT,...,100014,<NA>,Europe,,,,,,,
2,LSEG.L,Hogg (Cressida M),2024-03-19,Individual Investor,Director (Independent),Director (Independent),NaT,<NA>,NaT,NaT,...,1683,<NA>,Europe,,,,,,,
3,LSEG.L,Robert (Donald),2024-02-28,Individual Investor,Chairman of the Board/Chairman of the Board of...,<NA>,NaT,False,NaT,NaT,...,10000,<NA>,Europe,,,,,,,
4,LSEG.L,Rahmani (Valerie),2024-02-28,Individual Investor,,<NA>,NaT,False,NaT,NaT,...,1429,<NA>,North America,,,,,,,
5,LSEG.L,DeRose (Kathleen Traynor),2024-02-28,Individual Investor,,<NA>,NaT,<NA>,NaT,NaT,...,1500,<NA>,Europe,,,,,,,
6,LSEG.L,Blakemore (Dominic),2024-02-28,Individual Investor,Director (Non-Executive),<NA>,NaT,False,NaT,NaT,...,1611,<NA>,Europe,,,,,,,
7,LSEG.L,Gebreyes (Tsega),2024-02-28,Individual Investor,,<NA>,NaT,False,NaT,NaT,...,1200,<NA>,Europe,,,,,,,
8,LSEG.L,Vaswani (Ashok),2024-02-28,Individual Investor,,<NA>,NaT,False,NaT,NaT,...,581,<NA>,Europe,,,,,,,
9,LSEG.L,Guthrie (Scott),2024-02-28,Individual Investor,Director (Non-Executive),<NA>,NaT,<NA>,NaT,NaT,...,623,<NA>,Europe,,,,,,,
10,LSEG.L,Shalders (David),2023-09-11,Individual Investor,Chief Operating Officer,<NA>,NaT,False,NaT,2024-12-31,...,9196,<NA>,Europe,,,,,,,
11,LSEG.L,Roos (Murray),2023-04-24,Individual Investor,,,NaT,False,NaT,NaT,...,20079,<NA>,Europe,,,,,,,
12,LSEG.L,McCarthy (Anthony),2023-04-24,Individual Investor,,,NaT,False,NaT,2024-01-01,...,2666,<NA>,Europe,,,,,,,
13,LSEG.L,Maguire (Daniel John),2023-04-24,Individual Investor,,,NaT,<NA>,NaT,NaT,...,15251,<NA>,Europe,,,,,,,
14,LSEG.L,Johnson (Catherine),2023-04-24,Individual Investor,General Counsel,General Counsel,NaT,<NA>,NaT,NaT,...,28806,<NA>,Europe,,,,,,,
15,LSEG.L,Bakhshi (Balbir Singh),2023-03-07,Individual Investor,,,NaT,<NA>,NaT,NaT,...,3780,<NA>,Europe,,,,,,,
16,LSEG.L,Jones (Tim),2022-03-30,Individual Investor,,<NA>,NaT,False,NaT,2023-01-01,...,4288,<NA>,Europe,,,,,,,
17,LSEG.L,Craig (David William Ian),2021-03-19,Individual Investor,,<NA>,NaT,False,NaT,2021-07-01,...,0,<NA>,North America,,,,,,,
18,LSEG.L,Samad (Waqas),2021-01-29,Individual Investor,,<NA>,NaT,False,NaT,2021-01-29,...,14451,<NA>,Europe,,,,,,,
19,LSEG.L,Cote (Diane),2021-01-29,Individual Investor,,<NA>,NaT,False,NaT,2021-01-25,...,55057,<NA>,Europe,,,,,,,

### Close the session

In [5]:
ld.close_session()