----
<div style="display: flex; align-items: center;">
    <img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="20%" style="vertical-align: top;">
    <h1 style="margin-left: 20px;">Data Library for Python</h1>
</div>

----

## Content layer - IPA - Bond Pricing
This notebook demonstrates how to use Bond pricing analytics.

#### Learn more

To learn more about the LSEG Data Library for Python please join the LSEG Developer Community. By [registering](https://developers.refinitiv.com/iam/register) and [logging](https://developers.refinitiv.com/content/devportal/en_us/initCookie.html) into the LSEG Developer Community portal you will have free access to a number of learning materials 
 on the [LSEG Developer Portal](https://developers.lseg.com/en)

#### Getting Help and Support

If you have any questions regarding using the API, please post them on 
the [LSEG Data Q&A Forum](https://community.developers.refinitiv.com/spaces/321/index.html). 
The LSEG Developer Community will be happy to help.

## Set the configuration file location
For a better ease of use, you have the option to set initialization parameters of the LSEG Data Library in the _lseg-data.config.json_ configuration file. This file must be located beside your notebook, in your user folder or in a folder defined by the _LD_LIB_CONFIG_PATH_ environment variable. The _LD_LIB_CONFIG_PATH_ environment variable is the option used by this series of examples. The following code sets this environment variable.

In [16]:
import os
os.environ["LD_LIB_CONFIG_PATH"] = "../../../Configuration"

## Some Imports to start with

In [17]:
import lseg.data as ld
from lseg.data.content.ipa.financial_contracts import bond

## Open the data session

The open_session() function creates and open sessions based on the information contained in the lseg-data.config.json configuration file. Please edit this file to set the session type and other parameters required for the session you want to open.

In [18]:
ld.open_session()

## Retrieve data

### Simple Bond

In [23]:
response = bond.Definition(instrument_code="US10YT=RR").get_data()
response.data.df

,InstrumentTag,InstrumentCode,BondType,AssetStatus,InstrumentDescription,RIC,Isin,Ticker,Cusip,Sedol,...,InflationCurrentIndex,InflationMode,AdjustedAccrued,AdjustedYieldPercent,AdjustedCleanPrice,AdjustedDirtyPrice,ParValue,ErrorCode,ErrorMessage,ProcessingInformation
0,<NA>,US10YT=RR,FixedRateBond,Issued,UST 4.375 05/15/34,US10YT=RR,US91282CKQ32,UST,91282CKQ3,BSD4JJ6,...,<NA>,Unadjusted,0,<NA>,<NA>,<NA>,100,,,The default value 3M is returned in AssetSwapS...

### User defined Bond

In [6]:
response = bond.Definition(
            issue_date = "2002-02-28",
            end_date = "2032-02-28",
            notional_ccy = "USD",
            interest_payment_frequency = "Annual",
            fixed_rate_percent = 7,
            interest_calculation_method = "Dcb_Actual_Actual"
        ).get_data()

response.data.df

,InstrumentTag,InstrumentCode,BondType,AssetStatus,InstrumentDescription,RIC,Isin,Ticker,Cusip,Sedol,...,InflationCurrentIndex,InflationMode,AdjustedAccrued,AdjustedYieldPercent,AdjustedCleanPrice,AdjustedDirtyPrice,ParValue,ErrorCode,ErrorMessage,ProcessingInformation
0,<NA>,<NA>,FixedRateBond,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,Unadjusted,0,<NA>,<NA>,<NA>,100,,,The default value 3M is returned in AssetSwapS...

### Fields selection

In [7]:
response = bond.Definition(
    instrument_code = 'US1YT=RR',
    fields = [
        "InstrumentCode",
        "MarketDataDate",
        "YieldPercent",
        "GovernmentSpreadBp",
        "GovCountrySpreadBp",
        "RatingSpreadBp",
        "SectorRatingSpreadBp",
        "EdsfSpreadBp",
        "IssuerSpreadBp"
    ]
).get_data()

response.data.df

,InstrumentCode,MarketDataDate,YieldPercent,GovernmentSpreadBp,GovCountrySpreadBp,RatingSpreadBp,SectorRatingSpreadBp,EdsfSpreadBp,IssuerSpreadBp
0,US1YT=RR,2024-06-13 08:55:54,5.116334,0,-0.001636,-37.119383,<NA>,<NA>,<NA>

### Pricing parameters

In [8]:
response = bond.Definition(
    instrument_code = 'US1YT=RR',
    fields = [
        "InstrumentCode",
        "MarketDataDate",
        "YieldPercent",
        "GovernmentSpreadBp",
        "GovCountrySpreadBp",
        "RatingSpreadBp",
        "SectorRatingSpreadBp",
        "EdsfSpreadBp",
        "IssuerSpreadBp"
    ],
    pricing_parameters = bond.PricingParameters(
        market_data_date="2019-07-05",
        price_side = bond.PriceSide.BID
    )
).get_data()

display(response.data.df)

,InstrumentCode,MarketDataDate,YieldPercent,GovernmentSpreadBp,GovCountrySpreadBp,RatingSpreadBp,SectorRatingSpreadBp,EdsfSpreadBp,IssuerSpreadBp
0,US1YT=RR,2019-07-05,1.989924,0,-2.796619,<NA>,<NA>,<NA>,<NA>

## Close the session

In [9]:
ld.close_session()