# LD Lib. Python Tutorial 4 - get_history

## LSEG Data Model

The LSEG Data Platform is, well, a platform. More specifically, this platform hosts many API Families which themselves host individual APIs which allow users to access data (e.g.: historical end-of-business-day (i.e.: close) prices for a company's publically floated equity (i.e.: stock)) or services (e.g.: calculations). Each individual service within each API can be accessed via endpoints, that are simply just addresses where our computers can send requests. You can think of this like your computer sending a letter detailing the request you asked for; e.g.: Vodafone's stock price last year. You need to know which endpoint to use when sending requests. Documentation about endpoint names, and the structure in which requests can be made can be found on the [API Playground](https://apidocs.refinitiv.com/Apps/ApiDocs). This playground is, however, behind a paywall accesible only to LSEG clients via their user credentials (username and passwords). But you may be interested in the Data Model before becoming a client, so to serve such stakeholders, we have created the [LSEG Developer Portal](https://developers.lseg.com/en) on which detailed Documentation (and more) can be found (mostly) publicly. You can also find informaion about other APIs (i.e.: APIs not hosted within the LSEG Data Platform, e.g.: Datastream) on this Developer Portal, but these are outside the scope of this tutorial.


<img src="DataModel.PNG">

## LSEG Data Library

Anyone with a license can send requests to these endpoints and receive a response. One may choose to program their computer to do so using C++ or JAVA or any other coding language of choice; however, we decided to help developers and created functions in the most popular programing languages, Python, TypeScript and .Net. These functions were simple when 1st developed (e.g.: send all requests to the `historical-pricing` endpoint because it is the most popular one), but got more complex with time. In the case of Python, we decided to wrap as many functions as possible into a library, the LSEG Data Library (LDL).

Within this library, you can use the Delivery Layer functions to send requests to specific endpoints, but it is the most complex use-case of the LDL, since it requires us to know exactly which endpoint to use, and how to request for data/services from that assosiated API. We therefore created another set of functions, called the Content Layer, which renamed endpoints to more intuitive names, and allows us to structure our requests in a simpler, uniform, way. We noticed, however, that that some functions were more popular than others, much more, and therefore decided to siplify them even more! We packaged these into the last layer, the Access Layer.

Since the Access Layer is the simplest, we will start our tutorial there.

## Install & Import the LSEG Data Library

To install libraries in python, you can find the command in PyPl, in this instance, it is:

In [2]:
# pip install lseg.data

In [6]:
import lseg.data as ld

## Quick Introduction to the Workspace Desktop App, Workspace Web app, and LDL Sessions

1st, a little refresh on the clasical ‘product’ LSEG sells: the [Workspace Desktop App](https://www.refinitiv.com/en/products/refinitiv-workspace/download-workspace?_ga=2.91796954.1111853358.1688972213-1243864833.1674474112). Desktop apps differ from other applications in that they have to be downloaded and installed on your machine to work; one cannot, for example, access it on a web-page. They exist in contrast to their Web Apps; indeed, as per popular demand, we’ve made a web version of the LSEG Workspace application too: [Workspace Web](https://eikon.thomsonreuters.com/index.html), for which training can be found [here](https://my.refinitiv.com/content/mytr/en/policies/training-portal/refinitivworkspacenew/refinitivworkspacewebaccess.html?_ga=2.59282029.1111853358.1688972213-1243864833.1674474112).

The Workspace Desktop App is a desktop application that works on Windows and Mac. We are still in the process of onboarding all our datasets on that app, meaning that some (but few) datasets viewable on the Workspace Desktop App are not available via the LSEG Data Platform, and *vice versa*. On the other hand, we are also onboarding new datasets all the time, as per the nature of our company, and we tend to onboard them on both the Workspace Desktop App and LSEG Data Platform, to homogenise our data models.

N.B.: While some data providers are incorporated into our Apps and [APIs](https://www.mulesoft.com/resources/api/what-is-an-api), they might require you to pay them directly and get a license with them directly (e.g.: if you would like MSCI dataset access on LSEG Apps, you will need an MSCI license with MSCI separate from any LSEG license you may have).

The LSEG Data Platform can only be used with one of two sessions called ‘desktop’ and ‘platform’. When using the desktop session, one needs to their Workspace Desktop App running on the machine on which the API (LDL) is being used; this is not required when using the platform session.

a. When using the desktop session, the only credential needed to access Refinitiv datasets is your app key, information for which can be found [here](https://developers.refinitiv.com/en/api-catalog/eikon/eikon-data-api/quick-start); this is because the desktop app handles all other credentials to authenticate you to the LSEG system.

b. When using the platform session, one needs their App Key and user credentials (login & password).

## Desktop Session

### Authentification to LSEG Service

Desktop session use-cases are the simples ones, so let's start there. We can authenticate ourselves with the Workspace Desktop App open with simply just the Python line:

In [7]:
ld.open_session()

### Using the Python Data Library

Now that we are authenticated to the LSEG systems, we can start getting data from LSEG dataframes. We used the [`get_data`](https://github.com/Refinitiv-API-Samples/Example.DataLibrary.Python/blob/main/Examples/1-Access/EX-1.01.01-GetData.ipynb) functionin the past; let's now look into the [`get_history`](https://github.com/Refinitiv-API-Samples/Example.DataLibrary.Python/blob/main/Examples/1-Access/EX-1.01.02-GetHistory.ipynb) function:

In [8]:
df4 = ld.get_history(
    universe=['LSEG.L', 'MSFT'],
    fields=["BID", "ASK", "TR.Revenue", "TR.TURNOVER"],
    interval="H",
    start="2015-01-01T06:00:00",
    end="2019-10-01T09:30:00",
    adjustments="RPO",  # RPO - Apply Refinitiv Price Only adjustment to adjust historical price only not volume
    count=10)  # Max is 10000
df4

ValueError: Not supported interval value.
Supported intervals are: ['tick', 'tas', 'taq', 'minute', '1min', '5min', '10min', '30min', '60min', 'hourly', '1h', 'daily', '1d', '1D', '7D', '7d', 'weekly', '1W', 'monthly', '1M', 'quarterly', '3M', '6M', 'yearly', '12M', '1Y']

In [9]:
df4 = ld.get_history(
    universe='LSEG.L',
    fields=["BID", "ASK"],
    interval="hourly",
    start="2024-01-01T06:00:00",
    end="2024-10-01T19:30:00",
    adjustments="RPO",
    count=10)
df4

LSEG.L                BID   ASK
Timestamp
2024-06-05 07:00:00  9310  9314
2024-06-05 08:00:00  9298  9300
2024-06-05 09:00:00  9278  9282
2024-06-05 10:00:00  9282  9286
2024-06-05 11:00:00  9292  9294
2024-06-05 12:00:00  9308  9312
2024-06-05 13:00:00  9312  9316
2024-06-05 14:00:00  9344  9348
2024-06-05 15:00:00  9332  9360
2024-06-05 16:00:00  8700  9400

But how do you know how to use these functions? Are there more parameters in the `get_history` function in addition to `universe`, `fields`, `interval`, `start` and `end`? You will find great example uses on [GitHub](https://github.com/Refinitiv-API-Samples/Example.DataLibrary.Python/tree/main) and on [Articles](https://developers.refinitiv.com/en/article-catalog), but they are only a small set of possible use-cases and examples. That's where documentation comes into play! You can find the documentation [here](https://developers.refinitiv.com/en/api-catalog/refinitiv-data-platform/refinitiv-data-library-for-python/documentation), and also in the [docstrings](https://peps.python.org/pep-0257/) that you can find in this way:

In [13]:
help(ld.get_history)  # You can also try `help(dl.get_data)` and most/all function sin Python in general.

Help on function get_history in module lseg.data._access_layer.get_history_func:

get_history(universe: Union[str, Iterable[str]], fields: Union[str, Iterable[str], NoneType] = None, interval: Optional[str] = None, start: 'OptDateTime' = None, end: 'OptDateTime' = None, adjustments: Optional[str] = None, count: Optional[int] = None, parameters: Union[str, dict, NoneType] = None, header_type: lseg.data.content._header_type.HeaderType = <HeaderType.TITLE: 2>) -> pandas.core.frame.DataFrame
    Retrieves the pricing history, as well as Fundamental and Reference data history.

    Parameters
    ----------
    universe: str | list
        Instruments to request
    fields: str | list, optional
        Fields to request
    interval: str, optional
        Date interval. Supported intervals are:
        tick, tas, taq, minute, 1min, 5min, 10min, 30min, 60min, hourly, 1h, daily,
        1d, 1D, 7D, 7d, weekly, 1W, monthly, 1M, quarterly, 3M, 6M, yearly, 1Y
    start: str or date or datetime or timedelta, optional
        The start date and timestamp of the requested history
    end: str or date or datetime or timedelta, optional
        The end date and timestamp of the requested history
    adjustments : str, optional
        Tells the system whether to apply or not apply CORAX (Corporate Actions)
        events or exchange/manual corrections or price and volume adjustment
        according to trade/quote qualifier summarization actions to historical time
        series data. Possible values are:
        exchangeCorrection, manualCorrection, CCH, CRE, RTS, RPO, unadjusted,
        qualifiers
    count : int, optional
        The maximum number of data points returned. Values range: 1 - 10000.
        Applies only to pricing fields.
    parameters: str | dict, optional
        Single global parameter key=value or dictionary
        of global parameters to request.
        Applies only to TR fields.
    header_type: HeaderType, default HeaderType.TITLE
        If HeaderType.TITLE - returns field title as column headers for data
        If HeaderType.NAME - returns field name as column headers for data
        If HeaderType.NAME_AND_TITLE - returns field name and title as column headers for data

    Returns
    -------
    pandas.DataFrame

    Examples
    --------
    >>> get_history(universe="GOOG.O")
    >>> get_history(universe="GOOG.O", fields="tr.Revenue", interval="1Y")
    >>> get_history(
    ...     universe="GOOG.O",
    ...     fields=["BID", "ASK", "tr.Revenue"],
    ...     interval="1Y",
    ...     start="2015-01-01",
    ...     end="2020-10-01",
    ... )

### Where to go to find the available fields that I can access using the Data Libraries (such as the LD Python Library)?

Now that you have access to the LSEG API functions in Python, how can you figure out what field names you can use? You can using Workspace to figure out available fields, as shown [here](https://developers.refinitiv.com/en/article-catalog/article/summary-of-common-lseg-refinitiv-apis), but I prefer using the [DIB](https://developers.refinitiv.com/en/video-catalog/data-item-browser):

In DIB, I search ‘Vodafone’ for the instrument to request and ‘average daily value’ for the field. You get automatically a list of fields matching your request. In our case, the ADV — 5 days is equal to 16.117290

<img src="https://developers.refinitiv.com/content/dam/devportal/articles/Summary-of-Common-LSEG-Refinitiv-APIs/e.png">

In [ ]:
ld.close_session()

## Platform Session

Platform sessions allow us to use the LD Lib. without the Workspace Desktop App open. It was created for servers, and it is still aimed for data hungry users who require little human interation with the code at hand (e.g.: overnight data retraival). With that said, usecases have grown in breadth and complexity thoughout the years, and people may want such 'ping' services (i.e.: the ability to 'ping', to directly contact, the services that deliver data/calculations, without going through the Desktop App Proxy).

### Authentification to LSEG Service

Platform session use-cases are a little more complicated to the Desktop session ones. We can authenticate ourselves with the Workspace Desktop App open with simply just the Python line:

In [4]:
import lseg.data as ld

In [5]:
ld.open_session(
    config_name="C:/Example.DataLibrary.Python-main/Configuration/refinitiv-data.config.json",
    name="platform.jlrdp")

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\lseg\data\_access_layer\session.py:71:FutureWarning:
You open a platform session using the default value of the signon_control parameter (signon_control=True).
In future library version v2.0, this default will be changed to False.
If you want to keep the same behavior as today, you will need to set the signon_control parameter to True either in the library configuration file
({'sessions':{'platform':{'your_session_name':{'signon_control':true}}}}) or in your code where you create the Platform Session.
These alternative options are already supported in the current version of the library.

You will need a configuration file to authenticate yourself to the LSEG services. I named mine "refinitiv-data.config.json" and put them in the location "C:/Example.DataLibrary.Python-main/Configuration/"; it resembles somehting like this:

<img src="https://developers.lseg.com/content/dam/devportal/articles/Summary-of-Common-LSEG-Refinitiv-APIs/c.png">

In [23]:
ld.get_history(
    universe='LSEG.L',
    fields=["BID", "ASK"],
    start="2024-01-01",
    end="2024-10-01")

LSEG.L       BID   ASK
Date
2024-01-02  9138  9140
2024-01-03  9022  9024
2024-01-04  9010  9014
2024-01-05  8980  8982
2024-01-08  9008  9010
...          ...   ...
2024-05-30  9096  9098
2024-05-31  9160  9162
2024-06-03  9148  9150
2024-06-04  9282  9284
2024-06-05  9338  9342

[108 rows x 2 columns]