<div style="display: flex; align-items: center;">
    <img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="20%" style="vertical-align: top;">
    <h1 style="margin-left: 20px;">LD Lib. Python Tutorial 8 - Chain</h1>
</div>

## Chains

We spoke at length about the LSEG Data Model. Let's not repeat ourselves, and instead forcuss on the task at hand: Chains.

### What are Chains?

As best described by [Raksina](https://developers.lseg.com/en/article-catalog/article/Retrieve-underlying-Instrument-of-Chain-Symbol), "Chains are used to hold instrument names that have a common association. For example, a chain may contain the constituents of a market index like the Dow Jones or the list of strike prices on a particular option contract. It is important to note that chains contain the instrument names (a.k.a. RICs - Refinitiv Instrument Codes) but not the values of the instruments."

## Install & Import the LSEG Data Library

To install libraries in python, you can find the command in PyPl with `pip install lseg.data`, in this instance, it is:

In [1]:
import lseg.data as ld
import datetime
from IPython.display import display, clear_output

There are two sessions you can use to authenticate yourself to the LSEG Data Platform, the Desktop Session and Platform Session.

The Desktop Session allows you to access data in LSEG's Data Platform via the Desktop Workspace Application on the machine where you are running your code, meaning taht you need to have Workspace running on the machine where you are running your Python code. This is because this session funnels requests made to LSEG's servers through the desktop application. When using the Desktop Session, you need very little information, because you already inputed your username and password in the desktop application to logg in.

The Platform Session allows you to authenticate yourself to LSEG's Data Platform without the Desktop Application. This does, however, mean that you have to entre your credentials (e.g.: in a [reference configuration file](https://developers.lseg.com/en/api-catalog/lseg-data-platform/lseg-data-library-for-python/tutorials#tutorial-3-sessions-configurations-data-model-and-get-data)).

Let's start  with the Desktop Session:

## Access Layer

### Desktop Session

#### Authentification to LSEG Service

Desktop session use-cases are the simples ones, so let's start there. We can authenticate ourselves with the Workspace Desktop App open with simply just the Python line:

In [2]:
ld.open_session()

#### Create a chain object for the CAC40 index

In [3]:
fchi = ld.discovery.Chain("0#.FCHI")

In [4]:
print(fchi.constituents)

['ACCP.PA', 'AIRP.PA', 'AIR.PA', 'MT.AS', 'AXAF.PA', 'BNPP.PA', 'BOUY.PA', 'BVI.PA', 'CAPP.PA', 'CARR.PA', 'CAGR.PA', 'DANO.PA', 'DAST.PA', 'EDEN.PA', 'ENGIE.PA', 'ESLX.PA', 'EUFI.PA', 'HRMS.PA', 'PRTP.PA', 'OREP.PA', 'LVMH.PA', 'LEGD.PA', 'MICP.PA', 'ORAN.PA', 'PERP.PA', 'PUBP.PA', 'RENA.PA', 'SAF.PA', 'SGOB.PA', 'SASY.PA', 'SCHN.PA', 'SOGN.PA', 'STLAM.PA', 'STMPA.PA', 'TEPRF.PA', 'TCFP.PA', 'TTEF.PA', 'URW.PA', 'VIE.PA', 'SGEF.PA', 'VIV.PA']

In [5]:
fchi.name

'0#.FCHI'

In [6]:
fchi.summary_links

['.DJI', 'EUR=', '/.STOXX50E', '.FCHI', '.AD.FCHI']

#### Use the chain with get_history

In [7]:
ld.get_history(fchi, ['BID', 'ASK'])

           ACCP.PA        AIRP.PA          AIR.PA          MT.AS         \
               BID    ASK     BID     ASK     BID     ASK    BID    ASK
Date
2025-01-22   49.02  49.07  162.38  162.46   165.0  165.14   22.5  22.52
2025-01-23   48.57  48.58  161.72   161.8  166.66  166.68  22.97  22.98
2025-01-24   48.98  48.99  163.74  163.76   167.0  167.04  23.71  23.73
2025-01-27   48.88  48.93  165.92  165.96  165.84  166.52  23.75  23.76
2025-01-28   49.46  49.51  166.66  166.72  166.76   166.8  23.72  23.73
2025-01-29   49.37  49.45   167.0   167.4  166.62  166.76  23.79   23.8
2025-01-30   49.56  49.65  169.14  169.16  166.32  166.44  24.27  24.32
2025-01-31   49.75  49.77  168.46   168.6  167.12  167.14  24.17  24.21
2025-02-03   49.08  49.09   167.8  167.84  166.58   166.6  23.76  23.77
2025-02-04   49.35  49.36  168.28  168.32   166.0  166.04  24.18  24.23
2025-02-05   49.17  49.27  167.22  167.64   166.9  166.92  24.35  24.36
2025-02-06   49.96  50.04  170.02  170.32  167.78   167.9  27.61  27.64
2025-02-07    49.9  49.96  168.98  169.12  166.92  166.96  27.36  27.38
2025-02-10   50.38  50.48  169.76  169.78  167.44   167.5  27.19   27.2
2025-02-11    49.7  49.72  170.44  170.64  167.22   167.5  26.67  26.68
2025-02-12    49.9  49.92  170.78  170.82  169.78  169.88  26.84  26.85
2025-02-13   49.92  49.93  173.08  173.26  169.98   170.1   27.7  27.71
2025-02-14   50.28  50.46   174.1  174.14   168.5  168.52  27.22  27.27
2025-02-17   50.12  50.14  173.98   174.0  170.46   170.5  27.87  27.88
2025-02-18   49.52  49.54  174.32  174.64  172.98   173.0  27.71  27.84

           AXAF.PA         ... TTEF.PA        URW.PA        VIE.PA         \
               BID    ASK  ...     BID    ASK    BID    ASK    BID    ASK
Date                       ...
2025-01-22   35.72  35.73  ...   56.37  56.39   74.4  74.42  27.14  27.15
2025-01-23   36.12  36.13  ...   56.14  56.32  75.72  75.74  27.17  27.18
2025-01-24   35.89   35.9  ...   55.83  55.84  76.72  76.82  26.94  26.96
2025-01-27   36.35  36.36  ...   55.69  55.76  78.24  78.28  27.13  27.14
2025-01-28   36.65  36.68  ...   55.74  55.76  79.36  79.38  27.48  27.49
2025-01-29   36.48  36.49  ...    55.8  55.81  79.38  79.56  27.37  27.38
2025-01-30   36.68  36.69  ...   56.16  56.17   80.1   80.2  27.54  27.55
2025-01-31   36.65  36.66  ...   56.38  56.39  80.66  80.86  27.55   27.6
2025-02-03   36.35  36.37  ...   55.97  55.98   79.7   79.8  27.35  27.36
2025-02-04   37.06  37.08  ...   57.02  57.03  79.08  79.18  27.75  27.77
2025-02-05   36.92  36.95  ...    58.0  58.01  80.08  80.14  27.39  27.47
2025-02-06   37.38  37.39  ...   58.61  58.62  81.52   81.6  27.75  27.77
2025-02-07   37.56  37.58  ...   58.88  58.89   81.1  81.12  27.77  27.79
2025-02-10   37.73  37.76  ...   58.62  58.63  81.82   81.9  27.64  27.72
2025-02-11    38.0  38.02  ...   58.85  58.86  81.96   82.0  27.35  27.46
2025-02-12   38.02  38.05  ...    59.0  59.01   82.3  82.32  26.78  26.91
2025-02-13    38.0  38.04  ...   58.69   58.7  78.94  78.98  27.41  27.46
2025-02-14    37.5  37.53  ...   58.88  58.89  80.48   80.5   27.6  27.63
2025-02-17   37.59   37.6  ...    58.9  58.91  79.96   80.2  27.71  27.75
2025-02-18   37.53  37.63  ...   59.09  59.12  80.16   80.3  27.37  27.44

           SGEF.PA         VIV.PA
               BID     ASK    BID    ASK
Date
2025-01-22  102.75   102.9  2.464  2.465
2025-01-23   103.9  103.95  2.433  2.434
2025-01-24   102.3  102.35  2.445  2.456
2025-01-27  103.45   103.9  2.598  2.599
2025-01-28  104.45   104.5  2.589  2.595
2025-01-29   103.1  103.35  2.616  2.637
2025-01-30   104.5  104.65  2.688  2.693
2025-01-31   104.5  104.55  2.726  2.728
2025-02-03   104.1  104.15   2.77  2.771
2025-02-04   105.6   105.7  2.748  2.751
2025-02-05   105.3  105.45  2.707  2.709
2025-02-06  107.25   107.3  2.706  2.711
2025-02-07  109.85   109.9  2.815  2.817
2025-02-10   108.2   108.3  2.894  2.898
2025-02-11  106.75   106.8   2.94  2.961
2025-02-12   107.0  107.05   2.96  2.971
2025-02-13   108.0  108.05  3.007  3.008
2025-02-14   108.3  108.35   3.04  3.049
2025-02-17   109.2   109.3  2.945   2.96
2025-02-18  110.05   110.1   2.98  2.981

[20 rows x 82 columns]

#### Use the chain with get_data: An Options Use Case

In [8]:
optns4AllMatur4DAX = ld.discovery.Chain("0#GDAX*.EX")
print(optns4AllMatur4DAX.constituents)

['GDAX145000B5.EX', 'GDAX145000N5.EX', 'GDAX146000B5.EX', 'GDAX146000N5.EX', 'GDAX147000B5.EX', 'GDAX147000N5.EX', 'GDAX148000B5.EX', 'GDAX148000N5.EX', 'GDAX149000B5.EX', 'GDAX149000N5.EX', 'GDAX150000B5.EX', 'GDAX150000N5.EX', 'GDAX151000B5.EX', 'GDAX151000N5.EX', 'GDAX152000B5.EX', 'GDAX152000N5.EX', 'GDAX153000B5.EX', 'GDAX153000N5.EX', 'GDAX154000B5.EX', 'GDAX154000N5.EX', 'GDAX155000B5.EX', 'GDAX155000N5.EX', 'GDAX156000B5.EX', 'GDAX156000N5.EX', 'GDAX157000B5.EX', 'GDAX157000N5.EX', 'GDAX158000B5.EX', 'GDAX158000N5.EX', 'GDAX159000B5.EX', 'GDAX159000N5.EX', 'GDAX160000B5.EX', 'GDAX160000N5.EX', 'GDAX161000B5.EX', 'GDAX161000N5.EX', 'GDAX162000B5.EX', 'GDAX162000N5.EX', 'GDAX163000B5.EX', 'GDAX163000N5.EX', 'GDAX164000B5.EX', 'GDAX164000N5.EX', 'GDAX165000B5.EX', 'GDAX165000N5.EX', 'GDAX166000B5.EX', 'GDAX166000N5.EX', 'GDAX167000B5.EX', 'GDAX167000N5.EX', 'GDAX168000B5.EX', 'GDAX168000N5.EX', 'GDAX169000B5.EX', 'GDAX169000N5.EX', 'GDAX170000B5.EX', 'GDAX170000N5.EX', 'GDAX171000B5.EX', 'GDAX171000N5.EX', 'GDAX172000B5.EX', 'GDAX172000N5.EX', 'GDAX173000B5.EX', 'GDAX173000N5.EX', 'GDAX174000B5.EX', 'GDAX174000N5.EX', 'GDAX174500B5.EX', 'GDAX174500N5.EX', 'GDAX175000B5.EX', 'GDAX175000N5.EX', 'GDAX175500B5.EX', 'GDAX175500N5.EX', 'GDAX176000B5.EX', 'GDAX176000N5.EX', 'GDAX176500B5.EX', 'GDAX176500N5.EX', 'GDAX177000B5.EX', 'GDAX177000N5.EX', 'GDAX177500B5.EX', 'GDAX177500N5.EX', 'GDAX178000B5.EX', 'GDAX178000N5.EX', 'GDAX178500B5.EX', 'GDAX178500N5.EX', 'GDAX179000B5.EX', 'GDAX179000N5.EX', 'GDAX179500B5.EX', 'GDAX179500N5.EX', 'GDAX180000B5.EX', 'GDAX180000N5.EX', 'GDAX180500B5.EX', 'GDAX180500N5.EX', 'GDAX181000B5.EX', 'GDAX181000N5.EX', 'GDAX181500B5.EX', 'GDAX181500N5.EX', 'GDAX182000B5.EX', 'GDAX182000N5.EX', 'GDAX182500B5.EX', 'GDAX182500N5.EX', 'GDAX183000B5.EX', 'GDAX183000N5.EX', 'GDAX183500B5.EX', 'GDAX183500N5.EX', 'GDAX184000B5.EX', 'GDAX184000N5.EX', 'GDAX184500B5.EX', 'GDAX184500N5.EX', 'GDAX185000B5.EX', 'GDAX185000N5.EX', 'GDAX185500B5.EX', 'GDAX185500N5.EX', 'GDAX186000B5.EX', 'GDAX186000N5.EX', 'GDAX186500B5.EX', 'GDAX186500N5.EX', 'GDAX187000B5.EX', 'GDAX187000N5.EX', 'GDAX187500B5.EX', 'GDAX187500N5.EX', 'GDAX188000B5.EX', 'GDAX188000N5.EX', 'GDAX188500B5.EX', 'GDAX188500N5.EX', 'GDAX189000B5.EX', 'GDAX189000N5.EX', 'GDAX189500B5.EX', 'GDAX189500N5.EX', 'GDAX190000B5.EX', 'GDAX190000N5.EX', 'GDAX190500B5.EX', 'GDAX190500N5.EX', 'GDAX191000B5.EX', 'GDAX191000N5.EX', 'GDAX191500B5.EX', 'GDAX191500N5.EX', 'GDAX192000B5.EX', 'GDAX192000N5.EX', 'GDAX192500B5.EX', 'GDAX192500N5.EX', 'GDAX193000B5.EX', 'GDAX193000N5.EX', 'GDAX193500B5.EX', 'GDAX193500N5.EX', 'GDAX194000B5.EX', 'GDAX194000N5.EX', 'GDAX194500B5.EX', 'GDAX194500N5.EX', 'GDAX195000B5.EX', 'GDAX195000N5.EX', 'GDAX195500B5.EX', 'GDAX195500N5.EX', 'GDAX196000B5.EX', 'GDAX196000N5.EX', 'GDAX196500B5.EX', 'GDAX196500N5.EX', 'GDAX197000B5.EX', 'GDAX197000N5.EX', 'GDAX197500B5.EX', 'GDAX197500N5.EX', 'GDAX198000B5.EX', 'GDAX198000N5.EX', 'GDAX198500B5.EX', 'GDAX198500N5.EX', 'GDAX199000B5.EX', 'GDAX199000N5.EX', 'GDAX199500B5.EX', 'GDAX199500N5.EX', 'GDAX200000B5.EX', 'GDAX200000N5.EX', 'GDAX200500B5.EX', 'GDAX200500N5.EX', 'GDAX201000B5.EX', 'GDAX201000N5.EX', 'GDAX201500B5.EX', 'GDAX201500N5.EX', 'GDAX202000B5.EX', 'GDAX202000N5.EX', 'GDAX202500B5.EX', 'GDAX202500N5.EX', 'GDAX203000B5.EX', 'GDAX203000N5.EX', 'GDAX203500B5.EX', 'GDAX203500N5.EX', 'GDAX204000B5.EX', 'GDAX204000N5.EX', 'GDAX204500B5.EX', 'GDAX204500N5.EX', 'GDAX205000B5.EX', 'GDAX205000N5.EX', 'GDAX205500B5.EX', 'GDAX205500N5.EX', 'GDAX206000B5.EX', 'GDAX206000N5.EX', 'GDAX206500B5.EX', 'GDAX206500N5.EX', 'GDAX207000B5.EX', 'GDAX207000N5.EX', 'GDAX207500B5.EX', 'GDAX207500N5.EX', 'GDAX208000B5.EX', 'GDAX208000N5.EX', 'GDAX208500B5.EX', 'GDAX208500N5.EX', 'GDAX209000B5.EX', 'GDAX209000N5.EX', 'GDAX209500B5.EX', 'GDAX209500N5.EX', 'GDAX210000B5.EX', 'GDAX210000N5.EX', 'GDAX210250B5.EX', 'GDAX210250N5.EX', 'GDAX210500B5.EX', 'GDAX210500N5.EX', 'GDAX210750B5.EX', 'GDAX210750N5.EX', 'GDAX211000B5.EX', 'GDAX211000N5.EX', 'GDAX211250B5.EX', 'GDAX211250N5.EX', 'GDAX211500B5.EX', 'GDAX211500N5.EX', 'GDAX211750B5.EX', 'GDAX211750N5.EX', 'GDAX212000B5.EX', 'GDAX212000N5.EX', 'GDAX212250B5.EX', 'GDAX212250N5.EX', 'GDAX212500B5.EX', 'GDAX212500N5.EX', 'GDAX212750B5.EX', 'GDAX212750N5.EX', 'GDAX213000B5.EX', 'GDAX213000N5.EX', 'GDAX213250B5.EX', 'GDAX213250N5.EX', 'GDAX213500B5.EX', 'GDAX213500N5.EX', 'GDAX213750B5.EX', 'GDAX213750N5.EX', 'GDAX214000B5.EX', 'GDAX214000N5.EX', 'GDAX214250B5.EX', 'GDAX214250N5.EX', 'GDAX214500B5.EX', 'GDAX214500N5.EX', 'GDAX214750B5.EX', 'GDAX214750N5.EX', 'GDAX215000B5.EX', 'GDAX215000N5.EX', 'GDAX215250B5.EX', 'GDAX215250N5.EX', 'GDAX215500B5.EX', 'GDAX215500N5.EX', 'GDAX215750B5.EX', 'GDAX215750N5.EX', 'GDAX216000B5.EX', 'GDAX216000N5.EX', 'GDAX216250B5.EX', 'GDAX216250N5.EX', 'GDAX216500B5.EX', 'GDAX216500N5.EX', 'GDAX216750B5.EX', 'GDAX216750N5.EX', 'GDAX217000B5.EX', 'GDAX217000N5.EX', 'GDAX217250B5.EX', 'GDAX217250N5.EX', 'GDAX217500B5.EX', 'GDAX217500N5.EX', 'GDAX217750B5.EX', 'GDAX217750N5.EX', 'GDAX218000B5.EX', 'GDAX218000N5.EX', 'GDAX218250B5.EX', 'GDAX218250N5.EX', 'GDAX218500B5.EX', 'GDAX218500N5.EX', 'GDAX218750B5.EX', 'GDAX218750N5.EX', 'GDAX219000B5.EX', 'GDAX219000N5.EX', 'GDAX219250B5.EX', 'GDAX219250N5.EX', 'GDAX219500B5.EX', 'GDAX219500N5.EX', 'GDAX219750B5.EX', 'GDAX219750N5.EX', 'GDAX220000B5.EX', 'GDAX220000N5.EX', 'GDAX220250B5.EX', 'GDAX220250N5.EX', 'GDAX220500B5.EX', 'GDAX220500N5.EX', 'GDAX220750B5.EX', 'GDAX220750N5.EX', 'GDAX221000B5.EX', 'GDAX221000N5.EX', 'GDAX221250B5.EX', 'GDAX221250N5.EX', 'GDAX221500B5.EX', 'GDAX221500N5.EX', 'GDAX221750B5.EX', 'GDAX221750N5.EX', 'GDAX222000B5.EX', 'GDAX222000N5.EX', 'GDAX222250B5.EX', 'GDAX222250N5.EX', 'GDAX222500B5.EX', 'GDAX222500N5.EX', 'GDAX222750B5.EX', 'GDAX222750N5.EX', 'GDAX223000B5.EX', 'GDAX223000N5.EX', 'GDAX223250B5.EX', 'GDAX223250N5.EX', 'GDAX223500B5.EX', 'GDAX223500N5.EX', 'GDAX223750B5.EX', 'GDAX223750N5.EX', 'GDAX224000B5.EX', 'GDAX224000N5.EX', 'GDAX224250B5.EX', 'GDAX224250N5.EX', 'GDAX224500B5.EX', 'GDAX224500N5.EX', 'GDAX224750B5.EX', 'GDAX224750N5.EX', 'GDAX225000B5.EX', 'GDAX225000N5.EX', 'GDAX225250B5.EX', 'GDAX225250N5.EX', 'GDAX225500B5.EX', 'GDAX225500N5.EX', 'GDAX225750B5.EX', 'GDAX225750N5.EX', 'GDAX226000B5.EX', 'GDAX226000N5.EX', 'GDAX226250B5.EX', 'GDAX226250N5.EX', 'GDAX226500B5.EX', 'GDAX226500N5.EX', 'GDAX226750B5.EX', 'GDAX226750N5.EX', 'GDAX227000B5.EX', 'GDAX227000N5.EX', 'GDAX227250B5.EX', 'GDAX227250N5.EX', 'GDAX227500B5.EX', 'GDAX227500N5.EX', 'GDAX227750B5.EX', 'GDAX227750N5.EX', 'GDAX228000B5.EX', 'GDAX228000N5.EX', 'GDAX228250B5.EX', 'GDAX228250N5.EX', 'GDAX228500B5.EX', 'GDAX228500N5.EX', 'GDAX228750B5.EX', 'GDAX228750N5.EX', 'GDAX229000B5.EX', 'GDAX229000N5.EX', 'GDAX229250B5.EX', 'GDAX229250N5.EX', 'GDAX229500B5.EX', 'GDAX229500N5.EX', 'GDAX229750B5.EX', 'GDAX229750N5.EX', 'GDAX230000B5.EX', 'GDAX230000N5.EX', 'GDAX230250B5.EX', 'GDAX230250N5.EX', 'GDAX230500B5.EX', 'GDAX230500N5.EX', 'GDAX230750B5.EX', 'GDAX230750N5.EX', 'GDAX231000B5.EX', 'GDAX231000N5.EX', 'GDAX231250B5.EX', 'GDAX231250N5.EX', 'GDAX231500B5.EX', 'GDAX231500N5.EX', 'GDAX231750B5.EX', 'GDAX231750N5.EX', 'GDAX232000B5.EX', 'GDAX232000N5.EX', 'GDAX232250B5.EX', 'GDAX232250N5.EX', 'GDAX232500B5.EX', 'GDAX232500N5.EX', 'GDAX232750B5.EX', 'GDAX232750N5.EX', 'GDAX233000B5.EX', 'GDAX233000N5.EX', 'GDAX233250B5.EX', 'GDAX233250N5.EX', 'GDAX233500B5.EX', 'GDAX233500N5.EX', 'GDAX233750B5.EX', 'GDAX233750N5.EX', 'GDAX234000B5.EX', 'GDAX234000N5.EX', 'GDAX234250B5.EX', 'GDAX234250N5.EX', 'GDAX234500B5.EX', 'GDAX234500N5.EX', 'GDAX234750B5.EX', 'GDAX234750N5.EX', 'GDAX235000B5.EX', 'GDAX235000N5.EX', 'GDAX235250B5.EX', 'GDAX235250N5.EX', 'GDAX235500B5.EX', 'GDAX235500N5.EX', 'GDAX235750B5.EX', 'GDAX235750N5.EX', 'GDAX236000B5.EX', 'GDAX236000N5.EX', 'GDAX236250B5.EX', 'GDAX236250N5.EX', 'GDAX236500B5.EX', 'GDAX236500N5.EX', 'GDAX236750B5.EX', 'GDAX236750N5.EX', 'GDAX237000B5.EX', 'GDAX237000N5.EX', 'GDAX237250B5.EX', 'GDAX237250N5.EX', 'GDAX237500B5.EX', 'GDAX237500N5.EX', 'GDAX237750B5.EX', 'GDAX237750N5.EX', 'GDAX238000B5.EX', 'GDAX238000N5.EX', 'GDAX238250B5.EX', 'GDAX238250N5.EX', 'GDAX238500B5.EX', 'GDAX238500N5.EX', 'GDAX238750B5.EX', 'GDAX238750N5.EX', 'GDAX239000B5.EX', 'GDAX239000N5.EX', 'GDAX239250B5.EX', 'GDAX239250N5.EX', 'GDAX239500B5.EX', 'GDAX239500N5.EX', 'GDAX239750B5.EX', 'GDAX239750N5.EX', 'GDAX240000B5.EX', 'GDAX240000N5.EX', 'GDAX240250B5.EX', 'GDAX240250N5.EX', 'GDAX240500B5.EX', 'GDAX240500N5.EX', 'GDAX240750B5.EX', 'GDAX240750N5.EX', 'GDAX241000B5.EX', 'GDAX241000N5.EX', 'GDAX241250B5.EX', 'GDAX241250N5.EX', 'GDAX241500B5.EX', 'GDAX241500N5.EX', 'GDAX241750B5.EX', 'GDAX241750N5.EX', 'GDAX242000B5.EX', 'GDAX242000N5.EX', 'GDAX242250B5.EX', 'GDAX242250N5.EX', 'GDAX242500B5.EX', 'GDAX242500N5.EX', 'GDAX242750B5.EX', 'GDAX242750N5.EX', 'GDAX243000B5.EX', 'GDAX243000N5.EX', 'GDAX243250B5.EX', 'GDAX243250N5.EX', 'GDAX243500B5.EX', 'GDAX243500N5.EX', 'GDAX244000B5.EX', 'GDAX244000N5.EX', 'GDAX246000B5.EX', 'GDAX246000N5.EX', 'GDAX248000B5.EX', 'GDAX248000N5.EX', 'GDAX86000C5.EX', 'GDAX86000O5.EX', 'GDAX88000C5.EX', 'GDAX88000O5.EX', 'GDAX90000C5.EX', 'GDAX90000O5.EX', 'GDAX92000C5.EX', 'GDAX92000O5.EX', 'GDAX94000C5.EX', 'GDAX94000O5.EX', 'GDAX96000C5.EX', 'GDAX96000O5.EX', 'GDAX98000C5.EX', 'GDAX98000O5.EX', 'GDAX100000C5.EX', 'GDAX100000O5.EX', 'GDAX102000C5.EX', 'GDAX102000O5.EX', 'GDAX104000C5.EX', 'GDAX104000O5.EX', 'GDAX106000C5.EX', 'GDAX106000O5.EX', 'GDAX108000C5.EX', 'GDAX108000O5.EX', 'GDAX110000C5.EX', 'GDAX110000O5.EX', 'GDAX112000C5.EX', 'GDAX112000O5.EX', 'GDAX114000C5.EX', 'GDAX114000O5.EX', 'GDAX116000C5.EX', 'GDAX116000O5.EX', 'GDAX118000C5.EX', 'GDAX118000O5.EX', 'GDAX120000C5.EX', 'GDAX120000O5.EX', 'GDAX122000C5.EX', 'GDAX122000O5.EX', 'GDAX124000C5.EX', 'GDAX124000O5.EX', 'GDAX126000C5.EX', 'GDAX126000O5.EX', 'GDAX128000C5.EX', 'GDAX128000O5.EX', 'GDAX130000C5.EX', 'GDAX130000O5.EX', 'GDAX132000C5.EX', 'GDAX132000O5.EX', 'GDAX134000C5.EX', 'GDAX134000O5.EX', 'GDAX136000C5.EX', 'GDAX136000O5.EX', 'GDAX138000C5.EX', 'GDAX138000O5.EX', 'GDAX140000C5.EX', 'GDAX140000O5.EX', 'GDAX142000C5.EX', 'GDAX142000O5.EX', 'GDAX144000C5.EX', 'GDAX144000O5.EX', 'GDAX146000C5.EX', 'GDAX146000O5.EX', 'GDAX148000C5.EX', 'GDAX148000O5.EX', 'GDAX150000C5.EX', 'GDAX150000O5.EX', 'GDAX152000C5.EX', 'GDAX152000O5.EX', 'GDAX154000C5.EX', 'GDAX154000O5.EX', 'GDAX156000C5.EX', 'GDAX156000O5.EX', 'GDAX157000C5.EX', 'GDAX157000O5.EX', 'GDAX158000C5.EX', 'GDAX158000O5.EX', 'GDAX159000C5.EX', 'GDAX159000O5.EX', 'GDAX160000C5.EX', 'GDAX160000O5.EX', 'GDAX161000C5.EX', 'GDAX161000O5.EX', 'GDAX162000C5.EX', 'GDAX162000O5.EX', 'GDAX163000C5.EX', 'GDAX163000O5.EX', 'GDAX164000C5.EX', 'GDAX164000O5.EX', 'GDAX165000C5.EX', 'GDAX165000O5.EX', 'GDAX166000C5.EX', 'GDAX166000O5.EX', 'GDAX167000C5.EX', 'GDAX167000O5.EX', 'GDAX168000C5.EX', 'GDAX168000O5.EX', 'GDAX169000C5.EX', 'GDAX169000O5.EX', 'GDAX170000C5.EX', 'GDAX170000O5.EX', 'GDAX171000C5.EX', 'GDAX171000O5.EX', 'GDAX172000C5.EX', 'GDAX172000O5.EX', 'GDAX173000C5.EX', 'GDAX173000O5.EX', 'GDAX174000C5.EX', 'GDAX174000O5.EX', 'GDAX175000C5.EX', 'GDAX175000O5.EX', 'GDAX176000C5.EX', 'GDAX176000O5.EX', 'GDAX177000C5.EX', 'GDAX177000O5.EX', 'GDAX178000C5.EX', 'GDAX178000O5.EX', 'GDAX179000C5.EX', 'GDAX179000O5.EX', 'GDAX180000C5.EX', 'GDAX180000O5.EX', 'GDAX181000C5.EX', 'GDAX181000O5.EX', 'GDAX182000C5.EX', 'GDAX182000O5.EX', 'GDAX183000C5.EX', 'GDAX183000O5.EX', 'GDAX184000C5.EX', 'GDAX184000O5.EX', 'GDAX185000C5.EX', 'GDAX185000O5.EX', 'GDAX186000C5.EX', 'GDAX186000O5.EX', 'GDAX186500C5.EX', 'GDAX186500O5.EX', 'GDAX187000C5.EX', 'GDAX187000O5.EX', 'GDAX187500C5.EX', 'GDAX187500O5.EX', 'GDAX188000C5.EX', 'GDAX188000O5.EX', 'GDAX188500C5.EX', 'GDAX188500O5.EX', 'GDAX189000C5.EX', 'GDAX189000O5.EX', 'GDAX189500C5.EX', 'GDAX189500O5.EX', 'GDAX190000C5.EX', 'GDAX190000O5.EX', 'GDAX190500C5.EX', 'GDAX190500O5.EX', 'GDAX191000C5.EX', 'GDAX191000O5.EX', 'GDAX191500C5.EX', 'GDAX191500O5.EX', 'GDAX192000C5.EX', 'GDAX192000O5.EX', 'GDAX192500C5.EX', 'GDAX192500O5.EX', 'GDAX193000C5.EX', 'GDAX193000O5.EX', 'GDAX193500C5.EX', 'GDAX193500O5.EX', 'GDAX194000C5.EX', 'GDAX194000O5.EX', 'GDAX194500C5.EX', 'GDAX194500O5.EX', 'GDAX195000C5.EX', 'GDAX195000O5.EX', 'GDAX195500C5.EX', 'GDAX195500O5.EX', 'GDAX196000C5.EX', 'GDAX196000O5.EX', 'GDAX196500C5.EX', 'GDAX196500O5.EX', 'GDAX197000C5.EX', 'GDAX197000O5.EX', 'GDAX197500C5.EX', 'GDAX197500O5.EX', 'GDAX198000C5.EX', 'GDAX198000O5.EX', 'GDAX198500C5.EX', 'GDAX198500O5.EX', 'GDAX199000C5.EX', 'GDAX199000O5.EX', 'GDAX199500C5.EX', 'GDAX199500O5.EX', 'GDAX200000C5.EX', 'GDAX200000O5.EX', 'GDAX200500C5.EX', 'GDAX200500O5.EX', 'GDAX201000C5.EX', 'GDAX201000O5.EX', 'GDAX201500C5.EX', 'GDAX201500O5.EX', 'GDAX202000C5.EX', 'GDAX202000O5.EX', 'GDAX202500C5.EX', 'GDAX202500O5.EX', 'GDAX203000C5.EX', 'GDAX203000O5.EX', 'GDAX203500C5.EX', 'GDAX203500O5.EX', 'GDAX204000C5.EX', 'GDAX204000O5.EX', 'GDAX204500C5.EX', 'GDAX204500O5.EX', 'GDAX205000C5.EX', 'GDAX205000O5.EX', 'GDAX205500C5.EX', 'GDAX205500O5.EX', 'GDAX206000C5.EX', 'GDAX206000O5.EX', 'GDAX206500C5.EX', 'GDAX206500O5.EX', 'GDAX207000C5.EX', 'GDAX207000O5.EX', 'GDAX207500C5.EX', 'GDAX207500O5.EX', 'GDAX208000C5.EX', 'GDAX208000O5.EX', 'GDAX208500C5.EX', 'GDAX208500O5.EX', 'GDAX209000C5.EX', 'GDAX209000O5.EX', 'GDAX209500C5.EX', 'GDAX209500O5.EX', 'GDAX210000C5.EX', 'GDAX210000O5.EX', 'GDAX210500C5.EX', 'GDAX210500O5.EX', 'GDAX211000C5.EX', 'GDAX211000O5.EX', 'GDAX211500C5.EX', 'GDAX211500O5.EX', 'GDAX212000C5.EX', 'GDAX212000O5.EX', 'GDAX212500C5.EX', 'GDAX212500O5.EX', 'GDAX213000C5.EX', 'GDAX213000O5.EX', 'GDAX213500C5.EX', 'GDAX213500O5.EX', 'GDAX214000C5.EX', 'GDAX214000O5.EX', 'GDAX214500C5.EX', 'GDAX214500O5.EX', 'GDAX215000C5.EX', 'GDAX215000O5.EX', 'GDAX215500C5.EX', 'GDAX215500O5.EX', 'GDAX216000C5.EX', 'GDAX216000O5.EX', 'GDAX216500C5.EX', 'GDAX216500O5.EX', 'GDAX217000C5.EX', 'GDAX217000O5.EX', 'GDAX217500C5.EX', 'GDAX217500O5.EX', 'GDAX218000C5.EX', 'GDAX218000O5.EX', 'GDAX218500C5.EX', 'GDAX218500O5.EX', 'GDAX219000C5.EX', 'GDAX219000O5.EX', 'GDAX219500C5.EX', 'GDAX219500O5.EX', 'GDAX220000C5.EX', 'GDAX220000O5.EX', 'GDAX220500C5.EX', 'GDAX220500O5.EX', 'GDAX221000C5.EX', 'GDAX221000O5.EX', 'GDAX221500C5.EX', 'GDAX221500O5.EX', 'GDAX222000C5.EX', 'GDAX222000O5.EX', 'GDAX222500C5.EX', 'GDAX222500O5.EX', 'GDAX223000C5.EX', 'GDAX223000O5.EX', 'GDAX223500C5.EX', 'GDAX223500O5.EX', 'GDAX224000C5.EX', 'GDAX224000O5.EX', 'GDAX224500C5.EX', 'GDAX224500O5.EX', 'GDAX225000C5.EX', 'GDAX225000O5.EX', 'GDAX225500C5.EX', 'GDAX225500O5.EX', 'GDAX226000C5.EX', 'GDAX226000O5.EX', 'GDAX226500C5.EX', 'GDAX226500O5.EX', 'GDAX227000C5.EX', 'GDAX227000O5.EX', 'GDAX227500C5.EX', 'GDAX227500O5.EX', 'GDAX228000C5.EX', 'GDAX228000O5.EX', 'GDAX228500C5.EX', 'GDAX228500O5.EX', 'GDAX229000C5.EX', 'GDAX229000O5.EX', 'GDAX229500C5.EX', 'GDAX229500O5.EX', 'GDAX230000C5.EX', 'GDAX230000O5.EX', 'GDAX230500C5.EX', 'GDAX230500O5.EX', 'GDAX231000C5.EX', 'GDAX231000O5.EX', 'GDAX231500C5.EX', 'GDAX231500O5.EX', 'GDAX232000C5.EX', 'GDAX232000O5.EX', 'GDAX232500C5.EX', 'GDAX232500O5.EX', 'GDAX233000C5.EX', 'GDAX233000O5.EX', 'GDAX233500C5.EX', 'GDAX233500O5.EX', 'GDAX234000C5.EX', 'GDAX234000O5.EX', 'GDAX234500C5.EX', 'GDAX234500O5.EX', 'GDAX235000C5.EX', 'GDAX235000O5.EX', 'GDAX235500C5.EX', 'GDAX235500O5.EX', 'GDAX236000C5.EX', 'GDAX236000O5.EX', 'GDAX236500C5.EX', 'GDAX236500O5.EX', 'GDAX237000C5.EX', 'GDAX237000O5.EX', 'GDAX237500C5.EX', 'GDAX237500O5.EX', 'GDAX238000C5.EX', 'GDAX238000O5.EX', 'GDAX238500C5.EX', 'GDAX238500O5.EX', 'GDAX239000C5.EX', 'GDAX239000O5.EX', 'GDAX239500C5.EX', 'GDAX239500O5.EX', 'GDAX240000C5.EX', 'GDAX240000O5.EX', 'GDAX240500C5.EX', 'GDAX240500O5.EX', 'GDAX241000C5.EX', 'GDAX241000O5.EX', 'GDAX160000D5.EX', 'GDAX160000P5.EX', 'GDAX161000D5.EX', 'GDAX161000P5.EX', 'GDAX162000D5.EX', 'GDAX162000P5.EX', 'GDAX163000D5.EX', 'GDAX163000P5.EX', 'GDAX164000D5.EX', 'GDAX164000P5.EX', 'GDAX165000D5.EX', 'GDAX165000P5.EX', 'GDAX166000D5.EX', 'GDAX166000P5.EX', 'GDAX167000D5.EX', 'GDAX167000P5.EX', 'GDAX168000D5.EX', 'GDAX168000P5.EX', 'GDAX169000D5.EX', 'GDAX169000P5.EX', 'GDAX170000D5.EX', 'GDAX170000P5.EX', 'GDAX171000D5.EX', 'GDAX171000P5.EX', 'GDAX172000D5.EX', 'GDAX172000P5.EX', 'GDAX173000D5.EX', 'GDAX173000P5.EX', 'GDAX174000D5.EX', 'GDAX174000P5.EX', 'GDAX175000D5.EX', 'GDAX175000P5.EX', 'GDAX176000D5.EX', 'GDAX176000P5.EX', 'GDAX177000D5.EX', 'GDAX177000P5.EX', 'GDAX178000D5.EX', 'GDAX178000P5.EX', 'GDAX179000D5.EX', 'GDAX179000P5.EX', 'GDAX180000D5.EX', 'GDAX180000P5.EX', 'GDAX181000D5.EX', 'GDAX181000P5.EX', 'GDAX182000D5.EX', 'GDAX182000P5.EX', 'GDAX183000D5.EX', 'GDAX183000P5.EX', 'GDAX184000D5.EX', 'GDAX184000P5.EX', 'GDAX185000D5.EX', 'GDAX185000P5.EX', 'GDAX186000D5.EX', 'GDAX186000P5.EX', 'GDAX187000D5.EX', 'GDAX187000P5.EX', 'GDAX188000D5.EX', 'GDAX188000P5.EX', 'GDAX189000D5.EX', 'GDAX189000P5.EX', 'GDAX190000D5.EX', 'GDAX190000P5.EX', 'GDAX191000D5.EX', 'GDAX191000P5.EX', 'GDAX192000D5.EX', 'GDAX192000P5.EX', 'GDAX193000D5.EX', 'GDAX193000P5.EX', 'GDAX194000D5.EX', 'GDAX194000P5.EX', 'GDAX195000D5.EX', 'GDAX195000P5.EX', 'GDAX196000D5.EX', 'GDAX196000P5.EX', 'GDAX196500D5.EX', 'GDAX196500P5.EX', 'GDAX197000D5.EX', 'GDAX197000P5.EX', 'GDAX197500D5.EX', 'GDAX197500P5.EX', 'GDAX198000D5.EX', 'GDAX198000P5.EX', 'GDAX198500D5.EX', 'GDAX198500P5.EX', 'GDAX199000D5.EX', 'GDAX199000P5.EX', 'GDAX199500D5.EX', 'GDAX199500P5.EX', 'GDAX200000D5.EX', 'GDAX200000P5.EX', 'GDAX200500D5.EX', 'GDAX200500P5.EX', 'GDAX201000D5.EX', 'GDAX201000P5.EX', 'GDAX201500D5.EX', 'GDAX201500P5.EX', 'GDAX202000D5.EX', 'GDAX202000P5.EX', 'GDAX202500D5.EX', 'GDAX202500P5.EX', 'GDAX203000D5.EX', 'GDAX203000P5.EX', 'GDAX203500D5.EX', 'GDAX203500P5.EX', 'GDAX204000D5.EX', 'GDAX204000P5.EX', 'GDAX204500D5.EX', 'GDAX204500P5.EX', 'GDAX205000D5.EX', 'GDAX205000P5.EX', 'GDAX205500D5.EX', 'GDAX205500P5.EX', 'GDAX206000D5.EX', 'GDAX206000P5.EX', 'GDAX206500D5.EX', 'GDAX206500P5.EX', 'GDAX207000D5.EX', 'GDAX207000P5.EX', 'GDAX207500D5.EX', 'GDAX207500P5.EX', 'GDAX208000D5.EX', 'GDAX208000P5.EX', 'GDAX208500D5.EX', 'GDAX208500P5.EX', 'GDAX209000D5.EX', 'GDAX209000P5.EX', 'GDAX209500D5.EX', 'GDAX209500P5.EX', 'GDAX210000D5.EX', 'GDAX210000P5.EX', 'GDAX210500D5.EX', 'GDAX210500P5.EX', 'GDAX211000D5.EX', 'GDAX211000P5.EX', 'GDAX211500D5.EX', 'GDAX211500P5.EX', 'GDAX212000D5.EX', 'GDAX212000P5.EX', 'GDAX212500D5.EX', 'GDAX212500P5.EX', 'GDAX213000D5.EX', 'GDAX213000P5.EX', 'GDAX213500D5.EX', 'GDAX213500P5.EX', 'GDAX214000D5.EX', 'GDAX214000P5.EX', 'GDAX214500D5.EX', 'GDAX214500P5.EX', 'GDAX215000D5.EX', 'GDAX215000P5.EX', 'GDAX215500D5.EX', 'GDAX215500P5.EX', 'GDAX216000D5.EX', 'GDAX216000P5.EX', 'GDAX216500D5.EX', 'GDAX216500P5.EX', 'GDAX217000D5.EX', 'GDAX217000P5.EX', 'GDAX217500D5.EX', 'GDAX217500P5.EX', 'GDAX218000D5.EX', 'GDAX218000P5.EX', 'GDAX218500D5.EX', 'GDAX218500P5.EX', 'GDAX219000D5.EX', 'GDAX219000P5.EX', 'GDAX219500D5.EX', 'GDAX219500P5.EX', 'GDAX220000D5.EX', 'GDAX220000P5.EX', 'GDAX220500D5.EX', 'GDAX220500P5.EX', 'GDAX221000D5.EX', 'GDAX221000P5.EX', 'GDAX221500D5.EX', 'GDAX221500P5.EX', 'GDAX222000D5.EX', 'GDAX222000P5.EX', 'GDAX222500D5.EX', 'GDAX222500P5.EX', 'GDAX223000D5.EX', 'GDAX223000P5.EX', 'GDAX223500D5.EX', 'GDAX223500P5.EX', 'GDAX224000D5.EX', 'GDAX224000P5.EX', 'GDAX224500D5.EX', 'GDAX224500P5.EX', 'GDAX225000D5.EX', 'GDAX225000P5.EX', 'GDAX225500D5.EX', 'GDAX225500P5.EX', 'GDAX226000D5.EX', 'GDAX226000P5.EX', 'GDAX226500D5.EX', 'GDAX226500P5.EX', 'GDAX227000D5.EX', 'GDAX227000P5.EX', 'GDAX227500D5.EX', 'GDAX227500P5.EX', 'GDAX228000D5.EX', 'GDAX228000P5.EX', 'GDAX228500D5.EX', 'GDAX228500P5.EX', 'GDAX229000D5.EX', 'GDAX229000P5.EX', 'GDAX229500D5.EX', 'GDAX229500P5.EX', 'GDAX230000D5.EX', 'GDAX230000P5.EX', 'GDAX230500D5.EX', 'GDAX230500P5.EX', 'GDAX231000D5.EX', 'GDAX231000P5.EX', 'GDAX231500D5.EX', 'GDAX231500P5.EX', 'GDAX232000D5.EX', 'GDAX232000P5.EX', 'GDAX232500D5.EX', 'GDAX232500P5.EX', 'GDAX233000D5.EX', 'GDAX233000P5.EX', 'GDAX233500D5.EX', 'GDAX2

In [9]:
dax = ld.get_data(optns4AllMatur4DAX, ['TR.InstrumentDescription', 'PUTCALLIND', 'STRIKE_PRC', 'CF_CLOSE', 'IMP_VOLT', 'EXPIR_DATE'])
dax.head()

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\lseg\data\_tools\_dataframe.py:177:FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

,Instrument,Instrument Description,PUTCALLIND,STRIKE_PRC,CF_CLOSE,IMP_VOLT,EXPIR_DATE
0,GDAX145000B5.EX,Eurex DAX Monthly Index Option 14500 Call Feb ...,CALL,14500,8375.0,218.7894,2025-02-21
1,GDAX145000N5.EX,Eurex DAX Monthly Index Option 14500 Put Feb 2025,PUT,14500,0.1,127.6744,2025-02-21
2,GDAX146000B5.EX,Eurex DAX Monthly Index Option 14600 Call Feb ...,CALL,14600,8275.0,215.824,2025-02-21
3,GDAX146000N5.EX,Eurex DAX Monthly Index Option 14600 Put Feb 2025,PUT,14600,0.1,125.8407,2025-02-21
4,GDAX147000B5.EX,Eurex DAX Monthly Index Option 14700 Call Feb ...,CALL,14700,8175.0,212.877,2025-02-21

In [10]:
sepDax = dax[dax['Instrument Description'].str.contains('Sep 2025', na=False)] # Focus on one month

In [11]:
sepPuts = sepDax[sepDax['PUTCALLIND'] == 'PUT ']
sepCalls = dax[dax['PUTCALLIND'] == 'CALL']
display(sepPuts.head())
display(sepCalls.head())

,Instrument,Instrument Description,PUTCALLIND,STRIKE_PRC,CF_CLOSE,IMP_VOLT,EXPIR_DATE
1335,GDAX106000U5.EX,Eurex DAX Monthly Index Option 10600 Put Sep 2025,PUT,10600,18.0,44.1577,2025-09-19
1337,GDAX108000U5.EX,Eurex DAX Monthly Index Option 10800 Put Sep 2025,PUT,10800,19.1,43.5145,2025-09-19
1339,GDAX110000U5.EX,Eurex DAX Monthly Index Option 11000 Put Sep 2025,PUT,11000,20.3,42.8914,2025-09-19
1341,GDAX112000U5.EX,Eurex DAX Monthly Index Option 11200 Put Sep 2025,PUT,11200,21.5,42.2588,2025-09-19
1343,GDAX114000U5.EX,Eurex DAX Monthly Index Option 11400 Put Sep 2025,PUT,11400,22.8,41.6435,2025-09-19

,Instrument,Instrument Description,PUTCALLIND,STRIKE_PRC,CF_CLOSE,IMP_VOLT,EXPIR_DATE
0,GDAX145000B5.EX,Eurex DAX Monthly Index Option 14500 Call Feb ...,CALL,14500,8375.0,218.7894,2025-02-21
2,GDAX146000B5.EX,Eurex DAX Monthly Index Option 14600 Call Feb ...,CALL,14600,8275.0,215.824,2025-02-21
4,GDAX147000B5.EX,Eurex DAX Monthly Index Option 14700 Call Feb ...,CALL,14700,8175.0,212.877,2025-02-21
6,GDAX148000B5.EX,Eurex DAX Monthly Index Option 14800 Call Feb ...,CALL,14800,8075.1,210.0666,2025-02-21
8,GDAX149000B5.EX,Eurex DAX Monthly Index Option 14900 Call Feb ...,CALL,14900,7975.1,207.154,2025-02-21

In [12]:
optns4AllMatur4DAX.summary_links

['.GDAXI']

In [13]:
daxStrkPr = ld.get_data(optns4AllMatur4DAX.summary_links, ['CF_CLOSE'])
daxStrkPr

  Instrument  CF_CLOSE
0     .GDAXI   22844.5

In [14]:
print(f"Current strike price for GDAXI is {daxStrkPr['CF_CLOSE'].values[0]}")

Current strike price for GDAXI is 22844.5

In [15]:
limit = 2000
sepPutsCloseToTheMoney = sepPuts[abs(sepPuts['STRIKE_PRC'] - daxStrkPr['CF_CLOSE'].values[0]) < limit]
sepPutsCloseToTheMoney.head()

,Instrument,Instrument Description,PUTCALLIND,STRIKE_PRC,CF_CLOSE,IMP_VOLT,EXPIR_DATE
1481,GDAX209000U5.EX,Eurex DAX Monthly Index Option 20900 Put Sep 2025,PUT,20900,378.8,17.7825,2025-09-19
1483,GDAX210000U5.EX,Eurex DAX Monthly Index Option 21000 Put Sep 2025,PUT,21000,393.5,17.5875,2025-09-19
1485,GDAX211000U5.EX,Eurex DAX Monthly Index Option 21100 Put Sep 2025,PUT,21100,408.9,17.3941,2025-09-19
1487,GDAX212000U5.EX,Eurex DAX Monthly Index Option 21200 Put Sep 2025,PUT,21200,425.1,17.2037,2025-09-19
1489,GDAX213000U5.EX,Eurex DAX Monthly Index Option 21300 Put Sep 2025,PUT,21300,442.0,17.0137,2025-09-19

In [16]:
sepPutsCloseToTheMoney.set_index('STRIKE_PRC').head()

,Instrument,Instrument Description,PUTCALLIND,CF_CLOSE,IMP_VOLT,EXPIR_DATE
STRIKE_PRC,,,,,,
20900,GDAX209000U5.EX,Eurex DAX Monthly Index Option 20900 Put Sep 2025,PUT,378.8,17.7825,2025-09-19
21000,GDAX210000U5.EX,Eurex DAX Monthly Index Option 21000 Put Sep 2025,PUT,393.5,17.5875,2025-09-19
21100,GDAX211000U5.EX,Eurex DAX Monthly Index Option 21100 Put Sep 2025,PUT,408.9,17.3941,2025-09-19
21200,GDAX212000U5.EX,Eurex DAX Monthly Index Option 21200 Put Sep 2025,PUT,425.1,17.2037,2025-09-19
21300,GDAX213000U5.EX,Eurex DAX Monthly Index Option 21300 Put Sep 2025,PUT,442.0,17.0137,2025-09-19

In [17]:
import cufflinks
import pandas as pd

sepPutsCleaned = sepPutsCloseToTheMoney.replace('', pd.NA).dropna()
sepPutsCleaned.set_index('STRIKE_PRC')[["CF_CLOSE", "IMP_VOLT"]].iplot(
    subplots=True,
    mode='lines+markers',
    symbol='x',
    size=6,
    title='Eurex DAX Monthly Index Option (close to the money) Put Sep 2025',
    xTitle='Strike price',
    yTitle='Price',
    secondary_y='IMP_VOLT'
)

In [18]:
puts = dax[dax['PUTCALLIND'] == 'PUT ']
puts_close, puts_vols = pd.DataFrame(), pd.DataFrame()
for expiry in dax['EXPIR_DATE']:
    sub_set = puts[puts['EXPIR_DATE'] == expiry]
    puts_close[expiry] = sub_set.set_index('STRIKE_PRC')['CF_CLOSE']
    puts_vols[expiry] = sub_set.set_index('STRIKE_PRC')['IMP_VOLT']

puts_close.replace('', pd.NA).dropna().iplot(
    mode='markers',
    size=6,
    xTitle='strike price')

In [19]:
puts_vols.replace('', pd.NA).dropna().iplot(
    mode='markers',
    size=6,
    xTitle='strike price')

In [20]:
calls = dax[dax['PUTCALLIND'] == 'CALL']
calls_close, calls_vols = pd.DataFrame(), pd.DataFrame()
for expiry in dax['EXPIR_DATE']:
    sub_set = calls[calls['EXPIR_DATE'] == expiry]
    calls_close[expiry] = sub_set.set_index('STRIKE_PRC')['CF_CLOSE']
    calls_vols[expiry] = sub_set.set_index('STRIKE_PRC')['IMP_VOLT']

calls_close.replace('', pd.NA).dropna().iplot(
    mode='markers',
    size=6,
    xTitle='strike price')

In [21]:
calls_vols.replace('', pd.NA).dropna().iplot(
    mode='markers',
    size=6,
    xTitle='strike price')

#### summary_links

All chains contains preliminary links before constituents. Usually, it's related indexes. TLSEG names it the "summary links":

In [22]:
fchi.summary_links

['.DJI', 'EUR=', '/.STOXX50E', '.FCHI', '.AD.FCHI']

In [23]:
print(f"0#{fchi.summary_links[0]}")
ld.get_data(f"0#{fchi.summary_links[0]}", ['BID', 'ASK', 'TR.Revenue'])

0#.DJI

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\lseg\data\_tools\_dataframe.py:192: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\dtypes\cast.py:1056: RuntimeWarning:

invalid value encountered in cast

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\dtypes\cast.py:1080: RuntimeWarning:

invalid value encountered in cast

   Instrument       Revenue     BID     ASK
0        GS.N  126853000000     0.0     0.0
1       NKE.N   51362000000     0.0     0.0
2     CSCO.OQ   53803000000   64.59   64.94
3       JPM.N          <NA>     0.0     0.0
4       DIS.N   91361000000     0.0     0.0
5       MRK.N   64168000000     0.0     0.0
6       CVX.N  193414000000     0.0     0.0
7       AXP.N   71644000000     0.0     0.0
8       SHW.N   23098500000     0.0     0.0
9        VZ.N  134788000000     0.0     0.0
10       HD.N  152669000000     0.0     0.0
11      MCD.N   25920000000     0.0     0.0
12      UNH.N          <NA>     0.0     0.0
13    AMZN.OQ  637959000000   226.0  226.65
14       KO.N   47061000000     0.0     0.0
15      JNJ.N   88821000000     0.0     0.0
16    MSFT.OQ  245122000000  409.13  409.97
17     HON.OQ   38498000000  208.25  209.99
18      CRM.N   34857000000     0.0     0.0
19       PG.N   84039000000     0.0     0.0
20      IBM.N   62753000000     0.0     0.0
21    NVDA.OQ   60922000000  139.03   139.1
22      MMM.N   24575000000     0.0     0.0
23    AAPL.OQ  391035000000  244.75  245.47
24      WMT.N  648125000000     0.0     0.0
25      CAT.N   64809000000     0.0     0.0
26    AMGN.OQ   33424000000   285.0  294.47
27        V.N   35926000000     0.0     0.0
28      TRV.N          <NA>     0.0     0.0
29       BA.N   66517000000     0.0     0.0

In [24]:
ld.close_session()

#### Use the chain with pricing streams

In [25]:
# import lseg.data as ld
# import datetime
# import time
# from IPython.display import display, clear_output
# session = ld.open_session()
# if session is not None:
#     fchi = ld.discovery.Chain("0#.FCHI")
#     def display_data(data, instrument, stream):
#         clear_output(wait=True)
#         current_time = datetime.datetime.now().time()
#         print(current_time, "- Data received for", instrument)
#         display(data)
#         time.sleep(0.5)
#     stream = ld.open_pricing_stream(fchi, ['BID', 'ASK'], on_data=display_data)
# else:
#     print("Can't open a session !")

In [26]:
# stream.close()
# ld.close_session()

#### N.B.: Building Historical Index Constituents
The next topic that natuirally comes to mind here Historical Index Constituents. We now need to call upon [Dr.Aramyan's article](https://developers.lseg.com/en/article-catalog/article/building-historical-index-constituents) to build a functioan that Building historical index constituents

In [27]:
ld.open_session()

ric = '.FTSE'
start = '2014-01-01'
end = '2024-02-15'

In [28]:
def get_constituents_as_of(ric, date):
    initial_constituents = ld.get_data(
        universe=[f"0#{ric}({date.replace('-', '')})"],
        fields=["TR.PriceClose"],
        parameters={"SDATE":f"{date}", "EDATE":f"{date}"})
    initial_constituents = initial_constituents['Instrument'].to_list()
    return initial_constituents
initial_constituents = get_constituents_as_of(ric, start)
print(initial_constituents, len(initial_constituents))

['ABF.L', 'SAB.L^J16', 'ABDN.L', 'ADN.L^H17', 'ADML.L', 'AGGK.L^H21', 'AMFW.L^J17', 'AAL.L', 'ANTO.L', 'AHT.L', 'AZN.L', 'AV.L', 'BAB.L', 'BAES.L', 'BARC.L', 'RRS.L^A19', 'BG.L^B16', 'BHPB.L^A22', 'BP.L', 'BATS.L', 'BLND.L', 'BT.L', 'BNZL.L', 'BRBY.L', 'CPI.L', 'CCL.L', 'CNA.L', 'CCH.L', 'CPG.L', 'CRH.L', 'DGE.L', 'EZJ.L', 'EXPN.L', 'FERG.L', 'FRAS.L', 'FRES.L', 'FLG.L^D15', 'GFS.L^E21', 'GKN.L^E18', 'GLEN.L', 'GSK.L', 'HMSO.L', 'HRGV.L', 'HSBA.L', 'ICAG.L', 'IMI.L', 'IMB.L', 'IHG.L', 'ITRK.L', 'IDSI.L', 'ITV.L', 'JMAT.L', 'KGF.L', 'LAND.L', 'LGEN.L', 'LLOY.L', 'LSEG.L', 'MKS.L', 'MGGT.L^I22', 'MRON.L', 'MNDI.L', 'NG.L', 'NWG.L', 'NXT.L', 'OMU.L', 'PSON.L', 'PSN.L', 'PFC.L', 'PRU.L', 'RKT.L', 'REL.L', 'REX.L^G16', 'RIO.L', 'RR.L', 'RSA.L^F21', 'SGE.L', 'SBRY.L', 'SDR.L', 'SVT.L', 'SHEL.L', 'RDSb.L^A22', 'SHP.L^A19', 'SKYB.L^K18', 'SN.L', 'SMIN.L', 'SSE.L', 'STAN.L', 'ARM.L^I16', 'TATE.L', 'TSCO.L', 'TPK.L', 'TT.L^L14', 'TLW.L', 'ULVR.L', 'UU.L', 'VOD.L', 'WEIR.L', 'WTB.L', 'WMH.L^D21', 'MRW.L^J21', 'WPP.L'] 101

In [29]:
def get_constituent_changes(ric, start, end):
    return ld.get_data(
        universe=[ric],
        fields = [
            "TR.IndexJLConstituentRIC.date", "TR.IndexJLConstituentRIC",
            "TR.IndexJLConstituentName", "TR.IndexJLConstituentRIC.change"],
        parameters={"SDATE":f"{start}","EDATE":f"{end}", 'IC':'B'})
constituent_changes = get_constituent_changes(ric, start, end)
constituent_changes

    Instrument       Date Constituent RIC  Constituent Name  Change
0        .FTSE 2014-03-24           SJP.L  St James's Place  Joiner
1        .FTSE 2014-03-24          BTRW.L    Barratt Redrow  Joiner
2        .FTSE 2014-03-24      AMFW.L^J17       Amec Foster  Leaver
3        .FTSE 2014-03-24          TATE.L       Tate & Lyle  Leaver
4        .FTSE 2014-06-23           III.L          3i Group  Joiner
..         ...        ...             ...               ...     ...
210      .FTSE 2023-09-25          HWDN.L    Howden Joinery  Joiner
211      .FTSE 2023-12-18         ICGIN.L  Intermediate Cap  Joiner
212      .FTSE 2023-12-18          HRGV.L        Hargreaves  Leaver
213      .FTSE 2024-01-16       DPH.L^A24     Dechra Pharms  Leaver
214      .FTSE 2024-01-16           PSN.L         Persimmon  Joiner

[215 rows x 5 columns]

In [30]:
import copy
import pandas as pd

def add_joiner(init_list, joiner_list):
    for joiner in joiner_list:
        if joiner not in init_list:
            init_list.append(joiner)
        else:
            print(f'{joiner} joiner is already in the list')
    return init_list

def remove_leaver(init_list, leaver_list):
    for leaver in leaver_list:
        if leaver in init_list:
            init_list.remove(leaver)
        else:
            print(f'{leaver} leaver is not in the list')
    return init_list

def update_constituents(start, constituents, constitent_changes):
    hist_constituents = pd.DataFrame([(start, ric) for ric in constituents], columns=['Date', 'RIC'])
    for date in constitent_changes['Date'].unique():
        const_changes_date = constitent_changes[constitent_changes['Date'] == date]
        joiners = const_changes_date[const_changes_date['Change']=='Joiner']['Constituent RIC'].to_list()
        leavers = const_changes_date[const_changes_date['Change']=='Leaver']['Constituent RIC'].to_list()
        joiners_unique = list(set(joiners) - set(leavers))
        leavers_unique = list(set(leavers) - set(joiners))
        if len(joiners_unique) > 0:
            constituents = add_joiner(constituents, joiners_unique)
        if len(leavers_unique) > 0:
            constituents = remove_leaver(constituents, leavers_unique)
        new_constituents = copy.deepcopy(constituents)
        new_constituents_df =  pd.DataFrame([(str(date)[:10], ric) for ric in new_constituents], columns=['Date', 'RIC'])
        hist_constituents = pd.concat([hist_constituents, new_constituents_df])
    hist_constituents = hist_constituents.reset_index(drop = True)
    
    return hist_constituents

historical_constituents = update_constituents(start, initial_constituents, constituent_changes)
historical_constituents

            Date        RIC
0     2014-01-01      ABF.L
1     2014-01-01  SAB.L^J16
2     2014-01-01     ABDN.L
3     2014-01-01  ADN.L^H17
4     2014-01-01     ADML.L
...          ...        ...
7560  2024-01-16     DPLM.L
7561  2024-01-16      MKS.L
7562  2024-01-16     HWDN.L
7563  2024-01-16    ICGIN.L
7564  2024-01-16      PSN.L

[7565 rows x 2 columns]

In [31]:
def get_historical_constituents(index, start, end):
    initial_constituents = get_constituents_as_of(index, start)
    constitent_changes = get_constituent_changes(index, start, end)
    historical_constituents = update_constituents(start, initial_constituents, constitent_changes)
    return historical_constituents
ftse_constituents = get_historical_constituents('.FTSE', '2014-01-01', '2024-03-14')
ftse_constituents

            Date        RIC
0     2014-01-01      ABF.L
1     2014-01-01  SAB.L^J16
2     2014-01-01     ABDN.L
3     2014-01-01  ADN.L^H17
4     2014-01-01     ADML.L
...          ...        ...
7560  2024-01-16     DPLM.L
7561  2024-01-16      MKS.L
7562  2024-01-16     HWDN.L
7563  2024-01-16    ICGIN.L
7564  2024-01-16      PSN.L

[7565 rows x 2 columns]

In [32]:
dict_of_ftse_constituents = {i: ftse_constituents[ftse_constituents['Date'] == i] for i in ftse_constituents['Date'].unique()}

In [33]:
dict_of_ftse_constituents['2014-01-01']

           Date        RIC
0    2014-01-01      ABF.L
1    2014-01-01  SAB.L^J16
2    2014-01-01     ABDN.L
3    2014-01-01  ADN.L^H17
4    2014-01-01     ADML.L
..          ...        ...
96   2014-01-01     WEIR.L
97   2014-01-01      WTB.L
98   2014-01-01  WMH.L^D21
99   2014-01-01  MRW.L^J21
100  2014-01-01      WPP.L

[101 rows x 2 columns]

In [34]:
dict_of_ftse_constituents['2014-03-24']

           Date        RIC
101  2014-03-24      ABF.L
102  2014-03-24  SAB.L^J16
103  2014-03-24     ABDN.L
104  2014-03-24  ADN.L^H17
105  2014-03-24     ADML.L
..          ...        ...
197  2014-03-24  WMH.L^D21
198  2014-03-24  MRW.L^J21
199  2014-03-24      WPP.L
200  2014-03-24      SJP.L
201  2014-03-24     BTRW.L

[101 rows x 2 columns]

#### Show sectoral distribution over time

In [35]:
sectors = ld.get_data(
    list(ftse_constituents['RIC'].unique()),
    ["TR.TRBCIndustryGroup", "TR.RIC"])
sectors

    Instrument                          TRBC Industry Group Name        RIC
0        ABF.L                                    Food & Tobacco      ABF.L
1    SAB.L^J16                                         Beverages  SAB.L^J16
2       ABDN.L          Investment Banking & Investment Services     ABDN.L
3    ADN.L^H17          Investment Banking & Investment Services  ADN.L^H17
4       ADML.L                                         Insurance     ADML.L
..         ...                                               ...        ...
163      HLN.L                                   Pharmaceuticals      HLN.L
164     FCIT.L                            Collective Investments     FCIT.L
165     BEZG.L                                         Insurance     BEZG.L
166      DWL.L                          Automobiles & Auto Parts      DWL.L
167     DPLM.L  Machinery, Tools, Heavy Vehicles, Trains & Ships     DPLM.L

[168 rows x 3 columns]

In [36]:
sector_df = ftse_constituents.merge(sectors, on = 'RIC')
sector_df_grouped = sector_df.groupby(by = ["Date", "TRBC Industry Group Name"]).count()
sector_df_grouped = sector_df_grouped.reset_index()
sector_df_grouped

            Date          TRBC Industry Group Name  RIC  Instrument
0     2014-01-01               Aerospace & Defense    5           5
1     2014-01-01          Automobiles & Auto Parts    1           1
2     2014-01-01                  Banking Services    5           5
3     2014-01-01                         Beverages    3           3
4     2014-01-01  Biotechnology & Medical Research    1           1
...          ...                               ...  ...         ...
2510  2024-01-16    Residential & Commercial REITs    3           3
2511  2024-01-16            Software & IT Services    4           4
2512  2024-01-16               Specialty Retailers    5           5
2513  2024-01-16       Telecommunications Services    3           3
2514  2024-01-16         Water & Related Utilities    2           2

[2515 rows x 4 columns]

In [37]:
import plotly.express as px

_sectors = [
    "Software & IT Services", "Banking Services", "Telecommunications Services",
    "Automobiles & Auto Parts", "Aerospace & Defense"]
fig = px.bar(
    sector_df_grouped[sector_df_grouped['TRBC Industry Group Name'].isin(_sectors)],
    x="Date",
    y="Instrument",
    color="TRBC Industry Group Name",
    width=1000,
    height=400)
 
fig.update_layout(
    xaxis=dict(
        type='category',
        categoryorder='array'))
fig.show()

In [38]:
ld.close_session()

## Platform Session

Platform sessions allow us to use the LD Lib. without the Workspace Desktop App open. It was created for servers, and it is still aimed for data hungry users who require little human interation with the code at hand (e.g.: overnight data retraival). With that said, usecases have grown in breadth and complexity thoughout the years, and people may want such 'ping' services (i.e.: the ability to 'ping', to directly contact, the services that deliver data/calculations, without going through the Desktop App Proxy).

Platform session use-cases are a little more complicated to the Desktop session ones. We can authenticate ourselves with the Workspace Desktop App open with simply just the Python line:

In [3]:
import datetime
import lseg.data as ld
ld.open_session(
    config_name="C:/Example.DataLibrary.Python-main/Configuration/lseg-data.config.json",
    name="platform.ldp")

In [4]:
df = ld.get_data(
    universe=['JPY='],
    fields=['BID','ASK'])
df.index = [datetime.datetime.now().time()]
df.index.name = 'Time'
df

                Instrument     BID     ASK
Time
08:43:10.916671       JPY=  151.71  151.72

[Error 400] - {'error': 'invalid_grant'}

In [ ]:
import datetime
import time
from IPython.display import display, clear_output

fchi = ld.discovery.Chain("0#.FCHI")
def display_data(data, instrument, stream):
    clear_output(wait=True)
    current_time = datetime.datetime.now().time()
    print(current_time, "- Data received for", instrument)
    display(data)
    time.sleep(0.5)
stream = ld.open_pricing_stream(fchi, ['BID', 'ASK'], on_data=display_data)

08:42:18.185923 - Data received for SGEF.PA

          BID   ASK
SGEF.PA  None  None

In [ ]:
stream.close()
ld.close_session()