<div style="display: flex; align-items: center;">
    <img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="20%" style="vertical-align: top;">
    <h1 style="margin-left: 20px;">LD Lib. Python Tutorial 9 - Screeners</h1>
</div>

## Screeners

We spoke at length about the LSEG Data Model. Let's not repeat ourselves, and instead forcuss on the task at hand: Screeners.

Screeners are best exemplified in Chavalit & Raksina's article "[Find Your Right Companies with SCREENER | the Data Library (Python)](https://developers.lseg.com/en/article-catalog/article/find-your-right-companies-with-screener-eikon-data-apis-python)"

## Install & Import the LSEG Data (and other) Libraries

To install libraries in python, you can find the command in PyPl with `pip install lseg.data`, in this instance, it is:

In [25]:
import lseg.data as ld
import pandas as pd
from IPython.display import display, clear_output

There are two sessions you can use to authenticate yourself to the LSEG Data Platform, the Desktop Session and Platform Session.

The Desktop Session allows you to access data in LSEG's Data Platform via the Desktop Workspace Application on the machine where you are running your code, meaning taht you need to have Workspace running on the machine where you are running your Python code. This is because this session funnels requests made to LSEG's servers through the desktop application. When using the Desktop Session, you need very little information, because you already inputed your username and password in the desktop application to logg in.

The Platform Session allows you to authenticate yourself to LSEG's Data Platform without the Desktop Application. This does, however, mean that you have to entre your credentials (e.g.: in a [reference configuration file](https://developers.lseg.com/en/api-catalog/lseg-data-platform/lseg-data-library-for-python/tutorials#tutorial-3-sessions-configurations-data-model-and-get-data)).

Let's start  with the Desktop Session:

## Access Layer

### Desktop Session

Desktop session use-cases are the simples ones, so let's start there. We can authenticate ourselves with the Workspace Desktop App open with simply just the Python line:

In [26]:
ld.open_session()

In [ ]:
# =@TR("SCREEN(U(IN(Equity(active,public,primary))/*UNV:Public*/), IN(TR.HQCountryCode,""TH""), IN(TR.TRBCBusinessSectorCode,""5020""), CURN=USD)","TR.CommonName;TR.HeadquartersCountry;TR.TRBCBusinessSector","curn=USD RH=In CH=Fd")

In [ ]:
excel_screen "SCREEN(U(IN(Equity(active,public,primary))/*UNV:Public*/), IN(TR.HQCountryCode,""TH""), IN(TR.TRBCBusinessSectorCode,""5020""), CURN=USD)",
excel_output "TR.CommonName;TR.HeadquartersCountry;TR.TRBCBusinessSector",
excel_format = "curn=USD RH=In CH=Fd"

In [43]:
screen_p1 = "U(IN(Equity(active,public,primary))/*UNV:Public*/), "
screen_p2 = "IN(TR.HQCountryCode,'TH'), "
screen_p3 = "IN(TR.TRBCBusinessSectorCode,'5020'), "
screen_p4 = "CURN=USD"
screen = screen_p1 + screen_p2 + screen_p3 + screen_p4
screen

"U(IN(Equity(active,public,primary))/*UNV:Public*/), IN(TR.HQCountryCode,'TH'), IN(TR.TRBCBusinessSectorCode,'5020'), CURN=USD"

In [44]:
ld.get_data(
    universe=ld.discovery.Screener(screen),
    fields=['TR.CommonName','TR.CompanyMarketCap(Scale=6)','TR.ExchangeName',
            'TR.TRBCBusinessSector','TR.TotalReturn3Mo'])

,Instrument,Company Common Name,Company Market Cap,Exchange Name,TRBC Business Sector Name,3 Month Total Return
0,AI.BK,Asian Insulators PCL,2463.996554,STOCK EXCHANGE OF THAILAND,Renewable Energy,3.103127
1,SOLAR.BK,Solartron PCL,313.708979,STOCK EXCHANGE OF THAILAND,Renewable Energy,-48.888889
2,TAE.BK,Thai Agro Energy PCL,660.0,STOCK EXCHANGE OF THAILAND,Renewable Energy,-25.0
3,AIE.BK,AI Energy PCL,1937.619613,STOCK EXCHANGE OF THAILAND,Renewable Energy,53.683036
4,GGC.BK,Global Green Chemicals PCL,4278.926806,STOCK EXCHANGE OF THAILAND,Renewable Energy,-9.137555
5,BBGI.BK,BBGI PCL,5292.36,STOCK EXCHANGE OF THAILAND,Renewable Energy,-5.635962

In [6]:
rics = ld.discovery.Screener(
    'U(IN(Equity(active,public,primary))/*UNV:Public*/), ' +
    'TR.CompanyMarketCap(Scale=6)>=5000, IN(TR.ExchangeMarketIdCode,"XNYS"), ' +
    'IN(TR.TRBCBusinessSectorCode,"5010","5020","5030"), TR.TotalReturn3Mo>=15, ' +
    'CURN=USD')

df = ld.get_data(
    universe=rics,
    fields=['TR.CommonName','TR.CompanyMarketCap(Scale=6)','TR.ExchangeName',
            'TR.TRBCBusinessSector','TR.TotalReturn3Mo'])
 
display(df)

,Instrument,Company Common Name,Company Market Cap,Exchange Name,TRBC Business Sector Name,3 Month Total Return
0,EQT.N,EQT Corp,30863.80206,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,17.220116
1,CTRA.N,Coterra Energy Inc,21518.505592,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,15.790605
2,CRK.N,Comstock Resources Inc,5518.59413,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,17.091361
3,CQP.N,Cheniere Energy Partners LP,31100.091903,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,18.865574
4,MPLX.N,MPLX LP,55880.159532,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,16.701848
5,AR.N,Antero Resources Corp,12104.902,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,23.140234
6,HESM.N,Hess Midstream LP,9846.707853,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,21.859507
7,AM.N,Antero Midstream Corp,8342.10258,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,19.624026
8,LB.N,LandBridge Co LLC,5631.203655,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,28.089849

#### M&A League Tables

One of the great things about the CODEBOOK app is that you can reuse the screen criteria from the Screener APP. In this example we screened for M&A Deals YTD globally

In [7]:
# use SCREENER to produce list of deals meeting League Table criteria
lt_screen = "SCREEN(U(IN(DEALS)/*UNV:DEALSMNA*/),  relativedate(TR.MnARankDate,LY)/*dt:Date*/, \
            TR.MnAIsEligForStdRanking==true,TR.MnAHasDebtTender = false,TR.MnAHasLoanModify = false, \
            TR.MnAIsExchangeOffer = false,TR.MnAIsOPMAndExclFromRanking = false,TR.MnAIsEquityCarveout = false, CURN=USD)"
# define list of fields and then using get_data from Eikon Data API create a dataframe with the screen and fields
lt_fields = [
    'TR.MnALeagueAdvisor(DealMnALTType=FINADV, DealMnAIsParent=true,LTAllocType=BF, ExclIneligible=true)',
    'TR.MnARankValueIncNetDebt(Scale=6,Curn=USD)']
# Send data request and package responce
lt = ld.get_data(lt_screen,lt_fields)
lt

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\lseg\data\_tools\_dataframe.py:192:FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

         Instrument M&A League Advisor  Rank Value inc. Net Debt of Target
0       34391439583               None                                <NA>
1       34391690018               None                             0.03231
2       34391802838               None                            2.933985
3       34391837686               None                                <NA>
4       34392665429               None                           65.005926
...             ...                ...                                 ...
69950  154088835685               None                                <NA>
69951  154088835720               None                                <NA>
69952  154088835796               None                           24.994779
69953  154088836097     No Information                                <NA>
69954  154088836097                GCG                                <NA>

[69955 rows x 3 columns]

Quick Tip: If you need help defining your field selection use CODECREATOR to simply create the lines of code you need and click on 'Open in CODEBOOK'.

In [8]:
# refine dataframe to meet specific criteria for analysis. 
lt2 = lt[lt['M&A League Advisor'] != 'None'] #creates a new table removing results showing None
lt3 = lt2[lt2['M&A League Advisor'] != 'No Information'] #takes that table and removes results showing No Info
lt3 = lt3.dropna() #drops any NaNs that might be left so we have a clean data set
lt3_filtered = lt3[lt3['Rank Value inc. Net Debt of Target'] > 0] # filter out deals that aren't rank valued so we can compare properly
lt3_filtered

,Instrument,M&A League Advisor,Rank Value inc. Net Debt of Target
19,154085312961,Banco Bradesco SA,1248.5276
28,154085368140,Credit Agricole CIB,1577.855359
38,154085394739,Mizuho Financial Group,850.022797
50,154085570483,Santander Corp & Invest Bkg,245.946278
66,154086998549,Mediobanca,1470.956776
...,...,...,...
67408,154088764032,Itau Unibanco,73.333592
67608,154088767214,Intermonte SIM SpA,21.119155
69291,154088815105,Huatai Securities Co Ltd,33.866835
69451,154088821475,Kaede Group,0.756723
69469,154088821890,Kaede Group,5.619951

In [9]:
# group all deals by League Advisor so we can sum up their Rank Values
lt3_filtered = lt3_filtered.groupby('M&A League Advisor')['Rank Value inc. Net Debt of Target'].sum()[0:]
lt4 = pd.DataFrame(lt3_filtered)

In [10]:
# Create a table with the 10 largest M&A League Advisors based on their total Rank Value 
lt5 = lt4.nlargest(10,'Rank Value inc. Net Debt of Target')
lt5

                         Rank Value inc. Net Debt of Target
M&A League Advisor
Morgan Stanley                                372942.843822
Barclays                                      224128.764115
Wells Fargo & Co                              137646.303934
Citi                                          120871.859851
Deutsche Bank                                 105618.836123
Rothschild & Co                                97408.444239
Centerview Partners LLC                        74356.231713
UBS                                            58948.559168
Mediobanca                                     53743.292738
Houlihan Lokey                                 53200.773973

In [11]:
import plotly.express as px # the plotly libraries for visualization and UI
import plotly.graph_objects as go

# create pie chart using Plotly by using the above dataframe and apply styling and formatting
fig2 = px.pie(lt5, values='Rank Value inc. Net Debt of Target', title='M&A League Table', names=lt5.index)
fig2.layout.template = 'plotly_dark'
fig2.update_traces(textposition='inside')
fig2.update_layout(uniformtext_minsize=12, uniformtext_mode='hide')
fig2.update(layout=dict(title=dict(x=0.43)))
fig2.show()

#### IPOs

LSEG provides industry-leading equity and equity-related transaction information and league tables to the global deal-making industry, comprising over 300,000 global equity and equity-related deals since the 1970s. LSEG relies upon direct deal submissions from global deal makers coupled with rigorous sourcing of regulatory filings, newswires, and company press releases to gather timely and detailed equity issuance information.

In [12]:
# Once again use SCREENER to pull list of IPOs meeting our criteria YTD
ipo_screen = "SCREEN(U(IN(DEALS)/*UNV:DEALSEQ*/), TR.NIisECM=True, \
            TR.NIIsRankEligible==true, relativedate(TR.NIIssueDate,YTD)/*dt:Date*/, \
            TR.NIIsIpo==true, IN(TR.NITransactionStatus,'LIVE'), CURN=USD)"
# input ipo screen results as instrument list and pull ipo attributes via fields from Eikon Data API. 
ipos = ld.get_data(
    ipo_screen,['TR.NISdcPackageNumber',
                'TR.NIIsIpo',
                'TR.NIIssueDate',
                'TR.NIIssuer',
                'TR.NITRBCIndustry',
                'TR.NIIssuerPermId',
                'TR.NIIssuerNation',
                'TR.NIRegionHQ',
                'TR.NIOfferPrice',
                'TR.NIProceedsAmtInclOverallotSoldAllMkts(Scale=6)',
                'TR.NIIssuerExchTicker',
                'TR.NISecurityTypeAllMkt',
                'TR.NIBookOrCoManager',
                'TR.NIHasLockup',
                'TR.NILockupDays',
                'TR.NILockupShares'])
ipos.head()

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\lseg\data\_tools\_dataframe.py:192: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\lseg\data\_tools\_dataframe.py:192: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\lseg\data\_tools\_dataframe.py:192: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\lseg\data\_tools\_dataframe.py:192: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\dtypes\cast.py:1056: RuntimeWarning:

invalid value encountered in cast

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\dtypes\cast.py:1080: RuntimeWarning:

invalid value encountered in cast

,Instrument,Package Identifier,IPO Flag,Dates: Issue Date,Issuer/Borrower Name Full,New Issues TRBC Industry,Issuer/Borrower PermID,Issuer/Borrower Nation,New Issues Region of Headquarters,Offer Price,Proceeds Amount Incl Overallotment Sold All Markets,Issuer/Borrower Stock Exchange Name,Security Type All Markets,Bookrunner Or Co-Managers,Lockup: Lockup Provision Flag,Number of Lockup Days,Number of Shares Subject to Lockup Agreement
0,154085119155,3656640,True,2025-01-09,B R Goyal Infrastructure Ltd,Construction & Engineering,5064570989,India,Asia Pacific Excluding Central Asia,135.0,852.12,National,Ordinary Or Common Shares,Beeline Capital Advisors Pvt Ltd,True,365,<NA>
1,154085121435,3656640,True,2025-01-09,B R Goyal Infrastructure Ltd,Construction & Engineering,5064570989,India,Asia Pacific Excluding Central Asia,135.0,852.12,National,Ordinary Or Common Shares,Beeline Capital Advisors Pvt Ltd,True,365,<NA>
2,154085355268,3804477,True,2025-01-09,Numans Health Food Holdings Co Ltd,Food Processing,5068485035,China (Mainland),Asia Pacific Excluding Central Asia,0.8,200.0,Hong Kong,Ordinary Or Common Shares,Caitong International Securities Co Ltd,True,365,<NA>
3,154085355268,,<NA>,NaT,,,,,,<NA>,<NA>,,,Quam Securities Co Ltd,<NA>,<NA>,<NA>
4,154085355268,,<NA>,NaT,,,,,,<NA>,<NA>,,,China Everbright Sec(HK)Ltd,<NA>,<NA>,<NA>

In [13]:
# remove rows with duplicate package identifiers which support the same deal and cause double count
ipos = ipos[ipos['Package Identifier'].replace('', pd.NA).notna()]
ipos.describe()

,Dates: Issue Date,Offer Price,Proceeds Amount Incl Overallotment Sold All Markets,Number of Lockup Days,Number of Shares Subject to Lockup Agreement
count,435,435.0,435.0,309.0,100.0
mean,2025-02-06 06:37:14.482758400,1691.257292,16965.949844,581.569579,117961696.3
min,2025-01-02 00:00:00,-999.0,0.25,30.0,30586.0
25%,2025-01-15 00:00:00,9.08,149.6172,180.0,3910124.0
50%,2025-02-10 00:00:00,39.92,430.471288,365.0,13052808.0
75%,2025-02-26 00:00:00,163.5,1925.10465,1095.0,62000000.0
max,2025-03-18 00:00:00,61900.0,1199448.061,1825.0,1728260872.0
std,NaN,5842.438122,97644.274626,432.071211,311856379.823436

In [14]:
industry = 'New Issues TRBC Industry'
fig3 = go.Figure()
trace = go.Bar(x=ipos[industry].value_counts().head(15).values, 
               y=ipos[industry].value_counts().head(15).index,
               orientation='h')
fig3.add_trace(trace)
fig3.layout.template = 'plotly_dark'
fig3

#### Dataquery

Leonid's article "[Dataquery – a syntax builder for screening with Eikon Data API](https://developers.lseg.com/en/article-catalog/article/dataquery-a-syntax-builder-for-screening-with-eikon-data-api)" is also great. In that article, he shows how one can use his [dataquery.py](https://github.com/LSEG-API-Samples/dataquery/blob/master/dataquery.py) document to make screens from scratch.

In [21]:
from dataquery import *

screen = SCREEN.express.universe(
    Equity(active=True, public=True, primary=True)).conditions(
        IN('TR.ImmediateParentCountryHQ', "United States"),
        # IN('TR.CoRTradingCountryCode', 'US'),
        TOP(field='TR.CompanyMarketCap', bound=10, metric=nnumber)
        ).currency('USD').query

screen

'SCREEN(U(IN(Equity(primary,public,active))),IN(TR.ImmediateParentCountryHQ,United States),TOP(TR.CompanyMarketCap,10,nnumber),CURN=USD)'

In [23]:
df = ld.get_data(
    universe='SCREEN(U(IN(Equity(primary,public,active))),IN(TR.ImmediateParentCountryHQ,"United States"),TOP(TR.CompanyMarketCap,10,nnumber),CURN=USD)',
    fields=['TR.CommonName','TR.CompanyMarketCap(Scale=6)','TR.ExchangeName',
            'TR.TRBCBusinessSector','TR.TotalReturn3Mo'])

display(df)

,Instrument,Company Common Name,Company Market Cap,Exchange Name,TRBC Business Sector Name,3 Month Total Return
0,AAPL.OQ,Apple Inc,3218105.036,NASDAQ/NGS (GLOBAL SELECT MARKET),Technology Equipment,-15.48248
1,NVDA.OQ,NVIDIA Corp,2916532.0,NASDAQ/NGS (GLOBAL SELECT MARKET),Technology Equipment,-8.320939
2,MSFT.OQ,Microsoft Corp,2889588.894745,NASDAQ/NGS (GLOBAL SELECT MARKET),Software & IT Services,-14.299325
3,AMZN.OQ,Amazon.com Inc,2074399.54336,NASDAQ/NGS (GLOBAL SELECT MARKET),Retailers,-15.319057
4,GOOGL.OQ,Alphabet Inc,2018226.52,NASDAQ/NGS (GLOBAL SELECT MARKET),Software & IT Services,-15.828423
5,META.OQ,Meta Platforms Inc,1532610.489398,NASDAQ/NGS (GLOBAL SELECT MARKET),Software & IT Services,-2.262904
6,BRKa.N,Berkshire Hathaway Inc,1128548.722999,"NEW YORK STOCK EXCHANGE, INC.",Consumer Goods Conglomerates,14.739666
7,AVGO.OQ,Broadcom Inc,914529.025457,NASDAQ/NGS (GLOBAL SELECT MARKET),Technology Equipment,-18.830334
8,LLY.N,Eli Lilly and Co,782012.688375,"NEW YORK STOCK EXCHANGE, INC.",Pharmaceuticals & Medical Research,6.114066
9,TSLA.OQ,Tesla Inc,765563.219976,NASDAQ/NGS (GLOBAL SELECT MARKET),Automobiles & Auto Parts,-50.400117

In [38]:
ld.close_session()

## Platform Session

Platform sessions allow us to use the LD Lib. without the Workspace Desktop App open. It was created for servers, and it is still aimed for data hungry users who require little human interation with the code at hand (e.g.: overnight data retraival). With that said, usecases have grown in breadth and complexity thoughout the years, and people may want such 'ping' services (i.e.: the ability to 'ping', to directly contact, the services that deliver data/calculations, without going through the Desktop App Proxy).

Platform session use-cases are a little more complicated to the Desktop session ones. We can authenticate ourselves with the Workspace Desktop App open with simply just the Python line:

In [23]:
import lseg.data as ld
ld.open_session(
    config_name="C:/Example.DataLibrary.Python-main/Configuration/lseg-data.config.json",
    name="platform.ldp")

In [24]:
rics = ld.discovery.Screener(
    'U(IN(Equity(active,public,primary))/*UNV:Public*/), ' +
    'TR.CompanyMarketCap(Scale=6)>=5000, IN(TR.ExchangeMarketIdCode,"XNYS"), ' +
    'IN(TR.TRBCBusinessSectorCode,"5010","5020","5030"), TR.TotalReturn3Mo>=15, ' +
    'CURN=USD')

df = ld.get_data(
    universe=rics,
    fields=['TR.CommonName','TR.CompanyMarketCap(Scale=6)','TR.ExchangeName',
            'TR.TRBCBusinessSector','TR.TotalReturn3Mo'])
 
display(df)

,Instrument,Company Common Name,Company Market Cap,Exchange Name,TRBC Business Sector Name,3 Month Total Return
0,EQT.N,EQT Corp,32089.66552,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,21.810072
1,CRK.N,Comstock Resources Inc,5535.416616,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,36.357091
2,ET.N,Energy Transfer LP,69651.33,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,17.35514
3,CQP.N,Cheniere Energy Partners LP,30223.87114,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,18.393019
4,MPLX.N,MPLX LP,55558.71,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,17.249071
5,AR.N,Antero Resources Corp,12366.2932,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,24.381847
6,HESM.N,Hess Midstream LP,8830.944995,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,16.157062

In [25]:
ld.close_session()