----
<div style="display: flex; align-items: center;">
    <img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="20%" style="vertical-align: top;">
    <h1 style="margin-left: 20px;">Data Library for Python</h1>
</div>

----

## Content layer - Search Lookup
This notebook demonstrates how to use the Search service of the LSEG Data Platform.

#### Learn more

To learn more about the LSEG Data Library for Python please join the LSEG Developer Community. By [registering](https://developers.refinitiv.com/iam/register) and [logging](https://developers.refinitiv.com/content/devportal/en_us/initCookie.html) into the LSEG Developer Community portal you will have free access to a number of learning materials 
 on the [LSEG Developer Portal](https://developers.lseg.com/en)

#### Getting Help and Support

If you have any questions regarding using the API, please post them on 
the [LSEG Data Q&A Forum](https://community.developers.refinitiv.com/spaces/321/index.html). 
The LSEG Developer Community will be happy to help.

## Set the configuration file location
For a better ease of use, you have the option to set initialization parameters of the LSEG Data Library in the _lseg-data.config.json_ configuration file. This file must be located beside your notebook, in your user folder or in a folder defined by the _LD_LIB_CONFIG_PATH_ environment variable. The _LD_LIB_CONFIG_PATH_ environment variable is the option used by this series of examples. The following code sets this environment variable.

In [1]:
import os
os.environ["LD_LIB_CONFIG_PATH"] = "../../../Configuration"

## Some Imports to start with

In [2]:
import lseg.data as ld
from lseg.data.content import search

## Open the data session

The open_session() function creates and open sessions based on the information contained in the lseg-data.config.json configuration file. Please edit this file to set the session type and other parameters required for the session you want to open.

In [3]:
ld.open_session()

## Retrieve data

### Lookup

In [4]:
response = search.lookup.Definition(
    view=search.Views.INSTRUMENTS,                               # Required parameter
    scope="RIC",                                                       # Required parameter
    terms="MSFT.O,AAPL.O,GOOG.O,IBM.N,KBANK.BK,SCC.BK",                # Required parameter
    select="BusinessEntity,DocumentTitle,CUSIP,SEDOL",                 # Required parameter
).get_data()

response.data.df

,BusinessEntity,DocumentTitle,CUSIP,SEDOL
MSFT.O,INSTRUMENTxEQUITY,"Microsoft Corp, Ordinary Share",594918104,<NA>
AAPL.O,INSTRUMENTxEQUITY,"Apple Inc, Ordinary Share",037833100,<NA>
GOOG.O,INSTRUMENTxEQUITY,"Alphabet Inc, Ordinary Share",02079K107,<NA>
KBANK.BK,INSTRUMENTxEQUITY,"Kasikornbank PCL, Ordinary Share",<NA>,6888783
SCC.BK,INSTRUMENTxEQUITY,"Siam Cement PCL, Ordinary Share",<NA>,6609917

In [5]:
response = search.lookup.Definition(
    view=search.Views.SEARCH_ALL,                              # Required parameter
    scope="RIC",                                                     # Required parameter
    terms="A,B,NOSUCHRIC,C,D",                                       # Required parameter
    select="BusinessEntity,DocumentTitle",                           # Required parameter
).get_data()

response.data.df

  BusinessEntity                                      DocumentTitle
A   QUOTExEQUITY  Agilent Technologies Inc, Ordinary Share, NYSE...
B   QUOTExEQUITY  Barnes Group Inc, Ordinary Share, NYSE Consoli...
C   QUOTExEQUITY   Citigroup Inc, Ordinary Share, NYSE Consolidated
D   QUOTExEQUITY  Dominion Energy Inc, Ordinary Share, NYSE Cons...

## Close the session

In [6]:
ld.close_session()