----
<div style="display: flex; align-items: center;">
    <img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="20%" style="vertical-align: top;">
    <h1 style="margin-left: 20px;">Data Library for Python</h1>
</div>

----

## Content layer - Search
This notebook demonstrates how to use the Search service of the LSEG Data Platform.

#### Learn more

To learn more about the LSEG Data Library for Python please join the LSEG Developer Community. By [registering](https://developers.refinitiv.com/iam/register) and [logging](https://developers.refinitiv.com/content/devportal/en_us/initCookie.html) into the LSEG Developer Community portal you will have free access to a number of learning materials 
 on the [LSEG Developer Portal](https://developers.lseg.com/en)

#### Getting Help and Support

If you have any questions regarding using the API, please post them on 
the [LSEG Data Q&A Forum](https://community.developers.refinitiv.com/spaces/321/index.html). 
The LSEG Developer Community will be happy to help.

## Set the configuration file location
For a better ease of use, you have the option to set initialization parameters of the LSEG Data Library in the _lseg-data.config.json_ configuration file. This file must be located beside your notebook, in your user folder or in a folder defined by the _LD_LIB_CONFIG_PATH_ environment variable. The _LD_LIB_CONFIG_PATH_ environment variable is the option used by this series of examples. The following code sets this environment variable.

In [1]:
import os
os.environ["LD_LIB_CONFIG_PATH"] = "../../../Configuration"

## Some Imports to start with

In [2]:
import lseg.data as ld
from lseg.data.content import search

## Open the data session

The open_session() function creates and open sessions based on the information contained in the lseg-data.config.json configuration file. Please edit this file to set the session type and other parameters required for the session you want to open.

In [3]:
ld.open_session()

## Retrieve data

### General Search

In [4]:
response = search.Definition("IBM Bonds").get_data()
response.data.df

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",46638470074,0x00102cf964da067d,US137584123=
1,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",192826895881,0x00102c8de61f1850,US194445610=
2,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",46644611190,0x00102c00c0900d61,US161784508=
3,INSTRUMENTxFIXEDINCOMExGOVCORP,"Fideicomiso Fibra Uno, Plain Vanilla Fixed Cou...",44658934367,0x0004051cd9531a8d,FUNO15=
4,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",232796002153,0x00102cfffd953398,459200KS9=
5,INSTRUMENTxFIXEDINCOMExGOVCORP,"Fideicomiso Fibra Uno, Fixed Margin over Index...",232779066893,0x00102cb061232de3,FUNO212X=VALR
6,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",15628361579,0x0000fa00068e7c0e,459200AM3=
7,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",44652137828,0x00040514f83234eb,US099109963=
8,INSTRUMENTxFIXEDINCOMExGOVCORP,"Fideicomiso Fibra Uno, Plain Vanilla Fixed Cou...",46637470062,0x00102ca4794f05ab,MX133173986=
9,INSTRUMENTxFIXEDINCOMExGOVCORP,"Fideicomiso Fibra Uno, Plain Vanilla Fixed Cou...",46637469894,0x00102cb77c4f05bd,898324AC2=

### Specify number of rows to fetch

In [5]:
response = search.Definition("IBM Bonds", top=100).get_data()
response.data.df

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",46638470074,0x00102cf964da067d,US137584123=
1,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",192826895881,0x00102c8de61f1850,US194445610=
2,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",46644611190,0x00102c00c0900d61,US161784508=
3,INSTRUMENTxFIXEDINCOMExGOVCORP,"Fideicomiso Fibra Uno, Plain Vanilla Fixed Cou...",44658934367,0x0004051cd9531a8d,FUNO15=
4,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",232796002153,0x00102cfffd953398,459200KS9=
...,...,...,...,...,...
95,INSTRUMENTxFIXEDINCOMExGOVCORP,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",15629030192,0x000386003ff1246f,<NA>
96,INSTRUMENTxFIXEDINCOMExGOVCORP,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",15628870427,0x000386001f82352d,<NA>
97,INSTRUMENTxFIXEDINCOMExGOVCORP,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",15628377011,0x0000fa000a004bbb,<NA>
98,INSTRUMENTxFIXEDINCOMExGOVCORP,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",15629030262,0x000386003ff16f24,<NA>
99,INSTRUMENTxFIXEDINCOMExGOVCORP,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",15629030258,0x000386003ff16b20,<NA>

### Filter Expressions

In [6]:
response = search.Definition(
    view=search.Views.GOV_CORP_INSTRUMENTS,
    select="ISIN,RIC,IssueDate,Currency,FaceIssuedTotal,CouponRate,MaturityDate", 
    filter="IssuerTicker eq 'IBM' and IsActive eq true and AssetStatus ne 'MAT'"
).get_data()
response.data.df

,ISIN,RIC,IssueDate,Currency,FaceIssuedTotal,CouponRate,MaturityDate
0,XS1375841233,US137584123=,2016-03-07,EUR,750000000,1.125,2024-09-06
1,XS1944456109,US194445610=,2019-01-31,EUR,1000000000,0.875,2025-01-31
2,XS1617845083,US161784508=,2017-05-23,EUR,1000000000,0.95,2025-05-23
3,US459200KS93,459200KS9=,2022-07-27,USD,1000000000,4.0,2025-07-27
4,US459200AM34,459200AM3=,1995-10-30,USD,600000000,7.0,2025-10-30
5,XS0991099630,US099109963=,2013-11-07,EUR,1000000000,2.875,2025-11-07
6,US459200KW06,459200KW0=,2023-02-06,USD,850000000,4.5,2026-02-06
7,US459200JG74,459200JG7=,2016-02-19,USD,1350000000,3.45,2026-02-19
8,US459200JZ55,459200JZ5=,2019-05-15,USD,3000000000,3.3,2026-05-15
9,XS1512978112,US151297811=,2016-11-02,JPY,42000000000,0.3,2026-11-02

### Properties - Metadata

In [7]:
response = search.metadata.Definition(
    view = search.Views.GOV_CORP_INSTRUMENTS  # Required parameterc
).get_data() 

response.data.df

,,Type,Searchable,Sortable,Navigable,Groupable,Exact,Symbol
AccrualDate,AccrualDate,Date,True,True,True,False,False,False
AccruedInterest,AccruedInterest,Double,True,True,True,False,False,False
ActiveEstimatesExist,ActiveEstimatesExist,Boolean,True,False,False,False,False,False
AdtLocalCurrencyValue,AdtLocalCurrencyValue,String,True,False,False,False,False,False
AdtLocalCurrencyValueName,AdtLocalCurrencyValueName,String,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...
WorstStandardYield,WorstStandardYield,Double,True,True,True,False,False,False
WorstYearsToRedem,WorstYearsToRedem,Double,True,True,True,False,False,False
YieldCurveBenchmarkRIC,YieldCurveBenchmarkRIC,String,False,False,False,False,False,False
YieldTypeDescription,YieldTypeDescription,String,True,False,False,False,False,False
ZCodeValue,ZCodeValue,String,True,True,False,True,False,True

### Navigators

In [8]:
response = search.Definition(
    top=0,
    navigators="RCSTRBC2012Leaf"
).get_data()

### Search with Navigator option

In [9]:
response = search.Definition(
    view=search.Views.COMMODITY_QUOTES,
    query="cheese",
    navigators="ExchangeName"
).get_data()

response.data.df

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21622940491,273610776,CSCc1
1,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21622425217,272623267,0#CSC:
2,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21909537890,628553925,CSCN24
3,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21622940494,273610782,CSCc2
4,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21622940497,273610784,CSCc3
5,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21915186698,635366864,CSCQ24
6,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21902231392,619841775,CSCM24
7,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21622940525,273610812,CSCc14
8,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21622940502,273610789,CSCc5
9,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21980547592,717840977,CSCN25

In [10]:
response.data.raw["Navigators"]['ExchangeName']

{'Buckets': [{'Label': 'CME:Index and Options Market', 'Count': 17419},
  {'Label': 'Chicago Mercantile Exchange', 'Count': 3060},
  {'Label': 'Source is a Refinitiv Contributor', 'Count': 2979},
  {'Label': 'INTL FCStone Inc', 'Count': 2550},
  {'Label': 'US Department of Agriculture', 'Count': 103},
  {'Label': 'Commodity Futures Trading Commission', 'Count': 66},
  {'Label': 'Complete Intelligence', 'Count': 65},
  {'Label': 'Intercontinental Exchange US', 'Count': 31},
  {'Label': 'US Bureau Of Labor Statistics', 'Count': 10},
  {'Label': 'DCA Markets B.V. - DCA-Markets-PRA Price Reporting Agent',
   'Count': 4},
  {'Label': 'European Commission', 'Count': 3},
  {'Label': 'ESALQ', 'Count': 2},
  {'Label': 'Refinitiv', 'Count': 2},
  {'Label': 'CME:International Monetary Market', 'Count': 1}]}

In [11]:
response = search.Definition(
    view=search.Views.GOV_CORP_INSTRUMENTS,
    top=0,
    navigators="Currency(buckets:10,desc:sum_FaceOutstandingUSD,calc:max_CouponRate)"
).get_data()

response.data.raw

{'Total': 11494208,
 'Hits': [],
 'Navigators': {'Currency': {'Buckets': [{'Label': 'USD',
     'Count': 3763389,
     'max_CouponRate': 1800.0,
     'sum_FaceOutstandingUSD': 49438954323649.78},
    {'Label': 'EUR',
     'Count': 1093746,
     'max_CouponRate': 500.0,
     'sum_FaceOutstandingUSD': 21527212316149.0},
    {'Label': 'CNY',
     'Count': 342663,
     'max_CouponRate': 72.0,
     'sum_FaceOutstandingUSD': 20044978882106.297},
    {'Label': 'JPY',
     'Count': 471204,
     'max_CouponRate': 632.0,
     'sum_FaceOutstandingUSD': 10901404501957.016},
    {'Label': 'GBP',
     'Count': 200667,
     'max_CouponRate': 120.0,
     'sum_FaceOutstandingUSD': 4186088564763.0},
    {'Label': 'CAD',
     'Count': 321134,
     'max_CouponRate': 100.0,
     'sum_FaceOutstandingUSD': 2573047806153.0},
    {'Label': 'INR',
     'Count': 112945,
     'max_CouponRate': 42.75,
     'sum_FaceOutstandingUSD': 2497247939348.0},
    {'Label': 'KRW',
     'Count': 400869,
     'max_CouponRate': 46.41,
     'sum_FaceOutstandingUSD': 2140298006081.0},
    {'Label': 'AUD',
     'Count': 149976,
     'max_CouponRate': 120.96,
     'sum_FaceOutstandingUSD': 1571159285514.6873},
    {'Label': 'BRL',
     'Count': 68846,
     'max_CouponRate': 108.5,
     'sum_FaceOutstandingUSD': 1388815848653.7607}]}}}

#### Sub-navigator

In [11]:
response = search.Definition(
    view=search.Views.PEOPLE,
    top=0,
    navigators="FirstName(buckets:3,sub:LastName(buckets:2))"
).get_data()

response.data.raw["Navigators"]["FirstName"]["Buckets"]

[{'Label': 'John',
  'Count': 45097,
  'LastName': {'Buckets': [{'Label': 'Smith', 'Count': 122},
    {'Label': 'Wilson', 'Count': 118}]}},
 {'Label': 'David',
  'Count': 44910,
  'LastName': {'Buckets': [{'Label': 'Smith', 'Count': 259},
    {'Label': 'Brown', 'Count': 184}]}},
 {'Label': 'Michael',
  'Count': 43315,
  'LastName': {'Buckets': [{'Label': 'Smith', 'Count': 205},
    {'Label': 'Brown', 'Count': 148}]}}]

### Search with order_by option

In [12]:
response = search.Definition(
    view=search.Views.PEOPLE,
    query="ceo",
    order_by="YearOfBirth desc,LastName,FirstName",
    select="YearOfBirth,DocumentTitle"
).get_data()

response.data.df

   YearOfBirth                                      DocumentTitle
0         1997  Carl Fredrik Mikael Akerman - VOLTA GREENTECH ...
1         1997  Martins Balodis - Facing It International - Ch...
2         1997  David Samuel Haloho - David Sistem Group PT - ...
3         1997  Rishi Tandon - Creative Casuals (India) Pvt Lt...
4         1996  Senthil Nathan Abishiek - Acsen Tex Pvt Ltd - ...
5         1996  Mitchell Babalola Christopher Fasanya - Search...
6         1996  Ethan Fraenkel - Prograd uk Inc - Chief Execut...
7         1996  Kazuki Fujii - Ileo Co Ltd - Chief Executive O...
8         1996  Elliot Alexander Garreffa - Oasiis Ltd - Chief...
9         1996  Ivan Liljeqvist - Moralis Web3 Technology AB -...

### Search with group_by option

In [13]:
response = search.Definition(
    view=search.Views.INDICATOR_QUOTES,
    query="rate",
    group_by="CentralBankName",
    group_count=2,
    select="CentralBankName,DocumentTitle,RIC"
).get_data()

response.data.df

,CentralBankName,DocumentTitle,RIC
0,Federal Reserve System,"United States, Policy Rates, Fed Funds Target ...",USFOMC=ECI
1,Federal Reserve System,"United States, Policy Rates, Fed Overnight Rep...",USRRP=ECI
2,Bank of England,"United Kingdom, Policy Rates, Bank Rate, Reute...",GBBOEI=ECI
3,Bank of England,"United Kingdom, BOE Bank Rate (Quarterly)-Mean...",pGBBASEQP=E
4,European Central Bank,"Euro Zone, Policy Rates, ECB Main refinancing,...",EUECBR=ECI
5,European Central Bank,"Euro Zone, Policy Rates, ECB Deposit Rate, Reu...",EUECBD=ECI
6,Central Bank of Egypt,"Egypt, Policy Rates, Overnight Deposit Rate, R...",EGINTR=ECI
7,Central Bank of Egypt,"Egypt, Policy Rates, Overnight Lending Rate, R...",EGCBIR=ECI
8,Banca Nationala a Romaniei,"Romania, Policy Rates, Policy Rate, Reuters Po...",ROINTR=ECI
9,Banca Nationala a Romaniei,"Romania, Mon Policy Rate-Sest, Reuters Polls, ...",pROINTR=F

### Search For People

In [14]:
response = search.Definition(
    query="cfo",
    view=search.Views.PEOPLE
).get_data()

response.data.df

,BusinessEntity,DocumentTitle,PermID,PI
0,PERSON,Amy E. Hood - Microsoft Corp - Chief Financial...,34415553383,34415553383
1,PERSON,Luca Maestri - Apple Inc - Chief Financial Off...,34414554748,34414554748
2,PERSON,Brian T. Olsavsky - Amazon.com Inc - Senior Vi...,34417610894,34417610894
3,PERSON,"Ruth M. Porat - Alphabet Inc - President, Chie...",34413960665,34413960665
4,PERSON,Susan J. Li - Meta Platforms Inc - Chief Finan...,34424688603,34424688603
5,PERSON,Marc D. Hamburg - Berkshire Hathaway Inc - Chi...,34413152672,34413152672
6,PERSON,Andrew K. Klatt - Berkshire Hathaway Inc - CFO...,34414966250,34414966250
7,PERSON,Xu Hong - Alibaba Group Holding Ltd - Chief Fi...,34425652371,34425652371
8,PERSON,John Lo - Tencent Holdings Ltd - Chief Financi...,34414907131,34414907131
9,PERSON,Joseph J. Wolk - Johnson & Johnson - Chief Fin...,34422069022,34422069022

## Close the session

In [15]:
ld.close_session()