----
<div style="display: flex; align-items: center;">
    <img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="20%" style="vertical-align: top;">
    <h1 style="margin-left: 20px;">Data Library for Python</h1>
</div>

----

## Content - Fundamental and Reference
This notebook demonstrates how to retrieve Fundamental and Reference data.

#### Learn more

To learn more about the LSEG Data Library for Python please join the LSEG Developer Community. By [registering](https://developers.refinitiv.com/iam/register) and [logging](https://developers.refinitiv.com/content/devportal/en_us/initCookie.html) into the LSEG Developer Community portal you will have free access to a number of learning materials 
 on the [LSEG Developer Portal](https://developers.lseg.com/en)

#### Getting Help and Support

If you have any questions regarding using the API, please post them on 
the [LSEG Data Q&A Forum](https://community.developers.refinitiv.com/spaces/321/index.html). 
The LSEG Developer Community will be happy to help.

## Set the configuration file location
For a better ease of use, you have the option to set initialization parameters of the LSEG Data Library in the _lseg-data.config.json_ configuration file. This file must be located beside your notebook, in your user folder or in a folder defined by the _LD_LIB_CONFIG_PATH_ environment variable. The _LD_LIB_CONFIG_PATH_ environment variable is the option used by this series of examples. The following code sets this environment variable.

In [1]:
import os
os.environ["LD_LIB_CONFIG_PATH"] = "../../../Configuration"

## Some Imports to start with

In [2]:
import lseg.data as ld
from lseg.data.content import fundamental_and_reference
import datetime

## Open the data session

The open_session() function creates and open sessions based on the information contained in the lseg-data.config.json configuration file. Please edit this file to set the session type and other parameters required for the session you want to open.

In [3]:
ld.open_session()

## Retrieve data

### Simple requets
#### Get Revenue and GrossProfit for IBM.N and TRI.N

In [4]:
response = fundamental_and_reference.Definition(
    ["TRI.N", "IBM.N"],
    ["TR.Revenue", "TR.GrossProfit"]
).get_data()

response.data.df

  Instrument      Revenue  Gross Profit
0      TRI.N   6794000000    6490000000
1      IBM.N  61860000000   34300000000

### Simple request with chain
#### Get Revenue and GrossProfit for all constituents of the chain

In [5]:
response = fundamental_and_reference.Definition(
    ["0#.DJI"],
    ["TR.Revenue", "TR.GrossProfit"]
).get_data()

response.data.df

   Instrument       Revenue  Gross Profit
0        GS.N  108418000000   40556000000
1       NKE.N   51217000000   22292000000
2     CSCO.OQ   56998000000   35753000000
3       JPM.N          <NA>          <NA>
4       DIS.N   88898000000   29697000000
5     INTC.OQ   54228000000   21711000000
6       DOW.N   44622000000    4880000000
7       MRK.N   60115000000   44200000000
8       CVX.N  196913000000   77717000000
9       AXP.N   65380000000   41180000000
10       VZ.N  133974000000   79169000000
11       HD.N  152669000000   50960000000
12      MCD.N   25493700000   14562500000
13      UNH.N          <NA>          <NA>
14    AMZN.OQ  574785000000  270046000000
15       KO.N   45754000000   27234000000
16      JNJ.N   85159000000   58915000000
17    MSFT.OQ  211915000000  146052000000
18     HON.OQ   36662000000   13667000000
19      CRM.N   34857000000   26316000000
20       PG.N   82006000000   39406000000
21      IBM.N   61860000000   34300000000
22      MMM.N   32681000000   14305000000
23    AAPL.OQ  383285000000  169148000000
24      WMT.N  648125000000  157983000000
25      CAT.N   67060000000   24403000000
26    AMGN.OQ   28190000000   19775000000
27        V.N   32653000000   26086000000
28      TRV.N          <NA>          <NA>
29       BA.N   77794000000    7724000000

### Request with global parameters
#### Get Revenue and GrossProfit for GOOG.O and APPL.O with applied global parameters

In [6]:
response = fundamental_and_reference.Definition(
    ["GOOG.O", "AAPL.O"],
    ["TR.Revenue", "TR.GrossProfit"],
    {"SDate": "0CY", "Curn": "CAD"}
).get_data()

response.data.df

  Instrument       Revenue  Gross Profit
0     GOOG.O  383214496400  212222051700
1     AAPL.O  520386044500  229652239600

### Request with data item parameters
#### Get PriceTargetMean and LowPrice for GOOG.O and APPL.O with applied local parameters for each field

In [7]:
response = fundamental_and_reference.Definition(
    ["GOOG.O", "AAPL.O"],
    ["TR.PriceTargetMean(SDate:0CY)", "TR.LOWPRICE(SDate:0d)"]
).get_data()

response.data.df

  Instrument  Price Target - Mean  Low Price
0     GOOG.O                149.4     177.78
1     AAPL.O            199.16128      206.9

### Timeseries
#### Get timeseries data

In [8]:
response = fundamental_and_reference.Definition(
    ["GOOG.O", "MSFT.O", "FB.O", "AMZN.O", "TWTR.K"],
    ["TR.Revenue.date", "TR.Revenue", "TR.GrossProfit"],
    {"Scale": 6, "SDate": 0, "EDate": -3, "FRQ": "FY", "Curn": "EUR"}
).get_data()

response.data.df

   Instrument       Date       Revenue  Gross Profit
0      GOOG.O 2023-12-31  278538.92522  158592.68486
1      GOOG.O 2022-12-31   264281.9584   146357.8752
2      GOOG.O 2021-12-31  226632.96342  129044.36268
3      GOOG.O 2020-12-31   149453.1076     80074.546
4      MSFT.O 2023-06-30  194239.16985  133869.80268
5      MSFT.O 2022-06-30   189153.5454   129384.1924
6      MSFT.O 2021-06-30  141787.27064   97728.01168
7      MSFT.O 2020-06-30  127339.12585   86311.73543
8        FB.O        NaT          <NA>          <NA>
9      AMZN.O 2023-12-31  520829.93205  244696.78198
10     AMZN.O 2022-12-31   480265.7152   210382.0288
11     AMZN.O 2021-12-31  413283.62052  173713.49748
12     AMZN.O 2020-12-31   316109.2032   125077.4316
13     TWTR.K 2021-12-31   4466.457816    2885.26017
14     TWTR.K 2020-12-31   3042.946561   1924.148067
15     TWTR.K 2019-12-31   3085.929028   2071.620233
16     TWTR.K 2018-12-31   2652.693659   1811.293475

### Close the session

In [9]:
ld.close_session()