----
<div style="display: flex; align-items: center;">
    <img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="20%" style="vertical-align: top;">
    <h1 style="margin-left: 20px;">Data Library for Python</h1>
</div>

----

## Content - Historical Pricing - Synchronous calls

This notebook demonstrates how to retrieve Historical Pricing data from the LSEG Data Platform OR via Eikon or LSEG Workspace.   

Whilst this notebook uses synchronous calls, there is an async technique which will be explored in a future example/tutorial.

## Set the location of the configuration file
For ease of use, you can set various initialization parameters of the RD Library in the **_lseg-data.config.json_** configuration file - as described in the Quick Start -> Sessions example.

### One config file for the tutorials
As these tutorial Notebooks are categorised into sub-folders and to avoid the need for multiple config files, we will use the _LD_LIB_CONFIG_PATH_ environment variable to point to a single instance of the config file in the top-level ***Configuration*** folder.

Before proceeding, please **ensure you have entered your credentials** into the config file in the ***Configuration*** folder.

In [ ]:
import os
os.environ["LD_LIB_CONFIG_PATH"] = "../../../Configuration"

In [12]:
from lseg.data.content import historical_pricing
import lseg.data as ld
import datetime
import json

## Open the default session

To open the default session ensure you have 
* a '*lseg-data.config.json*' in the ***Configuration*** directory 
* **populated the file with your credentials**
* and specified a 'default' session in the config file    

**Note**: To request Historical Pricing data you must be using an RDP Platform (Cloud) session or a Desktop Session(Eikon/Workspace).   
It is not currently possible to request historical data from a deployed Session

In [13]:
ld.open_session()

## Request Historical Pricing data

### Historical Price Events

NOTE: We have not specified any start or end times, so the request defaults to the 20 most recent events

In [14]:
response = historical_pricing.events.Definition("VOD.L").get_data()
# Extract in DataFrame format
response.data.df

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\lseg\data\_tools\_dataframe.py:177:FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

VOD.L,EVENT_TYPE,RTL,SOURCE_DATETIME,SEQNUM,TRDXID_1,TRDPRC_1,TRDVOL_1,VWAP,BID,BIDSIZE,...,TR_TRD_FLG,ACVOL_UNS,OPEN_PRC,HIGH_1,LOW_1,MID_PRICE,IMB_SH,IMB_SIDE,QUALIFIERS,TAG
Timestamp,,,,,,,,,,,,,,,,,,,,,
2024-06-19 15:17:05.410,quote,44320,2024-06-19T15:17:05.410000000Z,3087317,<NA>,<NA>,<NA>,<NA>,71.56,86390,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[BID_TONE],d19_m06_y2024_h15_m17_s05_ms0410_0_44320_0_35
2024-06-19 15:17:05.410,quote,44352,2024-06-19T15:17:05.410000000Z,3087319,<NA>,<NA>,<NA>,<NA>,71.56,69895,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[BID_TONE],d19_m06_y2024_h15_m17_s05_ms0410_0_44352_0_35
2024-06-19 15:17:05.410,quote,44336,2024-06-19T15:17:05.410000000Z,3087318,<NA>,<NA>,<NA>,<NA>,71.56,81490,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[BID_TONE],d19_m06_y2024_h15_m17_s05_ms0410_0_44336_0_35
2024-06-19 15:17:05.411,quote,44368,2024-06-19T15:17:05.411000000Z,3087320,<NA>,<NA>,<NA>,<NA>,71.56,69895,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[ASK_TONE],d19_m06_y2024_h15_m17_s05_ms0411_0_44368_0_35
2024-06-19 15:17:05.415,quote,44384,2024-06-19T15:17:05.415000000Z,3087321,<NA>,<NA>,<NA>,<NA>,71.56,64713,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[BID_TONE],d19_m06_y2024_h15_m17_s05_ms0415_0_44384_0_35
2024-06-19 15:17:05.513,quote,44400,2024-06-19T15:17:05.513000000Z,3087324,<NA>,<NA>,<NA>,<NA>,71.56,60251,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[BID_TONE],d19_m06_y2024_h15_m17_s05_ms0513_0_44400_0_35
2024-06-19 15:17:05.542,quote,44416,2024-06-19T15:17:05.542000000Z,3087327,<NA>,<NA>,<NA>,<NA>,71.56,64672,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[BID_TONE],d19_m06_y2024_h15_m17_s05_ms0542_0_44416_0_35
2024-06-19 15:17:06.004,quote,44432,2024-06-19T15:17:06.004000000Z,3087413,<NA>,<NA>,<NA>,<NA>,71.56,60251,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[BID_TONE],d19_m06_y2024_h15_m17_s06_ms0004_0_44432_0_35
2024-06-19 15:17:06.004,quote,44448,2024-06-19T15:17:06.004000000Z,3087414,<NA>,<NA>,<NA>,<NA>,71.56,65151,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[BID_TONE],d19_m06_y2024_h15_m17_s06_ms0004_0_44448_0_35
2024-06-19 15:17:06.004,quote,44464,2024-06-19T15:17:06.004000000Z,3087415,<NA>,<NA>,<NA>,<NA>,71.56,59374,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[BID_TONE],d19_m06_y2024_h15_m17_s06_ms0004_0_44464_0_35
2024-06-19 15:17:06.004,quote,44480,2024-06-19T15:17:06.004000000Z,3087416,<NA>,<NA>,<NA>,<NA>,71.56,59374,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[ASK_TONE],d19_m06_y2024_h15_m17_s06_ms0004_0_44480_0_35
2024-06-19 15:17:06.004,quote,44496,2024-06-19T15:17:06.004000000Z,3087417,<NA>,<NA>,<NA>,<NA>,71.56,59374,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[ASK_TONE],d19_m06_y2024_h15_m17_s06_ms0004_0_44496_0_35
2024-06-19 15:17:06.565,quote,44512,2024-06-19T15:17:06.565000000Z,3087501,<NA>,<NA>,<NA>,<NA>,71.56,55851,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[BID_TONE],d19_m06_y2024_h15_m17_s06_ms0565_0_44512_0_35
2024-06-19 15:17:07.002,quote,44528,2024-06-19T15:17:07.002000000Z,3087544,<NA>,<NA>,<NA>,<NA>,71.56,50951,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[BID_TONE],d19_m06_y2024_h15_m17_s07_ms0002_0_44528_0_35
2024-06-19 15:17:07.614,quote,44544,2024-06-19T15:17:07.614000000Z,3087671,<NA>,<NA>,<NA>,<NA>,71.56,57221,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[BID_TONE],d19_m06_y2024_h15_m17_s07_ms0614_0_44544_0_35
2024-06-19 15:17:07.615,quote,44560,2024-06-19T15:17:07.615000000Z,3087684,<NA>,<NA>,<NA>,<NA>,71.56,57221,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[ASK_TONE],d19_m06_y2024_h15_m17_s07_ms0615_0_44560_0_35
2024-06-19 15:17:07.615,quote,44576,2024-06-19T15:17:07.615000000Z,3087685,<NA>,<NA>,<NA>,<NA>,71.56,62121,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[BID_TONE],d19_m06_y2024_h15_m17_s07_ms0615_0_44576_0_35
2024-06-19 15:17:08.117,quote,44592,2024-06-19T15:17:08.117000000Z,3087801,<NA>,<NA>,<NA>,<NA>,71.56,66529,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[BID_TONE],d19_m06_y2024_h15_m17_s08_ms0117_0_44592_0_35
2024-06-19 15:17:08.117,quote,44608,2024-06-19T15:17:08.117000000Z,3087802,<NA>,<NA>,<NA>,<NA>,71.56,66529,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[ASK_TONE],d19_m06_y2024_h15_m17_s08_ms0117_0_44608_0_35
2024-06-19 15:17:08.413,quote,44624,2024-06-19T15:17:08.413000000Z,3087818,<NA>,<NA>,<NA>,<NA>,71.56,66529,...,<NA>,<NA>,<NA>,<NA>,<NA>,71.57,<NA>,<NA>,[ASK_TONE],d19_m06_y2024_h15_m17_s08_ms0413_0_44624_0_35

#### Data is also available in the Raw JSON format

In [15]:
# JSON format (display only 200 characters of headers + data to minimise output)
print(json.dumps(response.data.raw['universe'], indent=2),
      'Headers:',
      json.dumps(response.data.raw['headers'], indent=2)[0:200],
      'Data:',
      json.dumps(response.data.raw['data'], indent=2)[0:200])

{
  "ric": "VOD.L"
} Headers: [
  {
    "name": "DATE_TIME",
    "type": "string"
  },
  {
    "name": "EVENT_TYPE",
    "type": "string"
  },
  {
    "name": "RTL",
    "type": "number",
    "decimalChar": "."
  },
  {
    "name" Data: [
  [
    "2024-06-19T15:17:08.413000000Z",
    "quote",
    44624,
    "2024-06-19T15:17:08.413000000Z",
    "3087818",
    null,
    null,
    null,
    null,
    71.56,
    66529,
    71.58,
    68

#### Historical Price events with some optional parameters
Specify start + end time and Corrections parameters

In [16]:
response = historical_pricing.events.Definition(
    universe = "AAPL.O", 
    start = datetime.timedelta(-1), 
    end = datetime.timedelta(0),
    adjustments = [
        historical_pricing.Adjustments.EXCHANGE_CORRECTION,
        historical_pricing.Adjustments.MANUAL_CORRECTION
    ],
    count=10
    ).get_data()
# Extract in DataFrame format
response.data.df

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\lseg\data\_tools\_dataframe.py:177:FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

AAPL.O,EVENT_TYPE,RTL,SOURCE_DATETIME,SEQNUM,TRDXID_1,TRDPRC_1,TRDVOL_1,ACVOL_UNS,VWAP,BID,...,OPEN_PRC,HIGH_1,LOW_1,IMP_VOLT,BID_MMID1,ASK_MMID1,LIMIT_INDQ,SH_SAL_RES,QUALIFIERS,TAG
Timestamp,,,,,,,,,,,,,,,,,,,,,
2024-06-18 23:59:47.305,quote,42544,2024-06-18T23:59:47.305000000Z,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,214,...,<NA>,<NA>,<NA>,<NA>,PSE,PSE,,N,[PRC_QL_CD]; [PRC_QL3]; [GV1_TEXT],d18_m06_y2024_h23_m59_s47_ms0305_0_42544_0_35
2024-06-18 23:59:47.320,trade,42574,2024-06-18T23:59:47.320000000Z,7239008,ADF,214.0195,1,79943002,<NA>,214,...,217.59,218.63,213,<NA>,<NA>,<NA>,<NA>,<NA>,@ TI[GV4_TEXT];ODT[IRGCOND],d18_m06_y2024_h23_m59_s47_ms0320_0_42574_0_4
2024-06-18 23:59:47.943,trade,42590,2024-06-18T23:59:47.943000000Z,7239012,ADF,214.0199,1,79943003,<NA>,214,...,217.59,218.63,213,<NA>,<NA>,<NA>,<NA>,<NA>,@ TI[GV4_TEXT];ODT[IRGCOND],d18_m06_y2024_h23_m59_s47_ms0943_0_42590_0_4
2024-06-18 23:59:48.504,trade,42606,2024-06-18T23:59:48.504000000Z,7239016,ADF,214.0199,100,79943103,<NA>,214,...,217.59,218.63,213,<NA>,<NA>,<NA>,<NA>,<NA>,@ T [GV4_TEXT];132[IRGCOND],d18_m06_y2024_h23_m59_s48_ms0504_0_42606_0_4
2024-06-18 23:59:49.838,trade,42622,2024-06-18T23:59:49.838000000Z,7239033,ADF,214.02,100,79943203,<NA>,214,...,217.59,218.63,213,<NA>,<NA>,<NA>,<NA>,<NA>,@ T [GV4_TEXT];132[IRGCOND],d18_m06_y2024_h23_m59_s49_ms0838_0_42622_0_4
2024-06-18 23:59:56.729,trade,42638,2024-06-18T23:59:56.729000000Z,7239050,ADF,214.01,1,79943204,<NA>,214,...,217.59,218.63,213,<NA>,<NA>,<NA>,<NA>,<NA>,@ TI[GV4_TEXT];ODT[IRGCOND],d18_m06_y2024_h23_m59_s56_ms0729_0_42638_0_4
2024-06-18 23:59:59.625,trade,42654,2024-06-18T23:59:59.625000000Z,7239060,ADF,214.02,50,79943254,<NA>,214,...,217.59,218.63,213,<NA>,<NA>,<NA>,<NA>,<NA>,@ TI[GV4_TEXT];ODT[IRGCOND],d18_m06_y2024_h23_m59_s59_ms0625_0_42654_0_4
2024-06-18 23:59:59.626,quote,42656,2024-06-18T23:59:59.626000000Z,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,214,...,<NA>,<NA>,<NA>,<NA>,PSE,PSE,,N,[PRC_QL_CD]; [PRC_QL3]; [GV1_TEXT],d18_m06_y2024_h23_m59_s59_ms0626_0_42656_0_35
2024-06-18 23:59:59.629,quote,42672,2024-06-18T23:59:59.629000000Z,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,214,...,<NA>,<NA>,<NA>,<NA>,PSE,PSE,,N,[PRC_QL_CD]; [PRC_QL3]; [GV1_TEXT],d18_m06_y2024_h23_m59_s59_ms0629_0_42672_0_35
2024-06-19 00:00:00.048,mkt. condition,42688,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,AGX[PRC_QL2];Mkt Conditions[USER];C [INST_PHA...,d19_m06_y2024_h00_m00_s00_ms0048_0_42688_0_28

### Historical Price Intraday Summaries  

NOTE: Once again, we have not specified any start or end times, so the request defaults to the 20 most recent price points at the specified interval.

In [17]:
response = historical_pricing.summaries.Definition(
    "VOD.L", 
    count=2,
    interval=historical_pricing.Intervals.FIVE_MINUTES).get_data()
# Extract in DataFrame format
response.data.df

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\lseg\data\_tools\_dataframe.py:177:FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

VOD.L,HIGH_1,LOW_1,OPEN_PRC,TRDPRC_1,NUM_MOVES,ACVOL_UNS,HIGH_YLD,LOW_YLD,OPEN_YLD,YIELD,...,BID_NUMMOV,ASK_HIGH_1,ASK_LOW_1,OPEN_ASK,ASK,ASK_NUMMOV,MID_HIGH,MID_LOW,MID_OPEN,MID_PRICE
Timestamp,,,,,,,,,,,,,,,,,,,,,
2024-06-19 15:10:00,71.68,71.54,71.68,71.6,69,384519,<NA>,<NA>,<NA>,<NA>,...,645,71.72,71.56,71.72,71.62,645,71.7,71.54,71.7,71.6
2024-06-19 15:15:00,71.6,71.58,71.6,71.58,13,67759,<NA>,<NA>,<NA>,<NA>,...,191,71.62,71.58,71.62,71.58,191,71.61,71.57,71.6,71.57

#### Historical Price Intraday Summaries with some optional parameters  

Specify a limit of 500 data points and filter for certain MarketSession types

In [18]:
response = historical_pricing.summaries.Definition(
    universe = "IBM.N", 
    interval = historical_pricing.Intervals.ONE_MINUTE,     # Supported intervals: ONE_MINUTE, FIVE_MINUTES, TEN_MINUTES, THIRTY_MINUTES, ONE_HOUR
    count = 500,
    sessions = [
        historical_pricing.MarketSession.PRE, 
        historical_pricing.MarketSession.NORMAL, 
        historical_pricing.MarketSession.POST
    ]).get_data()
# Extract in DataFrame format
response.data.df

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\lseg\data\_tools\_dataframe.py:177:FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

IBM.N,HIGH_1,LOW_1,OPEN_PRC,TRDPRC_1,NUM_MOVES,ACVOL_UNS,HIGH_YLD,LOW_YLD,OPEN_YLD,YIELD,...,BID_NUMMOV,ASK_HIGH_1,ASK_LOW_1,OPEN_ASK,ASK,ASK_NUMMOV,MID_HIGH,MID_LOW,MID_OPEN,MID_PRICE
Timestamp,,,,,,,,,,,,,,,,,,,,,
2024-06-17 18:12:00,169.51,169.46,169.47,169.5,12,340,<NA>,<NA>,<NA>,<NA>,...,95,169.51,169.48,169.48,169.51,95,<NA>,<NA>,<NA>,<NA>
2024-06-17 18:13:00,169.52,169.46,169.49,169.46,17,848,<NA>,<NA>,<NA>,<NA>,...,36,169.52,169.49,169.51,169.5,36,<NA>,<NA>,<NA>,<NA>
2024-06-17 18:14:00,169.52,169.4,169.5,169.4,21,765,<NA>,<NA>,<NA>,<NA>,...,107,169.54,169.45,169.51,169.46,107,<NA>,<NA>,<NA>,<NA>
2024-06-17 18:15:00,169.5,169.4,169.4,169.48,19,1434,<NA>,<NA>,<NA>,<NA>,...,86,169.55,169.44,169.46,169.51,86,<NA>,<NA>,<NA>,<NA>
2024-06-17 18:16:00,169.54,169.5,169.52,169.54,6,321,<NA>,<NA>,<NA>,<NA>,...,119,169.6,169.51,169.54,169.58,119,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-06-18 19:56:00,170.71,170.62,170.63,170.69,112,8593,<NA>,<NA>,<NA>,<NA>,...,394,170.74,170.63,170.64,170.7,394,<NA>,<NA>,<NA>,<NA>
2024-06-18 19:57:00,170.73,170.53,170.69,170.57,178,17351,<NA>,<NA>,<NA>,<NA>,...,438,170.75,170.53,170.7,170.58,438,<NA>,<NA>,<NA>,<NA>
2024-06-18 19:58:00,170.65,170.58,170.58,170.6,144,16884,<NA>,<NA>,<NA>,<NA>,...,442,170.65,170.59,170.59,170.62,442,<NA>,<NA>,<NA>,<NA>
2024-06-18 19:59:00,170.6,170.43,170.6,170.54,387,51823,<NA>,<NA>,<NA>,<NA>,...,1485,170.62,170.43,170.62,170.57,1485,<NA>,<NA>,<NA>,<NA>
2024-06-18 20:00:00,170.55,170.55,170.55,170.55,4,598495,<NA>,<NA>,<NA>,<NA>,...,9,170.57,170.55,170.57,170.55,9,<NA>,<NA>,<NA>,<NA>

### Historical Price Interday Summaries

Notice how the **Interval** has not been specified - so the request will use the default 'Daily' interval for the past 20 days

In [19]:
response = historical_pricing.summaries.Definition("IBM.N").get_data()
# Extract in DataFrame format
response.data.df

IBM.N,TRDPRC_1,HIGH_1,LOW_1,ACVOL_UNS,OPEN_PRC,BID,ASK,TRNOVR_UNS,VWAP,BLKCOUNT,BLKVOLUM,NUM_MOVES,TRD_STATUS,SALTIM
Date,,,,,,,,,,,,,,
2024-05-21,173.47,174.87,170.0,1384585,170.0,173.46,173.53,240098098,173.408,2,721029,9527,1,72600
2024-05-22,173.69,174.97,172.86,1144581,173.39,173.69,173.7,198788069,173.6776,2,690713,6484,1,72600
2024-05-23,170.67,175.39,170.44,1348696,175.39,170.71,170.72,230877520,171.1857,2,916253,6247,1,72600
2024-05-24,170.89,171.98,170.21,707031,171.48,170.91,170.95,120839586,170.9113,2,422078,4757,1,72600
2024-05-28,169.66,171.085,168.66,940554,170.44,169.71,169.72,159663325,169.7546,2,569100,5379,1,72600
2024-05-29,167.05,168.59,166.28,1472424,168.0,167.13,167.19,246278703,167.2607,2,932246,6543,1,72600
2024-05-30,165.63,166.71,164.23,1011264,165.85,165.68,165.73,167371673,165.5074,2,553205,6391,1,72600
2024-05-31,166.85,166.97,163.85,2246040,165.63,166.86,166.87,374238630,166.6215,3,1795666,6219,1,72600
2024-06-03,165.28,166.54,163.55,655582,166.54,165.29,165.36,102939923,165.235,2,364614,4572,1,72600
2024-06-04,165.81,166.37,164.0,867758,164.88,165.79,165.8,143806191,165.7215,2,598386,4505,1,72600
2024-06-05,167.38,167.77,165.82,1051457,166.41,167.38,167.39,175757552,167.1562,2,668019,5278,1,72600
2024-06-06,168.2,168.44,166.82,712208,167.52,168.2,168.21,119682924,168.0449,2,407007,3973,1,72600
2024-06-07,170.01,171.24,168.18,946515,168.18,170.03,170.06,160830796,169.9189,2,557998,5771,1,72600
2024-06-10,170.38,170.76,168.89,1297994,169.55,170.4,170.45,220932815,170.211,2,798136,7556,1,72600
2024-06-11,169.32,170.0,166.87,944940,169.98,169.3,169.31,159789691,169.1004,2,596177,5750,1,72600
2024-06-12,169.0,172.46,168.12,1049635,171.35,168.92,168.98,177721125,169.3171,2,656278,6883,1,72600
2024-06-13,169.12,169.59,168.36,1232060,169.01,169.02,169.03,208320002,169.0827,2,900933,4754,1,72600
2024-06-14,169.21,169.44,167.25,896479,168.29,169.21,169.22,151483970,168.9766,2,553090,4931,1,72600
2024-06-17,169.5,169.72,167.5,1158007,168.76,169.49,169.5,196054429,169.3033,2,745716,6078,1,72600
2024-06-18,170.55,170.74,168.39,1113462,170.0,170.54,170.55,189448578,170.1437,2,658374,6334,1,72600

### Historical Price Interday Summaries with some optional parameters  

Limit the response to past 20 days and also select a subset of the available fields

In [20]:
response = historical_pricing.summaries.Definition(
    universe = "VOD.L",
    interval = historical_pricing.Intervals.DAILY,          # Supported intervals: DAILY, WEEKLY, MONTHLY, QUARTERLY, YEARLY.
    count = 10,
    fields = ["BID", "ASK", "OPEN_PRC", "HIGH_1", "LOW_1", "TRDPRC_1", "NUM_MOVES", "TRNOVR_UNS"]
).get_data()
# Extract in DataFrame format
response.data.df

C:\Users\U6082174\AppData\Roaming\Python\Python311\site-packages\pandas\core\dtypes\cast.py:1057:RuntimeWarning: invalid value encountered in cast
C:\Users\U6082174\AppData\Roaming\Python\Python311\site-packages\pandas\core\dtypes\cast.py:1081:RuntimeWarning: invalid value encountered in cast

VOD.L,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2024-06-05,76.64,76.66,77.16,77.88,76.64,76.94,10339,6786344697.86
2024-06-06,72.2,72.22,72.98,72.98,71.52,72.2,11065,8664845548.49859
2024-06-07,71.5,71.52,72.18,72.66,71.48,71.52,6696,5164145494.53453
2024-06-10,70.86,70.88,70.96,71.94,70.5,70.96,7265,7875510266.63148
2024-06-11,70.1,70.12,71.24,71.4,69.86,70.1,7451,6436911296.54772
2024-06-12,69.0,69.06,70.12,70.48,69.0,69.24,8811,10628066140.638849
2024-06-13,68.7,68.72,68.84,69.54,68.62,68.84,7747,15301040088.32
2024-06-14,68.96,68.98,68.76,70.1,68.6,68.96,7636,4903335702.35417
2024-06-17,69.76,69.78,69.2,70.16,69.18,69.78,6336,6852732570.15413
2024-06-18,70.56,70.64,70.1,70.98,70.02,70.64,5368,4746706794.41771

### Handling invalid requests
When using the ***get_data()*** method, in case of a server error, an exception could be raised.   
For example, requesting an invalid RIC:

In [22]:
try:
    response = historical_pricing.events.Definition("BADRIC").get_data()
    print(response.data.df)
except ld.errors.LDError as e:
    print("Error code :", e.code)
    print("Error message:", e.message)

Error code : None
Error message: No data to return, please check errors: ERROR: No successful response.
(TS.Intraday.UserRequestError.90001, BADRIC - The universe is not found)

### Close the session

In [23]:
ld.close_session()