----
<div style="display: flex; align-items: center;">
    <img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="20%" style="vertical-align: top;">
    <h1 style="margin-left: 20px;">Data Library for Python</h1>
</div>

----

## Content - Search, Lookup and View Metadata
This notebook demonstrates how to utilise the Search API using the LSEG Data Platform OR via LSEG Eikon/Workspace.

For more details on the Search API refer to the following:

* The article, [Building Search into your Application Workflow](https://developers.lseg.com/en/article-catalog/article/building-search-into-your-application-workflow), provides an overview of the capabilities of the Search service including tips and tricks and many useful techniques.

## Set the location of the configuration file
For ease of use, you can set various initialization parameters of the RD Library in the **_lseg-data.config.json_** configuration file - as described in the Quick Start -> Sessions example.

### One config file for the tutorials
As these tutorial Notebooks are categorised into sub-folders and to avoid the need for multiple config files, we will use the _LD_LIB_CONFIG_PATH_ environment variable to point to a single instance of the config file in the top-level ***Configuration*** folder.

Before proceeding, please **ensure you have entered your credentials** into the config file in the ***Configuration*** folder.

In [1]:
import os
os.environ["LD_LIB_CONFIG_PATH"] = "../../../Configuration"

In [1]:
from lseg.data.content import search
import lseg.data as ld
import pandas as pd
import json

## Open the default session

To open the default session ensure you have a '*lseg-data.config.json*' in the ***Configuration*** directory, populated with your credentials and specified a 'default' session in the config file

In [2]:
ld.open_session()

#### General Search

In [3]:
response = search.Definition("IBM Bonds").get_data()
response.data.df

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",46638470074,0x00102cf964da067d,US137584123=
1,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",192826895881,0x00102c8de61f1850,US194445610=
2,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",46644611190,0x00102c00c0900d61,US161784508=
3,INSTRUMENTxFIXEDINCOMExGOVCORP,"Fideicomiso Fibra Uno, Plain Vanilla Fixed Cou...",44658934367,0x0004051cd9531a8d,FUNO15=
4,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",232796002153,0x00102cfffd953398,459200KS9=
5,INSTRUMENTxFIXEDINCOMExGOVCORP,"Fideicomiso Fibra Uno, Fixed Margin over Index...",232779066893,0x00102cb061232de3,FUNO212X=VALR
6,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",15628361579,0x0000fa00068e7c0e,459200AM3=
7,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",44652137828,0x00040514f83234eb,US099109963=
8,INSTRUMENTxFIXEDINCOMExGOVCORP,"Fideicomiso Fibra Uno, Plain Vanilla Fixed Cou...",46637470062,0x00102ca4794f05ab,MX133173986=
9,INSTRUMENTxFIXEDINCOMExGOVCORP,"Fideicomiso Fibra Uno, Plain Vanilla Fixed Cou...",46637469894,0x00102cb77c4f05bd,898324AC2=

#### Specify number of rows to fetch

In [4]:
response = search.Definition("IBM Bonds", top=100).get_data()
response.data.df

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",46638470074,0x00102cf964da067d,US137584123=
1,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",192826895881,0x00102c8de61f1850,US194445610=
2,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",46644611190,0x00102c00c0900d61,US161784508=
3,INSTRUMENTxFIXEDINCOMExGOVCORP,"Fideicomiso Fibra Uno, Plain Vanilla Fixed Cou...",44658934367,0x0004051cd9531a8d,FUNO15=
4,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",232796002153,0x00102cfffd953398,459200KS9=
...,...,...,...,...,...
95,INSTRUMENTxFIXEDINCOMExGOVCORP,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",15629030192,0x000386003ff1246f,<NA>
96,INSTRUMENTxFIXEDINCOMExGOVCORP,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",15628870427,0x000386001f82352d,<NA>
97,INSTRUMENTxFIXEDINCOMExGOVCORP,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",15628377011,0x0000fa000a004bbb,<NA>
98,INSTRUMENTxFIXEDINCOMExGOVCORP,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",15629030262,0x000386003ff16f24,<NA>
99,INSTRUMENTxFIXEDINCOMExGOVCORP,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",15629030258,0x000386003ff16b20,<NA>

#### Filter Expressions

In [5]:
response = search.Definition(
    view=search.Views.GOV_CORP_INSTRUMENTS,
    select="ISIN,RIC,IssueDate,Currency,FaceIssuedTotal,CouponRate,MaturityDate", 
    filter="IssuerTicker eq 'IBM' and IsActive eq true and AssetStatus ne 'MAT'"
).get_data()
response.data.df

,ISIN,RIC,IssueDate,Currency,FaceIssuedTotal,CouponRate,MaturityDate
0,XS1375841233,US137584123=,2016-03-07,EUR,750000000,1.125,2024-09-06
1,XS1944456109,US194445610=,2019-01-31,EUR,1000000000,0.875,2025-01-31
2,XS1617845083,US161784508=,2017-05-23,EUR,1000000000,0.95,2025-05-23
3,US459200KS93,459200KS9=,2022-07-27,USD,1000000000,4.0,2025-07-27
4,US459200AM34,459200AM3=,1995-10-30,USD,600000000,7.0,2025-10-30
5,XS0991099630,US099109963=,2013-11-07,EUR,1000000000,2.875,2025-11-07
6,US459200KW06,459200KW0=,2023-02-06,USD,850000000,4.5,2026-02-06
7,US459200JG74,459200JG7=,2016-02-19,USD,1350000000,3.45,2026-02-19
8,US459200JZ55,459200JZ5=,2019-05-15,USD,3000000000,3.3,2026-05-15
9,XS1512978112,US151297811=,2016-11-02,JPY,42000000000,0.3,2026-11-02

#### Properties - Metadata

In [6]:
response = search.metadata.Definition(
    view = search.Views.GOV_CORP_INSTRUMENTS  # Required parameterc
).get_data()

# for Pandas Display purpose only
pd.set_option("display.max_columns", None) 
pd.set_option("display.max_rows", 10)  # Just show 10 rows
pd.set_option("display.max_colwidth", 1)  

response.data.df

,,Type,Searchable,Sortable,Navigable,Groupable,Exact,Symbol
AccrualDate,AccrualDate,Date,True,True,True,False,False,False
AccruedInterest,AccruedInterest,Double,True,True,True,False,False,False
ActiveEstimatesExist,ActiveEstimatesExist,Boolean,True,False,False,False,False,False
AdtLocalCurrencyValue,AdtLocalCurrencyValue,String,True,False,False,False,False,False
AdtLocalCurrencyValueName,AdtLocalCurrencyValueName,String,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...
WorstStandardYield,WorstStandardYield,Double,True,True,True,False,False,False
WorstYearsToRedem,WorstYearsToRedem,Double,True,True,True,False,False,False
YieldCurveBenchmarkRIC,YieldCurveBenchmarkRIC,String,False,False,False,False,False,False
YieldTypeDescription,YieldTypeDescription,String,True,False,False,False,False,False
ZCodeValue,ZCodeValue,String,True,True,False,True,False,True

#### Navigators

In [7]:
response = search.Definition(
    top=10,
    navigators="RCSTRBC2012Leaf"
).get_data()

#### Response Data Structure

In [8]:
# Depending on the content type, the response can contain raw data and/or Dataframe format
# Let's check what this particular query returns.
if response.data.raw:
    display(response.data.raw)
else:
    print("Response does not contain raw data")    
# Check if the response contains a Dataframe too?
if (not response.data.df.empty):
    display(response.data.df)
else:
    print("\nResponse does not contain DataFrame")

{'Total': 152427118,
 'Hits': [{'BusinessEntity': 'QUOTExEQUITY',
   'DocumentTitle': 'OPRA Apple Equity Option 195 Call Jun 2024 , Equity Cash Option, Call 195 USD 21-Jun-2024, OPRA',
   'PermID': '21879741189',
   'PI': '592396111',
   'RIC': 'AAPLF212419500.U'},
  {'BusinessEntity': 'QUOTExEQUITY',
   'DocumentTitle': 'OPRA Apple Equity Option 200 Call Jun 2024 , Equity Cash Option, Call 200 USD 21-Jun-2024, OPRA',
   'PermID': '21879741128',
   'PI': '592396047',
   'RIC': 'AAPLF212420000.U'},
  {'BusinessEntity': 'QUOTExMONEY',
   'DocumentTitle': 'Guide to FX and Money Page (Speed Guide)',
   'PI': '1000226241',
   'RIC': 'MONEY'},
  {'BusinessEntity': 'QUOTExEQUITY',
   'DocumentTitle': 'OPRA Apple Equity Option 190 Call Jun 2024 , Equity Cash Option, Call 190 USD 21-Jun-2024, OPRA',
   'PermID': '21879740573',
   'PI': '592395493',
   'RIC': 'AAPLF212419000.U'},
  {'BusinessEntity': 'QUOTExEQUITY',
   'DocumentTitle': 'OPRA Apple Equity Option 195 Call Jul 2024 , Equity Cash Option, Call 195 USD 19-Jul-2024, OPRA',
   'PermID': '21999442055',
   'PI': '745679897',
   'RIC': 'AAPLG192419500.U'},
  {'BusinessEntity': 'QUOTExEQUITY',
   'DocumentTitle': 'OPRA Apple Equity Option 190 Call Jul 2024 , Equity Cash Option, Call 190 USD 19-Jul-2024, OPRA',
   'PermID': '21999153884',
   'PI': '745373691',
   'RIC': 'AAPLG192419000.U'},
  {'BusinessEntity': 'QUOTExEQUITY',
   'DocumentTitle': 'OPRA Apple Equity Option 185 Call Jun 2024 , Equity Cash Option, Call 185 USD 21-Jun-2024, OPRA',
   'PermID': '21879735589',
   'PI': '592390175',
   'RIC': 'AAPLF212418500.U'},
  {'BusinessEntity': 'QUOTExEQUITY',
   'DocumentTitle': 'OPRA Apple Equity Option 200 Call Jul 2024 , Equity Cash Option, Call 200 USD 19-Jul-2024, OPRA',
   'PermID': '21999457781',
   'PI': '745699409',
   'RIC': 'AAPLG192420000.U'},
  {'BusinessEntity': 'INSTRUMENTxINDEX',
   'DocumentTitle': 'FTSE 100 Index, Equity Index',
   'PermID': '232768448629',
   'PI': '272181',
   'RIC': '.FTSE'},
  {'BusinessEntity': 'QUOTExEQUITY',
   'DocumentTitle': 'OPRA Apple Equity Option 190 Put Jun 2024 , Equity Cash Option, Put 190 USD 21-Jun-2024, OPRA',
   'PermID': '21879735624',
   'PI': '592390221',
   'RIC': 'AAPLR212419000.U'}],
 'Navigators': {'RCSTRBC2012Leaf': {'Buckets': [{'Label': 'Banks (NEC)',
     'Count': 5726685},
    {'Label': 'Corporate Financial Services (NEC)', 'Count': 3029424},
    {'Label': 'Corporate Banks', 'Count': 1666316},
    {'Label': 'Retail & Mortgage Banks', 'Count': 1564869},
    {'Label': 'Investment Banking & Brokerage Services (NEC)',
     'Count': 1014194},
    {'Label': 'Government & Government Finance (NEC)', 'Count': 745262},
    {'Label': 'Public Finance Activities', 'Count': 579100},
    {'Label': 'Construction & Engineering (NEC)', 'Count': 562997},
    {'Label': 'Investment Holding Companies (NEC)', 'Count': 491935},
    {'Label': 'Business Support Services (NEC)', 'Count': 488505},
    {'Label': 'Investment Banking', 'Count': 486195},
    {'Label': 'Electric Utilities (NEC)', 'Count': 459314},
    {'Label': 'Consumer Lending (NEC)', 'Count': 420218},
    {'Label': 'Real Estate Rental, Development & Operations (NEC)',
     'Count': 405470},
    {'Label': 'Wealth Management', 'Count': 405125},
    {'Label': 'Supermarkets & Convenience Stores', 'Count': 394605},
    {'Label': 'Diversified Investment Services', 'Count': 360764},
    {'Label': 'Building Contractors', 'Count': 299312},
    {'Label': 'Investment Management & Fund Operators (NEC)', 'Count': 282341},
    {'Label': 'Professional Information Services (NEC)', 'Count': 272378},
    {'Label': 'Software (NEC)', 'Count': 257121},
    {'Label': 'IT Services & Consulting (NEC)', 'Count': 239630},
    {'Label': 'Department Stores (NEC)', 'Count': 224953},
    {'Label': 'Shell Companies', 'Count': 209476},
    {'Label': 'Management Consulting Services', 'Count': 208046},
    {'Label': 'Auto Vehicles, Parts & Service Retailers (NEC)',
     'Count': 200875},
    {'Label': 'Real Estate Services (NEC)', 'Count': 190107},
    {'Label': 'Hospitals, Clinics & Primary Care Services', 'Count': 167495},
    {'Label': 'Pharmaceuticals (NEC)', 'Count': 151713},
    {'Label': 'Investment Management', 'Count': 150464},
    {'Label': 'Integrated Telecommunications Services (NEC)', 'Count': 143036},
    {'Label': 'Homebuilding (NEC)', 'Count': 137179},
    {'Label': 'Industrial Machinery & Equipment (NEC)', 'Count': 125649},
    {'Label': 'Commodity Chemicals (NEC)', 'Count': 125272},
    {'Label': 'Miscellaneous Educational Service Providers', 'Count': 120550},
    {'Label': 'Brokerage Services', 'Count': 119294},
    {'Label': 'Food Processing (NEC)', 'Count': 118987},
    {'Label': 'Metal Merchant Wholesale', 'Count': 116864},
    {'Label': 'Government Administration Activities', 'Count': 114819},
    {'Label': 'Oil & Gas Exploration and Production (NEC)', 'Count': 111518},
    {'Label': 'Restaurants & Bars (NEC)', 'Count': 110723},
    {'Label': 'Construction Materials (NEC)', 'Count': 109495},
    {'Label': 'Financial & Commodity Market Operators & Service Providers (NEC)',
     'Count': 108367},
    {'Label': 'Auto, Truck & Motorcycle Parts (NEC)', 'Count': 106248},
    {'Label': 'Residential Builders - Single Homes', 'Count': 104141},
    {'Label': 'Residential Real Estate Rental & Development', 'Count': 101528},
    {'Label': 'Commercial Loans', 'Count': 99905},
    {'Label': 'Healthcare Facilities & Services (NEC)', 'Count': 99372},
    {'Label': 'Insurance Brokers', 'Count': 94381},
    {'Label': 'Metallic Rolling & Drawing Products', 'Count': 90192},
    {'Label': 'Highway & Bridge Construction', 'Count': 89954},
    {'Label': 'Personal Services (NEC)', 'Count': 88060},
    {'Label': 'Biotechnology & Medical Research (NEC)', 'Count': 84413},
    {'Label': 'Electrical Components & Equipment (NEC)', 'Count': 84357},
    {'Label': 'UK Investment Trusts', 'Count': 83585},
    {'Label': 'Office Real Estate Rental & Development', 'Count': 83182},
    {'Label': 'Multiline Utilities', 'Count': 83107},
    {'Label': 'Metal Service Centers', 'Count': 82534},
    {'Label': 'Industrial Machinery', 'Count': 79487},
    {'Label': 'Plastics', 'Count': 75526},
    {'Label': 'Gasoline Stations', 'Count': 75479},
    {'Label': 'Hotels & Motels', 'Count': 74578},
    {'Label': 'Freight Trucking', 'Count': 70904},
    {'Label': 'Closed End Funds', 'Count': 69553},
    {'Label': 'Iron & Steel (NEC)', 'Count': 68790},
    {'Label': 'Online Services (NEC)', 'Count': 67982},
    {'Label': 'Life & Health Insurance (NEC)', 'Count': 67702},
    {'Label': 'Drug Retailers (NEC)', 'Count': 66511},
    {'Label': "Doctor's Office", 'Count': 65846},
    {'Label': 'Advertising & Marketing (NEC)', 'Count': 64725},
    {'Label': 'Passenger Transportation, Ground & Sea (NEC)', 'Count': 64019},
    {'Label': 'Leisure & Recreation (NEC)', 'Count': 61893},
    {'Label': 'Plumbing Fixtures & Fittings', 'Count': 59965},
    {'Label': 'Natural Gas Distribution', 'Count': 59662},
    {'Label': 'Waste Management, Disposal & Recycling Services',
     'Count': 58418},
    {'Label': 'Integrated Oil & Gas', 'Count': 58392},
    {'Label': 'Civil Engineers & Architects', 'Count': 58388},
    {'Label': 'Maintenance & Repair Services', 'Count': 58292},
    {'Label': 'Consumer Goods Conglomerates', 'Count': 58161},
    {'Label': 'Diversified Industrial Goods Wholesale', 'Count': 57815},
    {'Label': 'Iron, Steel Mills & Foundries', 'Count': 57450},
    {'Label': 'Diversified Mining', 'Count': 56136},
    {'Label': 'Legal Services', 'Count': 55004},
    {'Label': 'Chocolate & Confectionery', 'Count': 54325},
    {'Label': 'Hedge Funds', 'Count': 53796},
    {'Label': 'Commercial Buildings', 'Count': 53673},
    {'Label': 'Grain (Crop) Production', 'Count': 53148},
    {'Label': 'Cement & Concrete Manufacturing', 'Count': 53086},
    {'Label': 'Employment Services (NEC)', 'Count': 52386},
    {'Label': 'Personal Products (NEC)', 'Count': 51393},
    {'Label': 'Specialty Mining & Metals (NEC)', 'Count': 51288},
    {'Label': 'Freight Logistics', 'Count': 50983},
    {'Label': 'Medical Equipment, Supplies & Distribution (NEC)',
     'Count': 50873},
    {'Label': 'Coal (NEC)', 'Count': 50566},
    {'Label': 'Oil & Gas Transportation Services (NEC)', 'Count': 49988},
    {'Label': 'Petroleum Refining', 'Count': 49940},
    {'Label': 'Oil & Gas Refining and Marketing (NEC)', 'Count': 49707},
    {'Label': 'Child Care & Family Services', 'Count': 48095},
    {'Label': 'Industrial Equipment Rental', 'Count': 46889},
    {'Label': 'Vegetable, Fruit & Nut Farming', 'Count': 46171}]}}}

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,QUOTExEQUITY,"OPRA Apple Equity Option 195 Call Jun 2024 , Equity Cash Option, Call 195 USD 21-Jun-2024, OPRA",21879741189,592396111,AAPLF212419500.U
1,QUOTExEQUITY,"OPRA Apple Equity Option 200 Call Jun 2024 , Equity Cash Option, Call 200 USD 21-Jun-2024, OPRA",21879741128,592396047,AAPLF212420000.U
2,QUOTExMONEY,Guide to FX and Money Page (Speed Guide),<NA>,1000226241,MONEY
3,QUOTExEQUITY,"OPRA Apple Equity Option 190 Call Jun 2024 , Equity Cash Option, Call 190 USD 21-Jun-2024, OPRA",21879740573,592395493,AAPLF212419000.U
4,QUOTExEQUITY,"OPRA Apple Equity Option 195 Call Jul 2024 , Equity Cash Option, Call 195 USD 19-Jul-2024, OPRA",21999442055,745679897,AAPLG192419500.U
5,QUOTExEQUITY,"OPRA Apple Equity Option 190 Call Jul 2024 , Equity Cash Option, Call 190 USD 19-Jul-2024, OPRA",21999153884,745373691,AAPLG192419000.U
6,QUOTExEQUITY,"OPRA Apple Equity Option 185 Call Jun 2024 , Equity Cash Option, Call 185 USD 21-Jun-2024, OPRA",21879735589,592390175,AAPLF212418500.U
7,QUOTExEQUITY,"OPRA Apple Equity Option 200 Call Jul 2024 , Equity Cash Option, Call 200 USD 19-Jul-2024, OPRA",21999457781,745699409,AAPLG192420000.U
8,INSTRUMENTxINDEX,"FTSE 100 Index, Equity Index",232768448629,272181,.FTSE
9,QUOTExEQUITY,"OPRA Apple Equity Option 190 Put Jun 2024 , Equity Cash Option, Put 190 USD 21-Jun-2024, OPRA",21879735624,592390221,AAPLR212419000.U

As you will see the above response contained both raw data and a Dataframe   

#### Search with Navigator option

In [9]:
response = search.Definition(
    view=search.Views.COMMODITY_QUOTES,
    query="cheese",
    navigators="ExchangeName"
).get_data()

response.data.df

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,QUOTExCOMMODITY,"CME Cash Settled Cheese Electronic Commodity Future Continuation 1, Commodity Future, Chicago Mercantile Exchange",21622940491,273610776,CSCc1
1,QUOTExCOMMODITY,"CME Cash Settled Cheese Electronic Commodity Future Chain Chain Contracts, Commodity Future, Chicago Mercantile Exchange",21622425217,272623267,0#CSC:
2,QUOTExCOMMODITY,"CME Cash Settled Cheese Electronic Commodity Future Jul 2024, Commodity Future, Chicago Mercantile Exchange",21909537890,628553925,CSCN24
3,QUOTExCOMMODITY,"CME Cash Settled Cheese Electronic Commodity Future Continuation 2, Commodity Future, Chicago Mercantile Exchange",21622940494,273610782,CSCc2
4,QUOTExCOMMODITY,"CME Cash Settled Cheese Electronic Commodity Future Continuation 3, Commodity Future, Chicago Mercantile Exchange",21622940497,273610784,CSCc3
5,QUOTExCOMMODITY,"CME Cash Settled Cheese Electronic Commodity Future Aug 2024, Commodity Future, Chicago Mercantile Exchange",21915186698,635366864,CSCQ24
6,QUOTExCOMMODITY,"CME Cash Settled Cheese Electronic Commodity Future Jun 2024, Commodity Future, Chicago Mercantile Exchange",21902231392,619841775,CSCM24
7,QUOTExCOMMODITY,"CME Cash Settled Cheese Electronic Commodity Future Nov 2024, Commodity Future, Chicago Mercantile Exchange",21934325409,658555795,CSCX24
8,QUOTExCOMMODITY,"CME Cash Settled Cheese Electronic Commodity Future Dec 2024, Commodity Future, Chicago Mercantile Exchange",21941309049,666775593,CSCZ24
9,QUOTExCOMMODITY,"CME Cash Settled Cheese Electronic Commodity Future Continuation 14, Commodity Future, Chicago Mercantile Exchange",21622940525,273610812,CSCc14

In [10]:
response.data.raw["Navigators"]['ExchangeName']

{'Buckets': [{'Label': 'CME:Index and Options Market', 'Count': 17503},
  {'Label': 'Chicago Mercantile Exchange', 'Count': 3107},
  {'Label': 'Source is a Refinitiv Contributor', 'Count': 2979},
  {'Label': 'INTL FCStone Inc', 'Count': 2550},
  {'Label': 'US Department of Agriculture', 'Count': 103},
  {'Label': 'Commodity Futures Trading Commission', 'Count': 66},
  {'Label': 'Complete Intelligence', 'Count': 65},
  {'Label': 'Intercontinental Exchange US', 'Count': 31},
  {'Label': 'US Bureau Of Labor Statistics', 'Count': 10},
  {'Label': 'DCA Markets B.V. - DCA-Markets-PRA Price Reporting Agent',
   'Count': 4},
  {'Label': 'European Commission', 'Count': 3},
  {'Label': 'ESALQ', 'Count': 2},
  {'Label': 'Refinitiv', 'Count': 2},
  {'Label': 'CME:International Monetary Market', 'Count': 1}]}

In [11]:
response = search.Definition(
    view=search.Views.GOV_CORP_INSTRUMENTS,
    top=0,
    navigators="Currency(buckets:10,desc:sum_FaceOutstandingUSD,calc:max_CouponRate)"
).get_data()

response.data.raw

{'Total': 12020686,
 'Hits': [],
 'Navigators': {'Currency': {'Buckets': [{'Label': 'USD',
     'Count': 4508881,
     'max_CouponRate': 1800.0,
     'sum_FaceOutstandingUSD': 55196132701262.0},
    {'Label': 'EUR',
     'Count': 1256047,
     'max_CouponRate': 999.999999,
     'sum_FaceOutstandingUSD': 27146298312943.0},
    {'Label': 'CNY',
     'Count': 441006,
     'max_CouponRate': 72.0,
     'sum_FaceOutstandingUSD': 22470416566666.0},
    {'Label': 'JPY',
     'Count': 519465,
     'max_CouponRate': 999.999999,
     'sum_FaceOutstandingUSD': 9893427015102.0},
    {'Label': 'GBP',
     'Count': 240812,
     'max_CouponRate': 999.999999,
     'sum_FaceOutstandingUSD': 5049204852592.0},
    {'Label': 'INR',
     'Count': 132551,
     'max_CouponRate': 42.75,
     'sum_FaceOutstandingUSD': 2870521107552.0},
    {'Label': 'CAD',
     'Count': 368469,
     'max_CouponRate': 100.0,
     'sum_FaceOutstandingUSD': 2674787582509.0},
    {'Label': 'KRW',
     'Count': 445081,
     'max_CouponRate': 48.0,
     'sum_FaceOutstandingUSD': 2399248286180.0225},
    {'Label': 'AUD',
     'Count': 188504,
     'max_CouponRate': 999.999999,
     'sum_FaceOutstandingUSD': 1742554611109.0},
    {'Label': 'BRL',
     'Count': 102139,
     'max_CouponRate': 999.999999,
     'sum_FaceOutstandingUSD': 1139952604832.8337}]}}}

#### Sub-navigator

In [12]:
response = search.Definition(
    view=search.Views.PEOPLE,
    top=0,
    navigators="FirstName(buckets:3,sub:LastName(buckets:2))"
).get_data()

response.data.raw["Navigators"]["FirstName"]["Buckets"]

[{'Label': 'John',
  'Count': 45127,
  'LastName': {'Buckets': [{'Label': 'Smith', 'Count': 122},
    {'Label': 'Wilson', 'Count': 118}]}},
 {'Label': 'David',
  'Count': 44947,
  'LastName': {'Buckets': [{'Label': 'Smith', 'Count': 259},
    {'Label': 'Brown', 'Count': 184}]}},
 {'Label': 'Michael',
  'Count': 43348,
  'LastName': {'Buckets': [{'Label': 'Smith', 'Count': 205},
    {'Label': 'Brown', 'Count': 148}]}}]

#### Search with order_by option

In [13]:
response = search.Definition(
    view=search.Views.PEOPLE,
    query="ceo",
    order_by="YearOfBirth desc,LastName,FirstName",
    select="YearOfBirth,DocumentTitle"
).get_data()

response.data.df

,YearOfBirth,DocumentTitle
0,1997,"Carl Fredrik Mikael Akerman - VOLTA GREENTECH AB - Chairman of the Board, Chief Executive Officer"
1,1997,"Martins Balodis - Facing It International - Chief Executive Officer, Director"
2,1997,"David Samuel Haloho - David Sistem Group PT - Chief Executive Officer, Founder"
3,1997,"Rishi Tandon - Creative Casuals (India) Pvt Ltd - Chief Executive Officer, Director"
4,1996,"Senthil Nathan Abishiek - Acsen Tex Pvt Ltd - Chief Executive Officer, Whole-Time Director (Promoter)"
5,1996,"Mitchell Babalola Christopher Fasanya - Searchland Ltd - Chief Executive Officer, Founder"
6,1996,Ethan Fraenkel - Prograd uk Inc - Chief Executive Officer
7,1996,"Kazuki Fujii - Ileo Co Ltd - Chief Executive Officer, Representative Director"
8,1996,Elliot Alexander Garreffa - Oasiis Ltd - Chief Executive Officer
9,1996,"Ivan Liljeqvist - Moralis Web3 Technology AB - Chief Executive Officer, Director"

#### Search with group_by option

In [14]:
response = search.Definition(
    view=search.Views.INDICATOR_QUOTES,
    query="rate",
    group_by="CentralBankName",
    group_count=2,
    select="CentralBankName,DocumentTitle,RIC"
).get_data()

response.data.df

,CentralBankName,DocumentTitle,RIC
0,Federal Reserve System,"United States, Policy Rates, Fed Funds Target Rate, Reuters Polls, Daily, The Federal Open Market Committee",USFOMC=ECI
1,Federal Reserve System,"United States, Policy Rates, Fed Overnight Repo, Reuters Polls, Daily, Federal Reserve, United States",USRRP=ECI
2,Bank of England,"United Kingdom, Policy Rates, Bank Rate, Reuters Polls, Monthly, Bank of England",GBBOEI=ECI
3,Bank of England,"United Kingdom, BOE Bank Rate (Quarterly)-Mean, Long-Term Outlook, Quarterly, Reuters",pGBBASEQP=E
4,European Central Bank,"Euro Zone, Policy Rates, ECB Main refinancing, Fixed Rate (Announcement Dates), Reuters Polls, Monthly, ECB - European Central Bank",EUECBR=ECI
5,European Central Bank,"Euro Zone, Policy Rates, ECB Deposit Rate, Reuters Polls, Monthly, ECB - European Central Bank",EUECBD=ECI
6,Central Bank of Egypt,"Egypt, Policy Rates, Overnight Deposit Rate, Reuters Polls, Daily, Central Bank of Egypt",EGINTR=ECI
7,Central Bank of Egypt,"Egypt, Policy Rates, Overnight Lending Rate, Reuters Polls, Daily, Central Bank of Egypt",EGCBIR=ECI
8,Banca Nationala a Romaniei,"Romania, Policy Rates, Policy Rate, Reuters Polls, Daily, National Bank of Romania",ROINTR=ECI
9,Banca Nationala a Romaniei,"Romania, Mon Policy Rate-Sest, Reuters Polls, Daily, StarMine",pROINTR=F

#### Search For People

In [15]:
response = search.Definition(
    query="cfo",
    view=search.Views.PEOPLE
).get_data()

response.data.df

,BusinessEntity,DocumentTitle,PermID,PI
0,PERSON,"Amy E. Hood - Microsoft Corp - Chief Financial Officer, Executive Vice President",34415553383,34415553383
1,PERSON,"Luca Maestri - Apple Inc - Chief Financial Officer, Senior Vice President",34414554748,34414554748
2,PERSON,"Brian T. Olsavsky - Amazon.com Inc - Senior Vice President, Chief Financial Officer",34417610894,34417610894
3,PERSON,"Ruth M. Porat - Alphabet Inc - President, Chief Financial Officer, Chief Investment Officer and Senior Vice President of Alphabet and Google",34413960665,34413960665
4,PERSON,Susan J. Li - Meta Platforms Inc - Chief Financial Officer,34424688603,34424688603
5,PERSON,"Marc D. Hamburg - Berkshire Hathaway Inc - Chief Financial Officer, Senior Vice President",34413152672,34413152672
6,PERSON,Andrew K. Klatt - Berkshire Hathaway Inc - CFO & COO,34414966250,34414966250
7,PERSON,Xu Hong - Alibaba Group Holding Ltd - Chief Financial Officer,34425652371,34425652371
8,PERSON,"John Lo - Tencent Holdings Ltd - Chief Financial Officer, Senior Vice President",34414907131,34414907131
9,PERSON,"Joseph J. Wolk - Johnson & Johnson - Chief Financial Officer, Executive Vice President",34422069022,34422069022

### Lookup

In [16]:
response = search.lookup.Definition(
    view=search.Views.INSTRUMENTS,
    scope="RIC",
    terms="MSFT.O,AAPL.O,GOOG.O,IBM.N,KBANK.BK,SCC.BK",
    select="BusinessEntity,DocumentTitle,CUSIP,SEDOL",
).get_data()

response.data.df

,BusinessEntity,DocumentTitle,CUSIP,SEDOL
MSFT.O,INSTRUMENTxEQUITY,"Microsoft Corp, Ordinary Share",594918104,<NA>
AAPL.O,INSTRUMENTxEQUITY,"Apple Inc, Ordinary Share",037833100,<NA>
GOOG.O,INSTRUMENTxEQUITY,"Alphabet Inc, Ordinary Share",02079K107,<NA>
KBANK.BK,INSTRUMENTxEQUITY,"Kasikornbank PCL, Ordinary Share",<NA>,6888783
SCC.BK,INSTRUMENTxEQUITY,"Siam Cement PCL, Ordinary Share",<NA>,6609917

In [17]:
response = search.lookup.Definition(
    view=search.Views.SEARCH_ALL,
    scope="RIC",
    terms="A,B,NOSUCHRIC,C,D",
    select="BusinessEntity,DocumentTitle",
).get_data()

response.data.df

  BusinessEntity                                                DocumentTitle
A  QUOTExEQUITY   Agilent Technologies Inc, Ordinary Share, NYSE Consolidated
B  QUOTExEQUITY   Barnes Group Inc, Ordinary Share, NYSE Consolidated
C  QUOTExEQUITY   Citigroup Inc, Ordinary Share, NYSE Consolidated
D  QUOTExEQUITY   Dominion Energy Inc, Ordinary Share, NYSE Consolidated

## Close the session

In [18]:
ld.close_session()