----
<img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="20%" style="vertical-align: top;">

# Data Library for Python

----

## Content layer - News
This notebook demonstrates how to retrieve News.

#### Learn more

To learn more about the Refinitiv Data Library for Python please join the Refinitiv Developer Community. By [registering](https://developers.refinitiv.com/iam/register) and [logging](https://developers.refinitiv.com/content/devportal/en_us/initCookie.html) into the Refinitiv Developer Community portal you will have free access to a number of learning materials like 
 [Quick Start guides](https://developers.refinitiv.com/en/api-catalog/refinitiv-data-platform/refinitiv-data-library-for-python/quick-start), 
 [Tutorials](https://developers.refinitiv.com/en/api-catalog/refinitiv-data-platform/refinitiv-data-library-for-python/learning), 
 [Documentation](https://developers.refinitiv.com/en/api-catalog/refinitiv-data-platform/refinitiv-data-library-for-python/docs)
 and much more.

#### Getting Help and Support

If you have any questions regarding using the API, please post them on 
the [Refinitiv Data Q&A Forum](https://community.developers.refinitiv.com/spaces/321/index.html). 
The Refinitiv Developer Community will be happy to help.

## Set the configuration file location
For a better ease of use, you have the option to set initialization parameters of the Refinitiv Data Library in the _refinitiv-data.config.json_ configuration file. This file must be located beside your notebook, in your user folder or in a folder defined by the _LD_LIB_CONFIG_PATH_ environment variable. The _LD_LIB_CONFIG_PATH_ environment variable is the option used by this series of examples. The following code sets this environment variable.

In [1]:
import os
os.environ["LD_LIB_CONFIG_PATH"] = "../../../Configuration"

## Some Imports to start with

In [2]:
import lseg.data as ld
from lseg.data.content import news
from datetime import timedelta
from IPython.display import HTML
import pandas as pd
pd.options.display.max_colwidth = 100

## Open the data session

The open_session() function creates and open sessions based on the information contained in the refinitiv-data.config.json configuration file. Please edit this file to set the session type and other parameters required for the session you want to open.

In [ ]:
ld.open_session(name="platform.ldp")

## Retrieve data

### Headlines

#### Get headlines

In [4]:
response = news.headlines.Definition("Apple").get_data()
response.data.df

,headline,storyId,sourceCode
versionCreated,,,
2025-03-10 13:45:54.143,"DJ Boeing, Apple Share Losses Lead Dow's 339-Point Drop",urn:newsml:reuters.com:20250310:nDJR1LkmP1:1,NS:MKTW
2025-03-10 13:45:54.111,"DJ Boeing, Apple Share Losses Lead Dow's 339-Point Drop",urn:newsml:reuters.com:20250310:nDJRbRJgxf:1,NS:DJN
2025-03-10 13:45:00.000,"DJ Boeing, Apple Share Losses Lead Dow's 339-Point Drop",urn:newsml:reuters.com:20250310:nDjcbRJgxf:1,NS:DJCP
2025-03-10 13:39:51.550,"Apple MacBook Air M3 and M2 discontinued, but you can still buy them-should you?",urn:newsml:reuters.com:20250310:nNRAvo7eq8:1,NS:HINDUT
2025-03-10 13:31:25.959,3D printed logos of Apple and Google are pictured on a keyboard in front of binary code in this ...,urn:newsml:reuters.com:20250310:nLPK3GSQgD:1,NS:RTRS
2025-03-10 13:25:48.837,"DJ Apple's Delayed Siri AI Upgrade Could Hit iPhone Sales, Citi Says -- Barrons.com",urn:newsml:reuters.com:20250310:nDJR10pHZG:2,NS:DJN
2025-03-10 13:25:48.833,"DJ Apple's Delayed Siri AI Upgrade Could Hit iPhone Sales, Citi Says -- Barrons.com",urn:newsml:reuters.com:20250310:nDJR1xpGFC:2,NS:BRN
2025-03-10 13:25:00.000,"DJ Apple's Delayed Siri AI Upgrade Could Hit iPhone Sales, Citi Says -- Barrons.com",urn:newsml:reuters.com:20250310:nDjc10pHZG:2,NS:DJCP
2025-03-10 13:14:07.444,Serbia's Tehnomanija buys Bosnian authorised reseller for Apple Macline,urn:newsml:reuters.com:20250310:nSEEdvnHva:1,NS:SEE
2025-03-10 13:00:00.452,<日経>◇新型iPad Air 発売、Apple Intelligenceは4月に日本語対応,urn:newsml:reuters.com:20250310:nQCKYLBGB:1,NS:QUICK

#### Get headlines within a range of dates

In [5]:
response = news.headlines.Definition(
    query="Refinitiv",
    date_from="20.03.2021", 
    date_to=timedelta(days=-4), 
    count=3
).get_data()
response.data.df

,headline,storyId,sourceCode
versionCreated,,,
2025-03-06 06:13:34.080,AWPTOP French News - urn:newsml:refinitiv.com:20200301:AWP_TN_DOC_2020030102:20212,urn:newsml:reuters.com:20250305:nATP2Frenh:20212,NS:AWP
2025-03-06 06:13:34.076,AWPTOP German News - urn:newsml:refinitiv.com:20200301:AWP_TN_DOC_2020030101:20212,urn:newsml:reuters.com:20250305:nATP1Germn:20212,NS:AWP
2025-03-05 07:28:25.311,AWPTOP French News - urn:newsml:refinitiv.com:20200301:AWP_TN_DOC_2020030102:20110,urn:newsml:reuters.com:20250304:nATP2Frenh:1,NS:AWP

#### Get a limited number of headlines

In [6]:
response = news.headlines.Definition(query = "Google", count = 350).get_data()
response.data.df

,headline,storyId,sourceCode
versionCreated,,,
2025-03-10 13:31:25.959,3D printed logos of Apple and Google are pictured on a keyboard in front of binary code in this ...,urn:newsml:reuters.com:20250310:nLPK3GSQgD:1,NS:RTRS
2025-03-10 13:01:37.039,DJ IBD: Wall Street Hopes For Trump-Google Antitrust Deal Take A Blow,urn:newsml:reuters.com:20250310:nDJR1GpVVK:1,NS:IBD
2025-03-10 13:01:36.999,DJ Wall Street Hopes For Trump-Google Antitrust Deal Take A Blow -- IBD,urn:newsml:reuters.com:20250310:nDJR8rmBKm:2,NS:DJN
2025-03-10 13:01:00.000,DJ Wall Street Hopes For Trump-Google Antitrust Deal Take A Blow -- IBD,urn:newsml:reuters.com:20250310:nDjc8rmBKm:2,NS:DJCP
2025-03-10 12:25:00.035,PureCars Has Been Named a 2025 Google Premier Partner,urn:newsml:reuters.com:20250310:nGNX5Q3LbB:1,NS:GNW
...,...,...,...
2025-02-28 09:06:49.419,Teachmint Launches Teachmint X2- Google EDLA Certified AI Interactive Flat Panel,urn:newsml:reuters.com:20250228:nNRAvkj7jz:1,NS:ASNEWS
2025-02-28 08:36:30.751,Google skär ner inom HR och molntjänster för att minska kostnader,urn:newsml:reuters.com:20250228:nFNW2Bsp6:1,NS:FNW
2025-02-28 07:32:09.918,DJ Google Tweak Stings Product-Review Sites -- WSJ,urn:newsml:reuters.com:20250228:nDJRbmHqGm:1,NS:WSJ
2025-02-28 07:32:09.903,DJ Google Tweak Stings Product-Review Sites -- WSJ,urn:newsml:reuters.com:20250228:nDJR90kt59:1,NS:DJN
2025-02-28 07:32:00.000,DJ Google Tweak Stings Product-Review Sites -- WSJ,urn:newsml:reuters.com:20250228:nDjc90kt59:1,NS:DJCP

### Story

In [7]:
response = news.story.Definition("urn:newsml:reuters.com:20240613:nPn5fJxGba:1").get_data()
print(response.data.story.title, '\n')
HTML(response.data.story.content.html)

Cognizant Launches First Set Of Healthcare Large Language Model Solutions As Part Of Generative AI Partnership With Google Cloud

## Extended Params

In [ ]:
response = news.headlines.Definition(
    query="",
    date_from="01.01.2025", 
    # date_to=timedelta(days=-4), 
    count=3,
    extended_params={
        "Source": "(    [Reuters News] OR [Dow Jones News Service] OR [LSEG Commodities Research & Forecast]    )   AND (  [Grains]   )"}
).get_data()
response.data.df

,headline,storyId,sourceCode
versionCreated,,,
2025-03-10 13:51:40.423,Commodities - urn:newsml:reuters.com:20060719:SPDOC_116716192006:178443,urn:newsml:reuters.com:20250310:nLPK86p2Kv:1,NS:RTRS
2025-03-10 13:51:40.417,SmartPageGroupDefinition.xml - urn:newsml:reuters.com:20060719:SPDOC_116709192006:173848,urn:newsml:reuters.com:20250310:nLPK6152CP:1,NS:RTRS
2025-03-10 13:51:40.374,Commodities - urn:newsml:reuters.com:20060119:SPDOC_28769192006:195020,urn:newsml:reuters.com:20250310:nLPK5qgwH3:195020,NS:RTRS

## Close the session

In [9]:
ld.close_session()