----
<img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="20%" style="vertical-align: top;">

# Data Library for Python

----

## Content layer - News
This notebook demonstrates how to retrieve News.

#### Learn more

To learn more about the Refinitiv Data Library for Python please join the Refinitiv Developer Community. By [registering](https://developers.refinitiv.com/iam/register) and [logging](https://developers.refinitiv.com/content/devportal/en_us/initCookie.html) into the Refinitiv Developer Community portal you will have free access to a number of learning materials like 
 [Quick Start guides](https://developers.refinitiv.com/en/api-catalog/refinitiv-data-platform/refinitiv-data-library-for-python/quick-start), 
 [Tutorials](https://developers.refinitiv.com/en/api-catalog/refinitiv-data-platform/refinitiv-data-library-for-python/learning), 
 [Documentation](https://developers.refinitiv.com/en/api-catalog/refinitiv-data-platform/refinitiv-data-library-for-python/docs)
 and much more.

#### Getting Help and Support

If you have any questions regarding using the API, please post them on 
the [Refinitiv Data Q&A Forum](https://community.developers.refinitiv.com/spaces/321/index.html). 
The Refinitiv Developer Community will be happy to help.

## Set the configuration file location
For a better ease of use, you have the option to set initialization parameters of the Refinitiv Data Library in the _refinitiv-data.config.json_ configuration file. This file must be located beside your notebook, in your user folder or in a folder defined by the _LD_LIB_CONFIG_PATH_ environment variable. The _LD_LIB_CONFIG_PATH_ environment variable is the option used by this series of examples. The following code sets this environment variable.

In [1]:
import os
os.environ["LD_LIB_CONFIG_PATH"] = "../../../Configuration"

## Some Imports to start with

In [2]:
import lseg.data as ld
from lseg.data.content import news
from datetime import timedelta
from IPython.display import HTML
import pandas as pd
pd.options.display.max_colwidth = 100

## Open the data session

The open_session() function creates and open sessions based on the information contained in the refinitiv-data.config.json configuration file. Please edit this file to set the session type and other parameters required for the session you want to open.

In [3]:
ld.open_session(name='platform.ldp')

## Retrieve data

### Headlines

#### Get headlines

In [4]:
response = news.headlines.Definition("Apple").get_data()
response.data.df

,headline,storyId,sourceCode
versionCreated,,,
2024-06-13 12:32:31.364,Apple says long-awaited AI will set new privacy standards – but experts are divided,urn:newsml:reuters.com:20240613:nNRAsyeza1:1,NS:THEGRD
2024-06-13 12:19:11.116,"The Zacks Analyst Blog Highlights Microsoft,Apple Alphabet and CompX International",urn:newsml:reuters.com:20240613:nNRAsyhw2m:1,NS:ZACKSC
2024-06-13 12:03:19.000,LIVE MARKETS-Musk's pay battle echoes Steve Jobs and Apple in '80s,urn:newsml:reuters.com:20240613:nL4N3IB0YX:3,NS:RTRS
2024-06-13 11:32:37.225,"The Zacks Analyst Blog Highlights NVIDIA, Apple, Netflix and Broadcom",urn:newsml:reuters.com:20240613:nNRAsygv3j:1,NS:ZACKSC
2024-06-13 11:14:59.718,<日経>◇米アファーム株上昇 決済サービスのApple Pay導入で,urn:newsml:reuters.com:20240613:nQCK5H7yHt:2,NS:QUICK
2024-06-13 11:12:27.907,"Apple Watch can detect symptoms of Parkinson's disease, study reveals",urn:newsml:reuters.com:20240613:nNRAsygmnn:1,NS:INDEPE
2024-06-13 10:32:08.930,"Tim Cook explains why Apple calls its AI Apple Intelligence, says decision was user-driven",urn:newsml:reuters.com:20240613:nNRAsyg5m5:1,NS:INDIAE
2024-06-13 10:21:11.859,"After EU, Apple could be forced to open ecosystem in Japan, India: Report",urn:newsml:reuters.com:20240613:nNRAsyfq1x:1,NS:BUSSTA
2024-06-13 10:18:22.350,"Zacks Investment Ideas feature highlights: AT&T, Verizon, Advanced Micro Devices, Walgreens Bo...",urn:newsml:reuters.com:20240613:nNRAsyg0nr:1,NS:ZACKSC
2024-06-13 10:17:50.624,"Zacks Investment Ideas feature highlights: Apple, Nvidia, INDA, EPI and SMIN",urn:newsml:reuters.com:20240613:nNRAsyg5ji:1,NS:ZACKSC

#### Get headlines within a range of dates

In [5]:
response = news.headlines.Definition(
    query="Refinitiv",
    date_from="20.03.2021", 
    date_to=timedelta(days=-4), 
    count=3
).get_data()
response.data.df

,headline,storyId,sourceCode
versionCreated,,,
2024-06-07 19:30:30.716,Refinitiv Wheat Price Update (WHTPR),urn:newsml:reuters.com:20240607:nIGB79199C:2,NS:RFT
2024-06-07 19:30:28.002,Refinitiv Soy Price Update (SOUPR),urn:newsml:reuters.com:20240607:nIGB79199B:2,NS:RFT
2024-06-07 19:30:21.949,Refinitiv Corn Price Update (CORPR),urn:newsml:reuters.com:20240607:nIGB79199A:2,NS:RFT

#### Get a limited number of headlines

In [6]:
response = news.headlines.Definition(query = "Google", count = 350).get_data()
response.data.df

,headline,storyId,sourceCode
versionCreated,,,
2024-06-13 12:01:35.977,*DJ Cognizant Launches First Set of Healthcare Large Language Model Solutions as Part of Generat...,urn:newsml:reuters.com:20240613:nDJR4H5dBR:2,NS:DJN
2024-06-13 12:01:00.000,*DJ Cognizant Launches First Set of Healthcare Large Language Model Solutions as Part of Generat...,urn:newsml:reuters.com:20240613:nDjc4H5dBR:2,NS:DJCP
2024-06-13 12:00:08.994,Press Release: Cognizant Launches First Set Of Healthcare Large Language Model Solutions As Part...,urn:newsml:reuters.com:20240613:nDJR1D6lb2:2,NS:DJN
2024-06-13 12:00:06.340,Cognizant Launches First Set Of Healthcare Large Language Model Solutions As Part Of Generative ...,urn:newsml:reuters.com:20240613:nPn5fJxGba:1,NS:PRN
2024-06-13 12:00:00.000,Cognizant Launches First Set Of Healthcare Large Language Model Solutions As Part Of Generative ...,urn:newsml:reuters.com:20240613:nDjc8k3kQ7:1,NS:DJCP
...,...,...,...
2024-06-05 19:12:02.662,Miljardenclaim tegen Google in VK om advertenties mag doorgaan (2),urn:newsml:reuters.com:20240605:nAnpm0dcZa:1,NS:ANP
2024-06-05 19:01:04.165,FILE PHOTO: The logo of Google LLC is seen at the Google Store Chelsea in New York City,urn:newsml:reuters.com:20240605:nRON5STZ3j:1,NS:RTRS
2024-06-05 19:01:03.165,2024-06-05T111344Z_1816080386_RC2FUY9UL36A_RTRMADP_1_BRITAIN-TECH-GOOGLE-ADTECH.JPG,urn:newsml:reuters.com:20240605:nRON4Lx5B1:1,NS:RTRS
2024-06-05 19:01:02.295,2024-06-05T111344Z_1816080386_RC2FUY9UL36A_RTRMADP_2_BRITAIN-TECH-GOOGLE-ADTECH.JPG,urn:newsml:reuters.com:20240605:nRON8dc8YZ:1,NS:RTRS
2024-06-05 18:52:17.549,DJ Google Parent Alphabet Poaches Eli Lilly Finance Chief Ashkenazi -- Update,urn:newsml:reuters.com:20240605:nDJR1zPW1F:1,NS:DJN

### Story

In [10]:
response = news.story.Definition("urn:newsml:reuters.com:20240613:nPn5fJxGba:1").get_data()
print(response.data.story.title, '\n')
HTML(response.data.story.content.html)

Cognizant Launches First Set Of Healthcare Large Language Model Solutions As Part Of Generative AI Partnership With Google Cloud

## Close the session

In [11]:
ld.close_session()